# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct DeliveryAppointmentApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `DeliveryAppointmentApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ DeliveryAppointmentApi }) = "https://demo.simplebilly.com"

const _returntypes_create_delivery_appointment_DeliveryAppointmentApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => DeliveryAppointment,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_delivery_appointment(_api::DeliveryAppointmentApi, delivery_appointment_create::DeliveryAppointmentCreate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_delivery_appointment_DeliveryAppointmentApi, "/api/v1/delivery-appointments", ["bearer_token", ], delivery_appointment_create)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `delivery_appointment_create`::`DeliveryAppointmentCreate` (required)

Return: `DeliveryAppointment`, `OpenAPI.Clients.ApiResponse`
"""
function create_delivery_appointment(_api::DeliveryAppointmentApi, delivery_appointment_create::DeliveryAppointmentCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_delivery_appointment(_api, delivery_appointment_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_delivery_appointment(_api::DeliveryAppointmentApi, response_stream::Channel, delivery_appointment_create::DeliveryAppointmentCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_delivery_appointment(_api, delivery_appointment_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_delivery_appointment_DeliveryAppointmentApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_delivery_appointment(_api::DeliveryAppointmentApi, appointment_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_delivery_appointment_DeliveryAppointmentApi, "/api/v1/delivery-appointments/{appointment_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "appointment_id", appointment_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `appointment_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_delivery_appointment(_api::DeliveryAppointmentApi, appointment_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_delivery_appointment(_api, appointment_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_delivery_appointment(_api::DeliveryAppointmentApi, response_stream::Channel, appointment_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_delivery_appointment(_api, appointment_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_delivery_appointment_DeliveryAppointmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DeliveryAppointment,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_delivery_appointment(_api::DeliveryAppointmentApi, appointment_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_delivery_appointment_DeliveryAppointmentApi, "/api/v1/delivery-appointments/{appointment_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "appointment_id", appointment_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `appointment_id`::`String` (required)

Return: `DeliveryAppointment`, `OpenAPI.Clients.ApiResponse`
"""
function get_delivery_appointment(_api::DeliveryAppointmentApi, appointment_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_delivery_appointment(_api, appointment_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_delivery_appointment(_api::DeliveryAppointmentApi, response_stream::Channel, appointment_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_delivery_appointment(_api, appointment_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_public_delivery_appointment_status_DeliveryAppointmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => PublicDeliveryAppointmentStatusResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_public_delivery_appointment_status(_api::DeliveryAppointmentApi, appointment_id::String, email::String, token::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_public_delivery_appointment_status_DeliveryAppointmentApi, "/api/v1/public/delivery-appointments/status", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "appointmentId", appointment_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "email", email; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "token", token; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Supplier/carrier checks appointment status (public, no auth). The appointment is only revealed when email AND token match.

Params:
- `appointment_id`::`String` (required)
- `email`::`String` (required)
- `token`::`String` (required)

Return: `PublicDeliveryAppointmentStatusResponse`, `OpenAPI.Clients.ApiResponse`
"""
function get_public_delivery_appointment_status(_api::DeliveryAppointmentApi, appointment_id::String, email::String, token::String; _mediaType=nothing)
    _ctx = _oacinternal_get_public_delivery_appointment_status(_api, appointment_id, email, token; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_public_delivery_appointment_status(_api::DeliveryAppointmentApi, response_stream::Channel, appointment_id::String, email::String, token::String; _mediaType=nothing)
    _ctx = _oacinternal_get_public_delivery_appointment_status(_api, appointment_id, email, token; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_delivery_appointments_DeliveryAppointmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{DeliveryAppointment},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_delivery_appointments(_api::DeliveryAppointmentApi; page=nothing, page_size=nothing, status=nothing, warehouse_id=nothing, from=nothing, to=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_delivery_appointments", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_delivery_appointments", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_delivery_appointments_DeliveryAppointmentApi, "/api/v1/delivery-appointments", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "status", status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "warehouse_id", warehouse_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "from", from; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "to", to; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `status`::`String`
- `warehouse_id`::`String`
- `from`::`Date`
- `to`::`Date`

Return: `Vector{DeliveryAppointment}`, `OpenAPI.Clients.ApiResponse`
"""
function list_delivery_appointments(_api::DeliveryAppointmentApi; page=nothing, page_size=nothing, status=nothing, warehouse_id=nothing, from=nothing, to=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_delivery_appointments(_api; page=page, page_size=page_size, status=status, warehouse_id=warehouse_id, from=from, to=to, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_delivery_appointments(_api::DeliveryAppointmentApi, response_stream::Channel; page=nothing, page_size=nothing, status=nothing, warehouse_id=nothing, from=nothing, to=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_delivery_appointments(_api; page=page, page_size=page_size, status=status, warehouse_id=warehouse_id, from=from, to=to, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_request_public_delivery_appointment_DeliveryAppointmentApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => PublicDeliveryAppointmentResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_request_public_delivery_appointment(_api::DeliveryAppointmentApi, public_delivery_appointment_request::PublicDeliveryAppointmentRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_request_public_delivery_appointment_DeliveryAppointmentApi, "/api/v1/public/delivery-appointments/request", ["bearer_token", ], public_delivery_appointment_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Supplier/carrier requests an inbound delivery slot (public, no auth). The tenant is derived from the warehouse found by `code` — never from the request.

Params:
- `public_delivery_appointment_request`::`PublicDeliveryAppointmentRequest` (required)

Return: `PublicDeliveryAppointmentResponse`, `OpenAPI.Clients.ApiResponse`
"""
function request_public_delivery_appointment(_api::DeliveryAppointmentApi, public_delivery_appointment_request::PublicDeliveryAppointmentRequest; _mediaType=nothing)
    _ctx = _oacinternal_request_public_delivery_appointment(_api, public_delivery_appointment_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function request_public_delivery_appointment(_api::DeliveryAppointmentApi, response_stream::Channel, public_delivery_appointment_request::PublicDeliveryAppointmentRequest; _mediaType=nothing)
    _ctx = _oacinternal_request_public_delivery_appointment(_api, public_delivery_appointment_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_delivery_appointment_DeliveryAppointmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DeliveryAppointment,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_delivery_appointment(_api::DeliveryAppointmentApi, appointment_id::String, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_delivery_appointment_DeliveryAppointmentApi, "/api/v1/delivery-appointments/{appointment_id}", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "appointment_id", appointment_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `appointment_id`::`String` (required)
- `body`::`Any` (required)

Return: `DeliveryAppointment`, `OpenAPI.Clients.ApiResponse`
"""
function update_delivery_appointment(_api::DeliveryAppointmentApi, appointment_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_delivery_appointment(_api, appointment_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_delivery_appointment(_api::DeliveryAppointmentApi, response_stream::Channel, appointment_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_delivery_appointment(_api, appointment_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_delivery_appointment_status_DeliveryAppointmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DeliveryAppointment,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_delivery_appointment_status(_api::DeliveryAppointmentApi, appointment_id::String, appointment_status_update::AppointmentStatusUpdate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_delivery_appointment_status_DeliveryAppointmentApi, "/api/v1/delivery-appointments/{appointment_id}/status", ["bearer_token", ], appointment_status_update)
    OpenAPI.Clients.set_param(_ctx.path, "appointment_id", appointment_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `appointment_id`::`String` (required)
- `appointment_status_update`::`AppointmentStatusUpdate` (required)

Return: `DeliveryAppointment`, `OpenAPI.Clients.ApiResponse`
"""
function update_delivery_appointment_status(_api::DeliveryAppointmentApi, appointment_id::String, appointment_status_update::AppointmentStatusUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_delivery_appointment_status(_api, appointment_id, appointment_status_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_delivery_appointment_status(_api::DeliveryAppointmentApi, response_stream::Channel, appointment_id::String, appointment_status_update::AppointmentStatusUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_delivery_appointment_status(_api, appointment_id, appointment_status_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_delivery_appointment
export delete_delivery_appointment
export get_delivery_appointment
export get_public_delivery_appointment_status
export list_delivery_appointments
export request_public_delivery_appointment
export update_delivery_appointment
export update_delivery_appointment_status
