# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct RfqApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `RfqApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ RfqApi }) = "https://demo.simplebilly.com"

const _returntypes_convert_rfq_RfqApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Any,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_convert_rfq(_api::RfqApi, rfq_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_convert_rfq_RfqApi, "/api/v1/rfqs/{rfq_id}/convert", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "rfq_id", rfq_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Convert an RFQ into a draft purchase order using the quoted unit prices (falling back to the requested prices, then leaving them blank). Marks the RFQ as `converted`.

Params:
- `rfq_id`::`String` (required)

Return: `Any`, `OpenAPI.Clients.ApiResponse`
"""
function convert_rfq(_api::RfqApi, rfq_id::String; _mediaType=nothing)
    _ctx = _oacinternal_convert_rfq(_api, rfq_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function convert_rfq(_api::RfqApi, response_stream::Channel, rfq_id::String; _mediaType=nothing)
    _ctx = _oacinternal_convert_rfq(_api, rfq_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_create_rfq_RfqApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Rfq,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_rfq(_api::RfqApi, rfq::Rfq; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_rfq_RfqApi, "/api/v1/rfqs", ["bearer_token", ], rfq)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `rfq`::`Rfq` (required)

Return: `Rfq`, `OpenAPI.Clients.ApiResponse`
"""
function create_rfq(_api::RfqApi, rfq::Rfq; _mediaType=nothing)
    _ctx = _oacinternal_create_rfq(_api, rfq; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_rfq(_api::RfqApi, response_stream::Channel, rfq::Rfq; _mediaType=nothing)
    _ctx = _oacinternal_create_rfq(_api, rfq; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_rfq_RfqApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_rfq(_api::RfqApi, rfq_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_rfq_RfqApi, "/api/v1/rfqs/{rfq_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "rfq_id", rfq_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `rfq_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_rfq(_api::RfqApi, rfq_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_rfq(_api, rfq_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_rfq(_api::RfqApi, response_stream::Channel, rfq_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_rfq(_api, rfq_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_rfq_RfqApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Rfq,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_rfq(_api::RfqApi, rfq_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_rfq_RfqApi, "/api/v1/rfqs/{rfq_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "rfq_id", rfq_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `rfq_id`::`String` (required)

Return: `Rfq`, `OpenAPI.Clients.ApiResponse`
"""
function get_rfq(_api::RfqApi, rfq_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_rfq(_api, rfq_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_rfq(_api::RfqApi, response_stream::Channel, rfq_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_rfq(_api, rfq_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_rfqs_RfqApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Rfq},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_rfqs(_api::RfqApi; page=nothing, page_size=nothing, status=nothing, supplier_name=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_rfqs", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_rfqs", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_rfqs_RfqApi, "/api/v1/rfqs/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "status", status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "supplier_name", supplier_name; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `status`::`String`
- `supplier_name`::`String`

Return: `Vector{Rfq}`, `OpenAPI.Clients.ApiResponse`
"""
function list_rfqs(_api::RfqApi; page=nothing, page_size=nothing, status=nothing, supplier_name=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_rfqs(_api; page=page, page_size=page_size, status=status, supplier_name=supplier_name, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_rfqs(_api::RfqApi, response_stream::Channel; page=nothing, page_size=nothing, status=nothing, supplier_name=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_rfqs(_api; page=page, page_size=page_size, status=status, supplier_name=supplier_name, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_rfq_RfqApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Rfq,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_rfq(_api::RfqApi, rfq_id::String, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_rfq_RfqApi, "/api/v1/rfqs/{rfq_id}", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "rfq_id", rfq_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `rfq_id`::`String` (required)
- `body`::`Any` (required)

Return: `Rfq`, `OpenAPI.Clients.ApiResponse`
"""
function update_rfq(_api::RfqApi, rfq_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_rfq(_api, rfq_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_rfq(_api::RfqApi, response_stream::Channel, rfq_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_rfq(_api, rfq_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_rfq_status_RfqApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Rfq,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_rfq_status(_api::RfqApi, rfq_id::String, rfq_status_update::RfqStatusUpdate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_rfq_status_RfqApi, "/api/v1/rfqs/{rfq_id}/status", ["bearer_token", ], rfq_status_update)
    OpenAPI.Clients.set_param(_ctx.path, "rfq_id", rfq_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `rfq_id`::`String` (required)
- `rfq_status_update`::`RfqStatusUpdate` (required)

Return: `Rfq`, `OpenAPI.Clients.ApiResponse`
"""
function update_rfq_status(_api::RfqApi, rfq_id::String, rfq_status_update::RfqStatusUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_rfq_status(_api, rfq_id, rfq_status_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_rfq_status(_api::RfqApi, response_stream::Channel, rfq_id::String, rfq_status_update::RfqStatusUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_rfq_status(_api, rfq_id, rfq_status_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export convert_rfq
export create_rfq
export delete_rfq
export get_rfq
export list_rfqs
export update_rfq
export update_rfq_status
