# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct BookkeepingApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `BookkeepingApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ BookkeepingApi }) = "https://demo.simplebilly.com"

const _returntypes_allocate_payment_api_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_allocate_payment_api(_api::BookkeepingApi, allocate_payment_request::AllocatePaymentRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_allocate_payment_api_BookkeepingApi, "/api/v1/payments/allocate", ["bearer_token", ], allocate_payment_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Allocate a payment to an invoice

Params:
- `allocate_payment_request`::`AllocatePaymentRequest` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function allocate_payment_api(_api::BookkeepingApi, allocate_payment_request::AllocatePaymentRequest; _mediaType=nothing)
    _ctx = _oacinternal_allocate_payment_api(_api, allocate_payment_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function allocate_payment_api(_api::BookkeepingApi, response_stream::Channel, allocate_payment_request::AllocatePaymentRequest; _mediaType=nothing)
    _ctx = _oacinternal_allocate_payment_api(_api, allocate_payment_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_bwa_report_api_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => BWAReport,
    Regex("^" * replace("500", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_bwa_report_api(_api::BookkeepingApi; year=nothing, month=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_bwa_report_api_BookkeepingApi, "/api/v1/bookkeeping/bwa", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "year", year; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "month", month; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get BWA (Betriebswirtschaftliche Auswertung) report

Params:
- `year`::`Int64`
- `month`::`Int64`

Return: `BWAReport`, `OpenAPI.Clients.ApiResponse`
"""
function bwa_report_api(_api::BookkeepingApi; year=nothing, month=nothing, _mediaType=nothing)
    _ctx = _oacinternal_bwa_report_api(_api; year=year, month=month, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function bwa_report_api(_api::BookkeepingApi, response_stream::Channel; year=nothing, month=nothing, _mediaType=nothing)
    _ctx = _oacinternal_bwa_report_api(_api; year=year, month=month, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_elster_status_api_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ElsterStatus,
)

function _oacinternal_elster_status_api(_api::BookkeepingApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_elster_status_api_BookkeepingApi, "/api/v1/bookkeeping/elster/status", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:

Return: `ElsterStatus`, `OpenAPI.Clients.ApiResponse`
"""
function elster_status_api(_api::BookkeepingApi; _mediaType=nothing)
    _ctx = _oacinternal_elster_status_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function elster_status_api(_api::BookkeepingApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_elster_status_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_elster_validate_api_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_elster_validate_api(_api::BookkeepingApi, zeitraum::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_elster_validate_api_BookkeepingApi, "/api/v1/bookkeeping/ustva/elster-validate", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "zeitraum", zeitraum; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, [])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `zeitraum`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function elster_validate_api(_api::BookkeepingApi, zeitraum::String; _mediaType=nothing)
    _ctx = _oacinternal_elster_validate_api(_api, zeitraum; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function elster_validate_api(_api::BookkeepingApi, response_stream::Channel, zeitraum::String; _mediaType=nothing)
    _ctx = _oacinternal_elster_validate_api(_api, zeitraum; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_elster_xml_api_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_elster_xml_api(_api::BookkeepingApi, zeitraum::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_elster_xml_api_BookkeepingApi, "/api/v1/bookkeeping/ustva/elster-xml", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "zeitraum", zeitraum; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, [])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `zeitraum`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function elster_xml_api(_api::BookkeepingApi, zeitraum::String; _mediaType=nothing)
    _ctx = _oacinternal_elster_xml_api(_api, zeitraum; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function elster_xml_api(_api::BookkeepingApi, response_stream::Channel, zeitraum::String; _mediaType=nothing)
    _ctx = _oacinternal_elster_xml_api(_api, zeitraum; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_cashflow_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => CashflowReport,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_cashflow(_api::BookkeepingApi; year=nothing, month=nothing, _mediaType=nothing)
    OpenAPI.validate_param("month", "get_cashflow", :minimum, month, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_cashflow_BookkeepingApi, "/api/v1/bookkeeping/cashflow", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "year", year; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "month", month; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""GET /api/v1/bookkeeping/cashflow Returns operating, investing, and financing cashflow for the given period.

Params:
- `year`::`Int64`
- `month`::`Int64`

Return: `CashflowReport`, `OpenAPI.Clients.ApiResponse`
"""
function get_cashflow(_api::BookkeepingApi; year=nothing, month=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_cashflow(_api; year=year, month=month, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_cashflow(_api::BookkeepingApi, response_stream::Channel; year=nothing, month=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_cashflow(_api; year=year, month=month, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_liquidity_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => LiquidityPosition,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_liquidity(_api::BookkeepingApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_liquidity_BookkeepingApi, "/api/v1/bookkeeping/liquidity", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""GET /api/v1/bookkeeping/liquidity Returns current liquidity position with ratios.

Params:

Return: `LiquidityPosition`, `OpenAPI.Clients.ApiResponse`
"""
function get_liquidity(_api::BookkeepingApi; _mediaType=nothing)
    _ctx = _oacinternal_get_liquidity(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_liquidity(_api::BookkeepingApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_get_liquidity(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_open_invoices_api_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Invoice},
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_open_invoices_api(_api::BookkeepingApi, customer_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_open_invoices_api_BookkeepingApi, "/api/v1/payments/open-invoices/{customer_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "customer_id", customer_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get open invoices for a customer

Params:
- `customer_id`::`String` (required)

Return: `Vector{Invoice}`, `OpenAPI.Clients.ApiResponse`
"""
function get_open_invoices_api(_api::BookkeepingApi, customer_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_open_invoices_api(_api, customer_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_open_invoices_api(_api::BookkeepingApi, response_stream::Channel, customer_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_open_invoices_api(_api, customer_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_verfahrensdokumentation_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Verfahrensdokumentation,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_verfahrensdokumentation(_api::BookkeepingApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_verfahrensdokumentation_BookkeepingApi, "/api/v1/bookkeeping/verfahrensdokumentation", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""GET /api/v1/bookkeeping/verfahrensdokumentation Returns the complete compliance catalog of all documented modules.

Params:

Return: `Verfahrensdokumentation`, `OpenAPI.Clients.ApiResponse`
"""
function get_verfahrensdokumentation(_api::BookkeepingApi; _mediaType=nothing)
    _ctx = _oacinternal_get_verfahrensdokumentation(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_verfahrensdokumentation(_api::BookkeepingApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_get_verfahrensdokumentation(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_run_dunning_api_BookkeepingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => DunningResult,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_run_dunning_api(_api::BookkeepingApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_run_dunning_api_BookkeepingApi, "/api/v1/bookkeeping/dunning", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:

Return: `DunningResult`, `OpenAPI.Clients.ApiResponse`
"""
function run_dunning_api(_api::BookkeepingApi; _mediaType=nothing)
    _ctx = _oacinternal_run_dunning_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function run_dunning_api(_api::BookkeepingApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_run_dunning_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export allocate_payment_api
export bwa_report_api
export elster_status_api
export elster_validate_api
export elster_xml_api
export get_cashflow
export get_liquidity
export get_open_invoices_api
export get_verfahrensdokumentation
export run_dunning_api
