# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PayrollApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PayrollApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PayrollApi }) = "https://demo.simplebilly.com"

const _returntypes_payroll_approve_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => PayrollRunApi,
)

function _oacinternal_payroll_approve(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payroll_approve_PayrollApi, "/api/v1/payroll/{id}/approve", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `PayrollRunApi`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_approve(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_approve(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_approve(_api::PayrollApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_approve(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_autopay_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Any,
)

function _oacinternal_payroll_autopay(_api::PayrollApi, id::String; body=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payroll_autopay_PayrollApi, "/api/v1/payroll/{id}/autopay", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)
- `body`::`Any`

Return: `Any`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_autopay(_api::PayrollApi, id::String; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_payroll_autopay(_api, id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_autopay(_api::PayrollApi, response_stream::Channel, id::String; body=nothing, _mediaType=nothing)
    _ctx = _oacinternal_payroll_autopay(_api, id; body=body, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_calculate_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => PayrollRunApi,
)

function _oacinternal_payroll_calculate(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payroll_calculate_PayrollApi, "/api/v1/payroll/{id}/calculate", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `PayrollRunApi`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_calculate(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_calculate(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_calculate(_api::PayrollApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_calculate(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_create_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => PayrollRunApi,
)

function _oacinternal_payroll_create(_api::PayrollApi, payroll_create_payload::PayrollCreatePayload; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payroll_create_PayrollApi, "/api/v1/payroll", ["bearer_token", ], payroll_create_payload)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `payroll_create_payload`::`PayrollCreatePayload` (required)

Return: `PayrollRunApi`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_create(_api::PayrollApi, payroll_create_payload::PayrollCreatePayload; _mediaType=nothing)
    _ctx = _oacinternal_payroll_create(_api, payroll_create_payload; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_create(_api::PayrollApi, response_stream::Channel, payroll_create_payload::PayrollCreatePayload; _mediaType=nothing)
    _ctx = _oacinternal_payroll_create(_api, payroll_create_payload; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_delete_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_payroll_delete(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_payroll_delete_PayrollApi, "/api/v1/payroll/{id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, [])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_delete(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_delete(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_delete(_api::PayrollApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_delete(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_elster_export_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_payroll_elster_export(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payroll_elster_export_PayrollApi, "/api/v1/payroll/{id}/elster-export", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, [])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_elster_export(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_elster_export(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_elster_export(_api::PayrollApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_elster_export(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_email_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Any,
)

function _oacinternal_payroll_email(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payroll_email_PayrollApi, "/api/v1/payroll/{id}/email", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Any`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_email(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_email(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_email(_api::PayrollApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_email(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_entry_pdf_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_payroll_entry_pdf(_api::PayrollApi, id::String, entry_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_payroll_entry_pdf_PayrollApi, "/api/v1/payroll/{id}/entries/{entry_id}/pdf", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_param(_ctx.path, "entry_id", entry_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/pdf", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)
- `entry_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_entry_pdf(_api::PayrollApi, id::String, entry_id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_entry_pdf(_api, id, entry_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_entry_pdf(_api::PayrollApi, response_stream::Channel, id::String, entry_id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_entry_pdf(_api, id, entry_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_get_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => PayrollRunApi,
)

function _oacinternal_payroll_get(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_payroll_get_PayrollApi, "/api/v1/payroll/{id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `PayrollRunApi`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_get(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_get(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_get(_api::PayrollApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_get(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_list_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{PayrollRunApi},
)

function _oacinternal_payroll_list(_api::PayrollApi; year=nothing, status=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_payroll_list_PayrollApi, "/api/v1/payroll", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "year", year; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "status", status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64`
- `status`::`String`

Return: `Vector{PayrollRunApi}`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_list(_api::PayrollApi; year=nothing, status=nothing, _mediaType=nothing)
    _ctx = _oacinternal_payroll_list(_api; year=year, status=status, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_list(_api::PayrollApi, response_stream::Channel; year=nothing, status=nothing, _mediaType=nothing)
    _ctx = _oacinternal_payroll_list(_api; year=year, status=status, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_pay_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => PayrollRunApi,
)

function _oacinternal_payroll_pay(_api::PayrollApi, id::String, payroll_pay_payload::PayrollPayPayload; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payroll_pay_PayrollApi, "/api/v1/payroll/{id}/pay", ["bearer_token", ], payroll_pay_payload)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)
- `payroll_pay_payload`::`PayrollPayPayload` (required)

Return: `PayrollRunApi`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_pay(_api::PayrollApi, id::String, payroll_pay_payload::PayrollPayPayload; _mediaType=nothing)
    _ctx = _oacinternal_payroll_pay(_api, id, payroll_pay_payload; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_pay(_api::PayrollApi, response_stream::Channel, id::String, payroll_pay_payload::PayrollPayPayload; _mediaType=nothing)
    _ctx = _oacinternal_payroll_pay(_api, id, payroll_pay_payload; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_pdf_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_payroll_pdf(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_payroll_pdf_PayrollApi, "/api/v1/payroll/{id}/pdf", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/pdf", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_pdf(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_pdf(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_pdf(_api::PayrollApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_pdf(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_summary_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => YearlyPayrollSummary,
)

function _oacinternal_payroll_summary(_api::PayrollApi, year::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_payroll_summary_PayrollApi, "/api/v1/payroll/summary/{year}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "year", year)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64` (required)

Return: `YearlyPayrollSummary`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_summary(_api::PayrollApi, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_payroll_summary(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_summary(_api::PayrollApi, response_stream::Channel, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_payroll_summary(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payroll_sv_meldungen_PayrollApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Any,
)

function _oacinternal_payroll_sv_meldungen(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payroll_sv_meldungen_PayrollApi, "/api/v1/payroll/{id}/sv-meldungen", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Any`, `OpenAPI.Clients.ApiResponse`
"""
function payroll_sv_meldungen(_api::PayrollApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_sv_meldungen(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payroll_sv_meldungen(_api::PayrollApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payroll_sv_meldungen(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export payroll_approve
export payroll_autopay
export payroll_calculate
export payroll_create
export payroll_delete
export payroll_elster_export
export payroll_email
export payroll_entry_pdf
export payroll_get
export payroll_list
export payroll_pay
export payroll_pdf
export payroll_summary
export payroll_sv_meldungen
