# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct TimeEntriesApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `TimeEntriesApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ TimeEntriesApi }) = "https://demo.simplebilly.com"

const _returntypes_clock_in_time_entry_TimeEntriesApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => TimeEntryDto,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_clock_in_time_entry(_api::TimeEntriesApi, time_entry_clock_in::TimeEntryClockIn; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_clock_in_time_entry_TimeEntriesApi, "/api/v1/time-entries", ["bearer_token", ], time_entry_clock_in)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Clock in for the authenticated user (resolved via their employee profile).

Params:
- `time_entry_clock_in`::`TimeEntryClockIn` (required)

Return: `TimeEntryDto`, `OpenAPI.Clients.ApiResponse`
"""
function clock_in_time_entry(_api::TimeEntriesApi, time_entry_clock_in::TimeEntryClockIn; _mediaType=nothing)
    _ctx = _oacinternal_clock_in_time_entry(_api, time_entry_clock_in; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function clock_in_time_entry(_api::TimeEntriesApi, response_stream::Channel, time_entry_clock_in::TimeEntryClockIn; _mediaType=nothing)
    _ctx = _oacinternal_clock_in_time_entry(_api, time_entry_clock_in; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_clock_out_time_entry_TimeEntriesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => TimeEntryDto,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("403", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_clock_out_time_entry(_api::TimeEntriesApi, id::String, time_entry_clock_out::TimeEntryClockOut; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PATCH", _returntypes_clock_out_time_entry_TimeEntriesApi, "/api/v1/time-entries/{id}", ["bearer_token", ], time_entry_clock_out)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Clock out an entry: the entry's owner, or anyone with `time_entries:write`.

Params:
- `id`::`String` (required)
- `time_entry_clock_out`::`TimeEntryClockOut` (required)

Return: `TimeEntryDto`, `OpenAPI.Clients.ApiResponse`
"""
function clock_out_time_entry(_api::TimeEntriesApi, id::String, time_entry_clock_out::TimeEntryClockOut; _mediaType=nothing)
    _ctx = _oacinternal_clock_out_time_entry(_api, id, time_entry_clock_out; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function clock_out_time_entry(_api::TimeEntriesApi, response_stream::Channel, id::String, time_entry_clock_out::TimeEntryClockOut; _mediaType=nothing)
    _ctx = _oacinternal_clock_out_time_entry(_api, id, time_entry_clock_out; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_labor_costs_TimeEntriesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{LaborCostRow},
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_labor_costs(_api::TimeEntriesApi, from::Date, to::Date, group_by::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_labor_costs_TimeEntriesApi, "/api/v1/labor-costs", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "from", from; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "to", to; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "group_by", group_by; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Labor-cost report: worked hours aggregated per employee / order / day, valued at the employee's hourly cost rate.

Params:
- `from`::`Date` (required)
- `to`::`Date` (required)
- `group_by`::`String` (required)

Return: `Vector{LaborCostRow}`, `OpenAPI.Clients.ApiResponse`
"""
function get_labor_costs(_api::TimeEntriesApi, from::Date, to::Date, group_by::String; _mediaType=nothing)
    _ctx = _oacinternal_get_labor_costs(_api, from, to, group_by; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_labor_costs(_api::TimeEntriesApi, response_stream::Channel, from::Date, to::Date, group_by::String; _mediaType=nothing)
    _ctx = _oacinternal_get_labor_costs(_api, from, to, group_by; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_time_entries_TimeEntriesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{TimeEntryDto},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_time_entries(_api::TimeEntriesApi; from=nothing, to=nothing, active=nothing, employee_id=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_time_entries_TimeEntriesApi, "/api/v1/time-entries", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "from", from; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "to", to; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "active", active; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_param(_ctx.query, "employee_id", employee_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List time entries with optional date-range / active / employee filters.

Params:
- `from`::`Date`
- `to`::`Date`
- `active`::`Bool`
- `employee_id`::`String`

Return: `Vector{TimeEntryDto}`, `OpenAPI.Clients.ApiResponse`
"""
function list_time_entries(_api::TimeEntriesApi; from=nothing, to=nothing, active=nothing, employee_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_time_entries(_api; from=from, to=to, active=active, employee_id=employee_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_time_entries(_api::TimeEntriesApi, response_stream::Channel; from=nothing, to=nothing, active=nothing, employee_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_time_entries(_api; from=from, to=to, active=active, employee_id=employee_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export clock_in_time_entry
export clock_out_time_entry
export get_labor_costs
export list_time_entries
