# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ReturnOrderApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ReturnOrderApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ReturnOrderApi }) = "https://demo.simplebilly.com"

const _returntypes_create_return_order_ReturnOrderApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => ReturnOrder,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_return_order(_api::ReturnOrderApi, return_order::ReturnOrder; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_return_order_ReturnOrderApi, "/api/v1/returns", ["bearer_token", ], return_order)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `return_order`::`ReturnOrder` (required)

Return: `ReturnOrder`, `OpenAPI.Clients.ApiResponse`
"""
function create_return_order(_api::ReturnOrderApi, return_order::ReturnOrder; _mediaType=nothing)
    _ctx = _oacinternal_create_return_order(_api, return_order; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_return_order(_api::ReturnOrderApi, response_stream::Channel, return_order::ReturnOrder; _mediaType=nothing)
    _ctx = _oacinternal_create_return_order(_api, return_order; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_return_order_ReturnOrderApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_return_order(_api::ReturnOrderApi, return_order_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_return_order_ReturnOrderApi, "/api/v1/returns/{return_order_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "return_order_id", return_order_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `return_order_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_return_order(_api::ReturnOrderApi, return_order_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_return_order(_api, return_order_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_return_order(_api::ReturnOrderApi, response_stream::Channel, return_order_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_return_order(_api, return_order_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_return_order_ReturnOrderApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ReturnOrder,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_return_order(_api::ReturnOrderApi, return_order_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_return_order_ReturnOrderApi, "/api/v1/returns/{return_order_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "return_order_id", return_order_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `return_order_id`::`String` (required)

Return: `ReturnOrder`, `OpenAPI.Clients.ApiResponse`
"""
function get_return_order(_api::ReturnOrderApi, return_order_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_return_order(_api, return_order_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_return_order(_api::ReturnOrderApi, response_stream::Channel, return_order_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_return_order(_api, return_order_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_return_orders_ReturnOrderApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{ReturnOrder},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_return_orders(_api::ReturnOrderApi; page=nothing, page_size=nothing, status=nothing, customer_name=nothing, order_number=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_return_orders", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_return_orders", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_return_orders_ReturnOrderApi, "/api/v1/returns/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "status", status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "customer_name", customer_name; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "order_number", order_number; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `status`::`String`
- `customer_name`::`String`
- `order_number`::`String`

Return: `Vector{ReturnOrder}`, `OpenAPI.Clients.ApiResponse`
"""
function list_return_orders(_api::ReturnOrderApi; page=nothing, page_size=nothing, status=nothing, customer_name=nothing, order_number=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_return_orders(_api; page=page, page_size=page_size, status=status, customer_name=customer_name, order_number=order_number, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_return_orders(_api::ReturnOrderApi, response_stream::Channel; page=nothing, page_size=nothing, status=nothing, customer_name=nothing, order_number=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_return_orders(_api; page=page, page_size=page_size, status=status, customer_name=customer_name, order_number=order_number, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_return_logistics_queue_ReturnOrderApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{ReturnLogisticsQueueItem},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_return_logistics_queue(_api::ReturnOrderApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_return_logistics_queue_ReturnOrderApi, "/api/v1/returns/logistics-queue", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:

Return: `Vector{ReturnLogisticsQueueItem}`, `OpenAPI.Clients.ApiResponse`
"""
function return_logistics_queue(_api::ReturnOrderApi; _mediaType=nothing)
    _ctx = _oacinternal_return_logistics_queue(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function return_logistics_queue(_api::ReturnOrderApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_return_logistics_queue(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_return_logistics_summary_ReturnOrderApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ReturnLogisticsSummary,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_return_logistics_summary(_api::ReturnOrderApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_return_logistics_summary_ReturnOrderApi, "/api/v1/returns/logistics-summary", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Returns-logistics aggregation for the dashboard: quantities received, restocked and scrapped per warehouse.

Params:

Return: `ReturnLogisticsSummary`, `OpenAPI.Clients.ApiResponse`
"""
function return_logistics_summary(_api::ReturnOrderApi; _mediaType=nothing)
    _ctx = _oacinternal_return_logistics_summary(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function return_logistics_summary(_api::ReturnOrderApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_return_logistics_summary(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_return_order_ReturnOrderApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ReturnOrder,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_return_order(_api::ReturnOrderApi, return_order_id::String, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_return_order_ReturnOrderApi, "/api/v1/returns/{return_order_id}", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "return_order_id", return_order_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `return_order_id`::`String` (required)
- `body`::`Any` (required)

Return: `ReturnOrder`, `OpenAPI.Clients.ApiResponse`
"""
function update_return_order(_api::ReturnOrderApi, return_order_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_return_order(_api, return_order_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_return_order(_api::ReturnOrderApi, response_stream::Channel, return_order_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_return_order(_api, return_order_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_return_order_status_ReturnOrderApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ReturnOrder,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_return_order_status(_api::ReturnOrderApi, return_order_id::String, return_order_status_update::ReturnOrderStatusUpdate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_return_order_status_ReturnOrderApi, "/api/v1/returns/{return_order_id}/status", ["bearer_token", ], return_order_status_update)
    OpenAPI.Clients.set_param(_ctx.path, "return_order_id", return_order_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `return_order_id`::`String` (required)
- `return_order_status_update`::`ReturnOrderStatusUpdate` (required)

Return: `ReturnOrder`, `OpenAPI.Clients.ApiResponse`
"""
function update_return_order_status(_api::ReturnOrderApi, return_order_id::String, return_order_status_update::ReturnOrderStatusUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_return_order_status(_api, return_order_id, return_order_status_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_return_order_status(_api::ReturnOrderApi, response_stream::Channel, return_order_id::String, return_order_status_update::ReturnOrderStatusUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_return_order_status(_api, return_order_id, return_order_status_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_return_order
export delete_return_order
export get_return_order
export list_return_orders
export return_logistics_queue
export return_logistics_summary
export update_return_order
export update_return_order_status
