# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ReplenishmentApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ReplenishmentApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ReplenishmentApi }) = "https://demo.simplebilly.com"

const _returntypes_apply_replenishments_ReplenishmentApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Any,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_apply_replenishments(_api::ReplenishmentApi; target_warehouse_id=nothing, source_warehouse_id=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_apply_replenishments_ReplenishmentApi, "/api/v1/replenishments/apply", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "targetWarehouseId", target_warehouse_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "sourceWarehouseId", source_warehouse_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Create one draft stock transfer per (source → target) pair carrying all suggested product lines for that pair.

Params:
- `target_warehouse_id`::`String`
- `source_warehouse_id`::`String`

Return: `Any`, `OpenAPI.Clients.ApiResponse`
"""
function apply_replenishments(_api::ReplenishmentApi; target_warehouse_id=nothing, source_warehouse_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_apply_replenishments(_api; target_warehouse_id=target_warehouse_id, source_warehouse_id=source_warehouse_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function apply_replenishments(_api::ReplenishmentApi, response_stream::Channel; target_warehouse_id=nothing, source_warehouse_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_apply_replenishments(_api; target_warehouse_id=target_warehouse_id, source_warehouse_id=source_warehouse_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_replenishments_ReplenishmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ReplenishmentResponse,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_replenishments(_api::ReplenishmentApi; target_warehouse_id=nothing, source_warehouse_id=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_replenishments_ReplenishmentApi, "/api/v1/replenishments", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "targetWarehouseId", target_warehouse_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "sourceWarehouseId", source_warehouse_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `target_warehouse_id`::`String`
- `source_warehouse_id`::`String`

Return: `ReplenishmentResponse`, `OpenAPI.Clients.ApiResponse`
"""
function get_replenishments(_api::ReplenishmentApi; target_warehouse_id=nothing, source_warehouse_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_replenishments(_api; target_warehouse_id=target_warehouse_id, source_warehouse_id=source_warehouse_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_replenishments(_api::ReplenishmentApi, response_stream::Channel; target_warehouse_id=nothing, source_warehouse_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_replenishments(_api; target_warehouse_id=target_warehouse_id, source_warehouse_id=source_warehouse_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export apply_replenishments
export get_replenishments
