# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct BankingApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `BankingApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ BankingApi }) = "https://demo.simplebilly.com"

const _returntypes_bank_lookup_api_BankingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => BankLookup,
)

function _oacinternal_bank_lookup_api(_api::BankingApi, iban::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_bank_lookup_api_BankingApi, "/api/v1/bookkeeping/banking/lookup", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "iban", iban; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `iban`::`String` (required)

Return: `BankLookup`, `OpenAPI.Clients.ApiResponse`
"""
function bank_lookup_api(_api::BankingApi, iban::String; _mediaType=nothing)
    _ctx = _oacinternal_bank_lookup_api(_api, iban; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function bank_lookup_api(_api::BankingApi, response_stream::Channel, iban::String; _mediaType=nothing)
    _ctx = _oacinternal_bank_lookup_api(_api, iban; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_bank_transactions_api_BankingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_bank_transactions_api(_api::BankingApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_bank_transactions_api_BankingApi, "/api/v1/bookkeeping/banking/transactions", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, [])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function bank_transactions_api(_api::BankingApi; _mediaType=nothing)
    _ctx = _oacinternal_bank_transactions_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function bank_transactions_api(_api::BankingApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_bank_transactions_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_hebesatz_lookup_api_BankingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{HebesatzLookup},
)

function _oacinternal_hebesatz_lookup_api(_api::BankingApi; gemeindeschluessel=nothing, plz=nothing, name=nothing, stichtag=nothing, country_code=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_hebesatz_lookup_api_BankingApi, "/api/v1/bookkeeping/hebesatz", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "gemeindeschluessel", gemeindeschluessel; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "plz", plz; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "name", name; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "stichtag", stichtag; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "country_code", country_code; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `gemeindeschluessel`::`String`
- `plz`::`String`
- `name`::`String`
- `stichtag`::`String`
- `country_code`::`String`

Return: `Vector{HebesatzLookup}`, `OpenAPI.Clients.ApiResponse`
"""
function hebesatz_lookup_api(_api::BankingApi; gemeindeschluessel=nothing, plz=nothing, name=nothing, stichtag=nothing, country_code=nothing, _mediaType=nothing)
    _ctx = _oacinternal_hebesatz_lookup_api(_api; gemeindeschluessel=gemeindeschluessel, plz=plz, name=name, stichtag=stichtag, country_code=country_code, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function hebesatz_lookup_api(_api::BankingApi, response_stream::Channel; gemeindeschluessel=nothing, plz=nothing, name=nothing, stichtag=nothing, country_code=nothing, _mediaType=nothing)
    _ctx = _oacinternal_hebesatz_lookup_api(_api; gemeindeschluessel=gemeindeschluessel, plz=plz, name=name, stichtag=stichtag, country_code=country_code, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export bank_lookup_api
export bank_transactions_api
export hebesatz_lookup_api
