# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ProposeAssignmentsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ProposeAssignmentsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ProposeAssignmentsApi }) = "https://demo.simplebilly.com"

const _returntypes_propose_assignments_api_ProposeAssignmentsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{ProposedAssignment},
    Regex("^" * replace("500", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_propose_assignments_api(_api::ProposeAssignmentsApi; min_confidence=nothing, customer_id=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_propose_assignments_api_ProposeAssignmentsApi, "/api/v1/bookkeeping/propose-assignments", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "min_confidence", min_confidence; style="form", is_explode=true)  # type Float64
    OpenAPI.Clients.set_param(_ctx.query, "customer_id", customer_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `min_confidence`::`Float64`
- `customer_id`::`String`

Return: `Vector{ProposedAssignment}`, `OpenAPI.Clients.ApiResponse`
"""
function propose_assignments_api(_api::ProposeAssignmentsApi; min_confidence=nothing, customer_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_propose_assignments_api(_api; min_confidence=min_confidence, customer_id=customer_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function propose_assignments_api(_api::ProposeAssignmentsApi, response_stream::Channel; min_confidence=nothing, customer_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_propose_assignments_api(_api; min_confidence=min_confidence, customer_id=customer_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export propose_assignments_api
