# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PaymentConditionApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PaymentConditionApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PaymentConditionApi }) = "https://demo.simplebilly.com"

const _returntypes_list_payment_conditions_api_PaymentConditionApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{PaymentCondition},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_payment_conditions_api(_api::PaymentConditionApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_payment_conditions_api_PaymentConditionApi, "/api/v1/payment-conditions", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:

Return: `Vector{PaymentCondition}`, `OpenAPI.Clients.ApiResponse`
"""
function list_payment_conditions_api(_api::PaymentConditionApi; _mediaType=nothing)
    _ctx = _oacinternal_list_payment_conditions_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_payment_conditions_api(_api::PaymentConditionApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_list_payment_conditions_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export list_payment_conditions_api
