# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct OffenlegungApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `OffenlegungApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ OffenlegungApi }) = "https://demo.simplebilly.com"

const _returntypes_offenlegung_api_OffenlegungApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => OffenlegungReport,
)

function _oacinternal_offenlegung_api(_api::OffenlegungApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_offenlegung_api_OffenlegungApi, "/api/v1/bookkeeping/offenlegung", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:

Return: `OffenlegungReport`, `OpenAPI.Clients.ApiResponse`
"""
function offenlegung_api(_api::OffenlegungApi; _mediaType=nothing)
    _ctx = _oacinternal_offenlegung_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function offenlegung_api(_api::OffenlegungApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_offenlegung_api(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export offenlegung_api
