# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct GroupFigureApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `GroupFigureApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ GroupFigureApi }) = "https://demo.simplebilly.com"

const _returntypes_create_group_figure_GroupFigureApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => GroupFigure,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_group_figure(_api::GroupFigureApi, group_figure_create::GroupFigureCreate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_group_figure_GroupFigureApi, "/api/v1/group-figures", ["bearer_token", ], group_figure_create)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `group_figure_create`::`GroupFigureCreate` (required)

Return: `GroupFigure`, `OpenAPI.Clients.ApiResponse`
"""
function create_group_figure(_api::GroupFigureApi, group_figure_create::GroupFigureCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_group_figure(_api, group_figure_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_group_figure(_api::GroupFigureApi, response_stream::Channel, group_figure_create::GroupFigureCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_group_figure(_api, group_figure_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_group_figure_GroupFigureApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_group_figure(_api::GroupFigureApi, year::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_group_figure_GroupFigureApi, "/api/v1/group-figures/{year}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "year", year)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_group_figure(_api::GroupFigureApi, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_group_figure(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_group_figure(_api::GroupFigureApi, response_stream::Channel, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_delete_group_figure(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_group_figure_GroupFigureApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => GroupFigure,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_group_figure(_api::GroupFigureApi, year::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_group_figure_GroupFigureApi, "/api/v1/group-figures/{year}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "year", year)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64` (required)

Return: `GroupFigure`, `OpenAPI.Clients.ApiResponse`
"""
function get_group_figure(_api::GroupFigureApi, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_group_figure(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_group_figure(_api::GroupFigureApi, response_stream::Channel, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_group_figure(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_group_figures_GroupFigureApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{GroupFigure},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_group_figures(_api::GroupFigureApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "get_group_figures", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "get_group_figures", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_group_figures_GroupFigureApi, "/api/v1/group-figures/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "include_deleted", include_deleted; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `include_deleted`::`Bool`

Return: `Vector{GroupFigure}`, `OpenAPI.Clients.ApiResponse`
"""
function get_group_figures(_api::GroupFigureApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_group_figures(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_group_figures(_api::GroupFigureApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_group_figures(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_group_figure_GroupFigureApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => GroupFigure,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_group_figure(_api::GroupFigureApi, year::Int64, group_figure_update::GroupFigureUpdate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_group_figure_GroupFigureApi, "/api/v1/group-figures/{year}", ["bearer_token", ], group_figure_update)
    OpenAPI.Clients.set_param(_ctx.path, "year", year)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64` (required)
- `group_figure_update`::`GroupFigureUpdate` (required)

Return: `GroupFigure`, `OpenAPI.Clients.ApiResponse`
"""
function update_group_figure(_api::GroupFigureApi, year::Int64, group_figure_update::GroupFigureUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_group_figure(_api, year, group_figure_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_group_figure(_api::GroupFigureApi, response_stream::Channel, year::Int64, group_figure_update::GroupFigureUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_group_figure(_api, year, group_figure_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_group_figure
export delete_group_figure
export get_group_figure
export get_group_figures
export update_group_figure
