# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct BomApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `BomApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ BomApi }) = "https://demo.simplebilly.com"

const _returntypes_create_bom_BomApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Bom,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_bom(_api::BomApi, bom_create::BomCreate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_bom_BomApi, "/api/v1/boms", ["bearer_token", ], bom_create)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `bom_create`::`BomCreate` (required)

Return: `Bom`, `OpenAPI.Clients.ApiResponse`
"""
function create_bom(_api::BomApi, bom_create::BomCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_bom(_api, bom_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_bom(_api::BomApi, response_stream::Channel, bom_create::BomCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_bom(_api, bom_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_bom_BomApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_bom(_api::BomApi, bom_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_bom_BomApi, "/api/v1/boms/{bom_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "bom_id", bom_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `bom_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_bom(_api::BomApi, bom_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_bom(_api, bom_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_bom(_api::BomApi, response_stream::Channel, bom_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_bom(_api, bom_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_bom_BomApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Bom,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_bom(_api::BomApi, bom_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_bom_BomApi, "/api/v1/boms/{bom_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "bom_id", bom_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `bom_id`::`String` (required)

Return: `Bom`, `OpenAPI.Clients.ApiResponse`
"""
function get_bom(_api::BomApi, bom_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_bom(_api, bom_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_bom(_api::BomApi, response_stream::Channel, bom_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_bom(_api, bom_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_boms_BomApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Bom},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_boms(_api::BomApi; page=nothing, page_size=nothing, search=nothing, product_id=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_boms", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_boms", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_boms_BomApi, "/api/v1/boms/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "pageSize", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "productId", product_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `product_id`::`String`

Return: `Vector{Bom}`, `OpenAPI.Clients.ApiResponse`
"""
function list_boms(_api::BomApi; page=nothing, page_size=nothing, search=nothing, product_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_boms(_api; page=page, page_size=page_size, search=search, product_id=product_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_boms(_api::BomApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, product_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_boms(_api; page=page, page_size=page_size, search=search, product_id=product_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_bom_BomApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Bom,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_bom(_api::BomApi, bom_id::String, bom_update::BomUpdate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_bom_BomApi, "/api/v1/boms/{bom_id}", ["bearer_token", ], bom_update)
    OpenAPI.Clients.set_param(_ctx.path, "bom_id", bom_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `bom_id`::`String` (required)
- `bom_update`::`BomUpdate` (required)

Return: `Bom`, `OpenAPI.Clients.ApiResponse`
"""
function update_bom(_api::BomApi, bom_id::String, bom_update::BomUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_bom(_api, bom_id, bom_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_bom(_api::BomApi, response_stream::Channel, bom_id::String, bom_update::BomUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_bom(_api, bom_id, bom_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_bom
export delete_bom
export get_bom
export list_boms
export update_bom
