# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct CreditNoteApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `CreditNoteApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ CreditNoteApi }) = "https://demo.simplebilly.com"

const _returntypes_create_credit_note_CreditNoteApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Invoice,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_credit_note(_api::CreditNoteApi, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_credit_note_CreditNoteApi, "/api/v1/credit-notes", ["bearer_token", ], body)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `body`::`Any` (required)

Return: `Invoice`, `OpenAPI.Clients.ApiResponse`
"""
function create_credit_note(_api::CreditNoteApi, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_create_credit_note(_api, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_credit_note(_api::CreditNoteApi, response_stream::Channel, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_create_credit_note(_api, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_download_credit_note_pdf_CreditNoteApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_download_credit_note_pdf(_api::CreditNoteApi, credit_note_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_download_credit_note_pdf_CreditNoteApi, "/api/v1/credit-notes/{credit_note_id}/pdf", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "credit_note_id", credit_note_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/pdf", "application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `credit_note_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function download_credit_note_pdf(_api::CreditNoteApi, credit_note_id::String; _mediaType=nothing)
    _ctx = _oacinternal_download_credit_note_pdf(_api, credit_note_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function download_credit_note_pdf(_api::CreditNoteApi, response_stream::Channel, credit_note_id::String; _mediaType=nothing)
    _ctx = _oacinternal_download_credit_note_pdf(_api, credit_note_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_credit_note_CreditNoteApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Invoice,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_credit_note(_api::CreditNoteApi, credit_note_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_credit_note_CreditNoteApi, "/api/v1/credit-notes/{credit_note_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "credit_note_id", credit_note_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `credit_note_id`::`String` (required)

Return: `Invoice`, `OpenAPI.Clients.ApiResponse`
"""
function get_credit_note(_api::CreditNoteApi, credit_note_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_credit_note(_api, credit_note_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_credit_note(_api::CreditNoteApi, response_stream::Channel, credit_note_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_credit_note(_api, credit_note_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_credit_notes_CreditNoteApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Invoice},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_credit_notes(_api::CreditNoteApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_credit_notes", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_credit_notes", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_credit_notes_CreditNoteApi, "/api/v1/credit-notes/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "include_deleted", include_deleted; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `include_deleted`::`Bool`

Return: `Vector{Invoice}`, `OpenAPI.Clients.ApiResponse`
"""
function list_credit_notes(_api::CreditNoteApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_credit_notes(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_credit_notes(_api::CreditNoteApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_credit_notes(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_credit_note
export download_credit_note_pdf
export get_credit_note
export list_credit_notes
