# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ImportRunnerApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ImportRunnerApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ImportRunnerApi }) = "https://demo.simplebilly.com"

const _returntypes_get_import_status_ImportRunnerApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ImportJobStatus,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_import_status(_api::ImportRunnerApi, job_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_import_status_ImportRunnerApi, "/api/v1/import/{job_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "job_id", job_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `job_id`::`String` (required)

Return: `ImportJobStatus`, `OpenAPI.Clients.ApiResponse`
"""
function get_import_status(_api::ImportRunnerApi, job_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_import_status(_api, job_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_import_status(_api::ImportRunnerApi, response_stream::Channel, job_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_import_status(_api, job_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_start_import_ImportRunnerApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ImportStartResponse,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_start_import(_api::ImportRunnerApi, import_start_request::ImportStartRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_start_import_ImportRunnerApi, "/api/v1/import/start", ["bearer_token", ], import_start_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `import_start_request`::`ImportStartRequest` (required)

Return: `ImportStartResponse`, `OpenAPI.Clients.ApiResponse`
"""
function start_import(_api::ImportRunnerApi, import_start_request::ImportStartRequest; _mediaType=nothing)
    _ctx = _oacinternal_start_import(_api, import_start_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function start_import(_api::ImportRunnerApi, response_stream::Channel, import_start_request::ImportStartRequest; _mediaType=nothing)
    _ctx = _oacinternal_start_import(_api, import_start_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_test_import_connection_ImportRunnerApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ImportTestResponse,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_test_import_connection(_api::ImportRunnerApi, import_test_request::ImportTestRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_test_import_connection_ImportRunnerApi, "/api/v1/import/test", ["bearer_token", ], import_test_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `import_test_request`::`ImportTestRequest` (required)

Return: `ImportTestResponse`, `OpenAPI.Clients.ApiResponse`
"""
function test_import_connection(_api::ImportRunnerApi, import_test_request::ImportTestRequest; _mediaType=nothing)
    _ctx = _oacinternal_test_import_connection(_api, import_test_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function test_import_connection(_api::ImportRunnerApi, response_stream::Channel, import_test_request::ImportTestRequest; _mediaType=nothing)
    _ctx = _oacinternal_test_import_connection(_api, import_test_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export get_import_status
export start_import
export test_import_connection
