# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct PaymentApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `PaymentApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ PaymentApi }) = "https://demo.simplebilly.com"

const _returntypes_create_payment_PaymentApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Payment,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_payment(_api::PaymentApi, payment_create::PaymentCreate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_payment_PaymentApi, "/api/v1/payments", ["bearer_token", ], payment_create)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `payment_create`::`PaymentCreate` (required)

Return: `Payment`, `OpenAPI.Clients.ApiResponse`
"""
function create_payment(_api::PaymentApi, payment_create::PaymentCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_payment(_api, payment_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_payment(_api::PaymentApi, response_stream::Channel, payment_create::PaymentCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_payment(_api, payment_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_payment_PaymentApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_payment(_api::PaymentApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_payment_PaymentApi, "/api/v1/payments/{id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_payment(_api::PaymentApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_payment(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_payment(_api::PaymentApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_payment(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_payment_PaymentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Payment,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_payment(_api::PaymentApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_payment_PaymentApi, "/api/v1/payments/{id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Payment`, `OpenAPI.Clients.ApiResponse`
"""
function get_payment(_api::PaymentApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_payment(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_payment(_api::PaymentApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_payment(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_payments_PaymentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Payment},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_payments(_api::PaymentApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "get_payments", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "get_payments", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_payments_PaymentApi, "/api/v1/payments/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "include_deleted", include_deleted; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `include_deleted`::`Bool`

Return: `Vector{Payment}`, `OpenAPI.Clients.ApiResponse`
"""
function get_payments(_api::PaymentApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_payments(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_payments(_api::PaymentApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_payments(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_payment_restore_PaymentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Payment,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_payment_restore(_api::PaymentApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_payment_restore_PaymentApi, "/api/v1/payments/{id}/restore", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Payment`, `OpenAPI.Clients.ApiResponse`
"""
function payment_restore(_api::PaymentApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payment_restore(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function payment_restore(_api::PaymentApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_payment_restore(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_payment_PaymentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Payment,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_payment(_api::PaymentApi, id::String, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_payment_PaymentApi, "/api/v1/payments/{id}", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)
- `body`::`Any` (required)

Return: `Payment`, `OpenAPI.Clients.ApiResponse`
"""
function update_payment(_api::PaymentApi, id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_payment(_api, id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_payment(_api::PaymentApi, response_stream::Channel, id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_payment(_api, id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_payment
export delete_payment
export get_payment
export get_payments
export payment_restore
export update_payment
