# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct WarehouseApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `WarehouseApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ WarehouseApi }) = "https://demo.simplebilly.com"

const _returntypes_create_warehouse_WarehouseApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Warehouse,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_warehouse(_api::WarehouseApi, warehouse::Warehouse; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_warehouse_WarehouseApi, "/api/v1/warehouses", ["bearer_token", ], warehouse)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `warehouse`::`Warehouse` (required)

Return: `Warehouse`, `OpenAPI.Clients.ApiResponse`
"""
function create_warehouse(_api::WarehouseApi, warehouse::Warehouse; _mediaType=nothing)
    _ctx = _oacinternal_create_warehouse(_api, warehouse; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_warehouse(_api::WarehouseApi, response_stream::Channel, warehouse::Warehouse; _mediaType=nothing)
    _ctx = _oacinternal_create_warehouse(_api, warehouse; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_warehouse_WarehouseApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_warehouse(_api::WarehouseApi, warehouse_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_warehouse_WarehouseApi, "/api/v1/warehouses/{warehouse_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "warehouse_id", warehouse_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `warehouse_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_warehouse(_api::WarehouseApi, warehouse_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_warehouse(_api, warehouse_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_warehouse(_api::WarehouseApi, response_stream::Channel, warehouse_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_warehouse(_api, warehouse_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_warehouse_WarehouseApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Warehouse,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_warehouse(_api::WarehouseApi, warehouse_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_warehouse_WarehouseApi, "/api/v1/warehouses/{warehouse_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "warehouse_id", warehouse_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `warehouse_id`::`String` (required)

Return: `Warehouse`, `OpenAPI.Clients.ApiResponse`
"""
function get_warehouse(_api::WarehouseApi, warehouse_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_warehouse(_api, warehouse_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_warehouse(_api::WarehouseApi, response_stream::Channel, warehouse_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_warehouse(_api, warehouse_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_warehouses_WarehouseApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Warehouse},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_warehouses(_api::WarehouseApi; page=nothing, page_size=nothing, search=nothing, is_active=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_warehouses", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_warehouses", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_warehouses_WarehouseApi, "/api/v1/warehouses/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "is_active", is_active; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `is_active`::`Bool`

Return: `Vector{Warehouse}`, `OpenAPI.Clients.ApiResponse`
"""
function list_warehouses(_api::WarehouseApi; page=nothing, page_size=nothing, search=nothing, is_active=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_warehouses(_api; page=page, page_size=page_size, search=search, is_active=is_active, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_warehouses(_api::WarehouseApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, is_active=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_warehouses(_api; page=page, page_size=page_size, search=search, is_active=is_active, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_warehouse_WarehouseApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Warehouse,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_warehouse(_api::WarehouseApi, warehouse_id::String, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_warehouse_WarehouseApi, "/api/v1/warehouses/{warehouse_id}", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "warehouse_id", warehouse_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `warehouse_id`::`String` (required)
- `body`::`Any` (required)

Return: `Warehouse`, `OpenAPI.Clients.ApiResponse`
"""
function update_warehouse(_api::WarehouseApi, warehouse_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_warehouse(_api, warehouse_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_warehouse(_api::WarehouseApi, response_stream::Channel, warehouse_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_warehouse(_api, warehouse_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_warehouse
export delete_warehouse
export get_warehouse
export list_warehouses
export update_warehouse
