# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct TrainingAssignmentApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `TrainingAssignmentApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ TrainingAssignmentApi }) = "https://demo.simplebilly.com"

const _returntypes_create_training_assignment_TrainingAssignmentApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => TrainingAssignment,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_training_assignment(_api::TrainingAssignmentApi, training_assignment_create::TrainingAssignmentCreate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_training_assignment_TrainingAssignmentApi, "/api/v1/training-assignments", ["bearer_token", ], training_assignment_create)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `training_assignment_create`::`TrainingAssignmentCreate` (required)

Return: `TrainingAssignment`, `OpenAPI.Clients.ApiResponse`
"""
function create_training_assignment(_api::TrainingAssignmentApi, training_assignment_create::TrainingAssignmentCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_training_assignment(_api, training_assignment_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_training_assignment(_api::TrainingAssignmentApi, response_stream::Channel, training_assignment_create::TrainingAssignmentCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_training_assignment(_api, training_assignment_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_training_assignment_TrainingAssignmentApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_training_assignment(_api::TrainingAssignmentApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_training_assignment_TrainingAssignmentApi, "/api/v1/training-assignments/{id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_training_assignment(_api::TrainingAssignmentApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_training_assignment(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_training_assignment(_api::TrainingAssignmentApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_training_assignment(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_training_assignment_TrainingAssignmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => TrainingAssignment,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_training_assignment(_api::TrainingAssignmentApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_training_assignment_TrainingAssignmentApi, "/api/v1/training-assignments/{id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `TrainingAssignment`, `OpenAPI.Clients.ApiResponse`
"""
function get_training_assignment(_api::TrainingAssignmentApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_training_assignment(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_training_assignment(_api::TrainingAssignmentApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_training_assignment(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_training_assignments_TrainingAssignmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{TrainingAssignment},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_training_assignments(_api::TrainingAssignmentApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "get_training_assignments", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "get_training_assignments", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_training_assignments_TrainingAssignmentApi, "/api/v1/training-assignments/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "include_deleted", include_deleted; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `include_deleted`::`Bool`

Return: `Vector{TrainingAssignment}`, `OpenAPI.Clients.ApiResponse`
"""
function get_training_assignments(_api::TrainingAssignmentApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_training_assignments(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_training_assignments(_api::TrainingAssignmentApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_training_assignments(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_training_assignment_TrainingAssignmentApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => TrainingAssignment,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_training_assignment(_api::TrainingAssignmentApi, id::String, training_assignment_update::TrainingAssignmentUpdate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_training_assignment_TrainingAssignmentApi, "/api/v1/training-assignments/{id}", ["bearer_token", ], training_assignment_update)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)
- `training_assignment_update`::`TrainingAssignmentUpdate` (required)

Return: `TrainingAssignment`, `OpenAPI.Clients.ApiResponse`
"""
function update_training_assignment(_api::TrainingAssignmentApi, id::String, training_assignment_update::TrainingAssignmentUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_training_assignment(_api, id, training_assignment_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_training_assignment(_api::TrainingAssignmentApi, response_stream::Channel, id::String, training_assignment_update::TrainingAssignmentUpdate; _mediaType=nothing)
    _ctx = _oacinternal_update_training_assignment(_api, id, training_assignment_update; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_training_assignment
export delete_training_assignment
export get_training_assignment
export get_training_assignments
export update_training_assignment
