# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ContactApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ContactApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ContactApi }) = "https://demo.simplebilly.com"

const _returntypes_contact_schema_ContactApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Any,
)

function _oacinternal_contact_schema(_api::ContactApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_contact_schema_ContactApi, "/api/v1/contacts/schema", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Serve JSON Schema for client-side validation

Params:

Return: `Any`, `OpenAPI.Clients.ApiResponse`
"""
function contact_schema(_api::ContactApi; _mediaType=nothing)
    _ctx = _oacinternal_contact_schema(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function contact_schema(_api::ContactApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_contact_schema(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_contact_timeline_ContactApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => ContactTimelineResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_contact_timeline(_api::ContactApi, contact_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_contact_timeline_ContactApi, "/api/v1/contacts/{contact_id}/timeline", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "contact_id", contact_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get the full per-contact timeline (Xentral §4.6/4.7).

Aggregates communications, quotations, orders, invoices and uploaded documents for a contact, merged into a single reverse-chronological feed.

Params:
- `contact_id`::`String` (required)

Return: `ContactTimelineResponse`, `OpenAPI.Clients.ApiResponse`
"""
function contact_timeline(_api::ContactApi, contact_id::String; _mediaType=nothing)
    _ctx = _oacinternal_contact_timeline(_api, contact_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function contact_timeline(_api::ContactApi, response_stream::Channel, contact_id::String; _mediaType=nothing)
    _ctx = _oacinternal_contact_timeline(_api, contact_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_create_contact_ContactApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Contact,
)

function _oacinternal_create_contact(_api::ContactApi, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_contact_ContactApi, "/api/v1/contacts", ["bearer_token", ], body)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Create contact

Params:
- `body`::`Any` (required)

Return: `Contact`, `OpenAPI.Clients.ApiResponse`
"""
function create_contact(_api::ContactApi, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_create_contact(_api, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_contact(_api::ContactApi, response_stream::Channel, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_create_contact(_api, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_contact_ContactApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_delete_contact(_api::ContactApi, contact_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_contact_ContactApi, "/api/v1/contacts/{contact_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "contact_id", contact_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, [])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Soft-delete contact

Params:
- `contact_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_contact(_api::ContactApi, contact_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_contact(_api, contact_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_contact(_api::ContactApi, response_stream::Channel, contact_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_contact(_api, contact_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_contact_ContactApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Contact,
    Regex("^" * replace("404", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_get_contact(_api::ContactApi, contact_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_contact_ContactApi, "/api/v1/contacts/{contact_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "contact_id", contact_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get single contact

Params:
- `contact_id`::`String` (required)

Return: `Contact`, `OpenAPI.Clients.ApiResponse`
"""
function get_contact(_api::ContactApi, contact_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_contact(_api, contact_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_contact(_api::ContactApi, response_stream::Channel, contact_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_contact(_api, contact_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_contacts_ContactApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Contact},
)

function _oacinternal_list_contacts(_api::ContactApi; page=nothing, page_size=nothing, search=nothing, contact_type=nothing, tag=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_contacts", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_contacts", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_contacts_ContactApi, "/api/v1/contacts", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contact_type", contact_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "tag", tag; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List contacts with search, type filter, and pagination

Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `contact_type`::`String`
- `tag`::`String`

Return: `Vector{Contact}`, `OpenAPI.Clients.ApiResponse`
"""
function list_contacts(_api::ContactApi; page=nothing, page_size=nothing, search=nothing, contact_type=nothing, tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_contacts(_api; page=page, page_size=page_size, search=search, contact_type=contact_type, tag=tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_contacts(_api::ContactApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, contact_type=nothing, tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_contacts(_api; page=page, page_size=page_size, search=search, contact_type=contact_type, tag=tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_sales_volume_ContactApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SalesVolumeReport,
)

function _oacinternal_sales_volume(_api::ContactApi; page=nothing, page_size=nothing, search=nothing, contact_type=nothing, tag=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "sales_volume", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "sales_volume", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_sales_volume_ContactApi, "/api/v1/contacts/sales-volume", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contact_type", contact_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "tag", tag; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Sales volume per contact

Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `contact_type`::`String`
- `tag`::`String`

Return: `SalesVolumeReport`, `OpenAPI.Clients.ApiResponse`
"""
function sales_volume(_api::ContactApi; page=nothing, page_size=nothing, search=nothing, contact_type=nothing, tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_sales_volume(_api; page=page, page_size=page_size, search=search, contact_type=contact_type, tag=tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function sales_volume(_api::ContactApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, contact_type=nothing, tag=nothing, _mediaType=nothing)
    _ctx = _oacinternal_sales_volume(_api; page=page, page_size=page_size, search=search, contact_type=contact_type, tag=tag, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_contact_ContactApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Contact,
)

function _oacinternal_update_contact(_api::ContactApi, contact_id::String, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_contact_ContactApi, "/api/v1/contacts/{contact_id}", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "contact_id", contact_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Update contact

Params:
- `contact_id`::`String` (required)
- `body`::`Any` (required)

Return: `Contact`, `OpenAPI.Clients.ApiResponse`
"""
function update_contact(_api::ContactApi, contact_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_contact(_api, contact_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_contact(_api::ContactApi, response_stream::Channel, contact_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_contact(_api, contact_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export contact_schema
export contact_timeline
export create_contact
export delete_contact
export get_contact
export list_contacts
export sales_volume
export update_contact
