# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct InvoiceApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `InvoiceApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ InvoiceApi }) = "https://demo.simplebilly.com"

const _returntypes_create_invoice_InvoiceApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Invoice,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_invoice(_api::InvoiceApi, invoice_create::InvoiceCreate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_invoice_InvoiceApi, "/api/v1/invoices", ["bearer_token", ], invoice_create)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `invoice_create`::`InvoiceCreate` (required)

Return: `Invoice`, `OpenAPI.Clients.ApiResponse`
"""
function create_invoice(_api::InvoiceApi, invoice_create::InvoiceCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_invoice(_api, invoice_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_invoice(_api::InvoiceApi, response_stream::Channel, invoice_create::InvoiceCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_invoice(_api, invoice_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_invoice_InvoiceApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_invoice(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_invoice_InvoiceApi, "/api/v1/invoices/{id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_invoice(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_invoice(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_invoice(_api::InvoiceApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_invoice(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_download_invoice_pdf_InvoiceApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_download_invoice_pdf(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_download_invoice_pdf_InvoiceApi, "/api/v1/invoices/{id}/pdf", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/pdf", "application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function download_invoice_pdf(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_download_invoice_pdf(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function download_invoice_pdf(_api::InvoiceApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_download_invoice_pdf(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_invoice_InvoiceApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Invoice,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_invoice(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_invoice_InvoiceApi, "/api/v1/invoices/{id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Invoice`, `OpenAPI.Clients.ApiResponse`
"""
function get_invoice(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_invoice(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_invoice(_api::InvoiceApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_invoice(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_invoice_pdf_url_InvoiceApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => InvoicePdfUrlResponse,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_invoice_pdf_url(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_invoice_pdf_url_InvoiceApi, "/api/v1/invoices/{id}/pdf-url", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `InvoicePdfUrlResponse`, `OpenAPI.Clients.ApiResponse`
"""
function get_invoice_pdf_url(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_invoice_pdf_url(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_invoice_pdf_url(_api::InvoiceApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_invoice_pdf_url(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_invoices_InvoiceApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Invoice},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_invoices(_api::InvoiceApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "get_invoices", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "get_invoices", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_invoices_InvoiceApi, "/api/v1/invoices/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "search", search; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "include_deleted", include_deleted; style="form", is_explode=true)  # type Bool
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `search`::`String`
- `include_deleted`::`Bool`

Return: `Vector{Invoice}`, `OpenAPI.Clients.ApiResponse`
"""
function get_invoices(_api::InvoiceApi; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_invoices(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_invoices(_api::InvoiceApi, response_stream::Channel; page=nothing, page_size=nothing, search=nothing, include_deleted=nothing, _mediaType=nothing)
    _ctx = _oacinternal_get_invoices(_api; page=page, page_size=page_size, search=search, include_deleted=include_deleted, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_invoice_restore_InvoiceApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Invoice,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_invoice_restore(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_invoice_restore_InvoiceApi, "/api/v1/invoices/{id}/restore", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)

Return: `Invoice`, `OpenAPI.Clients.ApiResponse`
"""
function invoice_restore(_api::InvoiceApi, id::String; _mediaType=nothing)
    _ctx = _oacinternal_invoice_restore(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function invoice_restore(_api::InvoiceApi, response_stream::Channel, id::String; _mediaType=nothing)
    _ctx = _oacinternal_invoice_restore(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_invoice_InvoiceApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Invoice,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_invoice(_api::InvoiceApi, id::String, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_invoice_InvoiceApi, "/api/v1/invoices/{id}", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "id", id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `id`::`String` (required)
- `body`::`Any` (required)

Return: `Invoice`, `OpenAPI.Clients.ApiResponse`
"""
function update_invoice(_api::InvoiceApi, id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_invoice(_api, id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_invoice(_api::InvoiceApi, response_stream::Channel, id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_invoice(_api, id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_invoice
export delete_invoice
export download_invoice_pdf
export get_invoice
export get_invoice_pdf_url
export get_invoices
export invoice_restore
export update_invoice
