# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct EbilanzApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `EbilanzApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ EbilanzApi }) = "https://demo.simplebilly.com"

const _returntypes_ebilanz_report_api_EbilanzApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => EBilanzReport,
)

function _oacinternal_ebilanz_report_api(_api::EbilanzApi; year=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_ebilanz_report_api_EbilanzApi, "/api/v1/bookkeeping/ebilanz", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "year", year; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "date_from", date_from; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "date_to", date_to; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64`
- `date_from`::`String`
- `date_to`::`String`

Return: `EBilanzReport`, `OpenAPI.Clients.ApiResponse`
"""
function ebilanz_report_api(_api::EbilanzApi; year=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    _ctx = _oacinternal_ebilanz_report_api(_api; year=year, date_from=date_from, date_to=date_to, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function ebilanz_report_api(_api::EbilanzApi, response_stream::Channel; year=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    _ctx = _oacinternal_ebilanz_report_api(_api; year=year, date_from=date_from, date_to=date_to, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_ebilanz_xbrl_export_api_EbilanzApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_ebilanz_xbrl_export_api(_api::EbilanzApi; year=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_ebilanz_xbrl_export_api_EbilanzApi, "/api/v1/bookkeeping/ebilanz/xbrl", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "year", year; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "date_from", date_from; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "date_to", date_to; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/xml", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64`
- `date_from`::`String`
- `date_to`::`String`

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function ebilanz_xbrl_export_api(_api::EbilanzApi; year=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    _ctx = _oacinternal_ebilanz_xbrl_export_api(_api; year=year, date_from=date_from, date_to=date_to, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function ebilanz_xbrl_export_api(_api::EbilanzApi, response_stream::Channel; year=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    _ctx = _oacinternal_ebilanz_xbrl_export_api(_api; year=year, date_from=date_from, date_to=date_to, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export ebilanz_report_api
export ebilanz_xbrl_export_api
