# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct GoodsReceiptApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `GoodsReceiptApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ GoodsReceiptApi }) = "https://demo.simplebilly.com"

const _returntypes_create_goods_receipt_GoodsReceiptApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => GoodsReceipt,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_goods_receipt(_api::GoodsReceiptApi, goods_receipt::GoodsReceipt; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_goods_receipt_GoodsReceiptApi, "/api/v1/goods-receipts", ["bearer_token", ], goods_receipt)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `goods_receipt`::`GoodsReceipt` (required)

Return: `GoodsReceipt`, `OpenAPI.Clients.ApiResponse`
"""
function create_goods_receipt(_api::GoodsReceiptApi, goods_receipt::GoodsReceipt; _mediaType=nothing)
    _ctx = _oacinternal_create_goods_receipt(_api, goods_receipt; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_goods_receipt(_api::GoodsReceiptApi, response_stream::Channel, goods_receipt::GoodsReceipt; _mediaType=nothing)
    _ctx = _oacinternal_create_goods_receipt(_api, goods_receipt; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_goods_receipt_GoodsReceiptApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_goods_receipt(_api::GoodsReceiptApi, goods_receipt_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_goods_receipt_GoodsReceiptApi, "/api/v1/goods-receipts/{goods_receipt_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "goods_receipt_id", goods_receipt_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `goods_receipt_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_goods_receipt(_api::GoodsReceiptApi, goods_receipt_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_goods_receipt(_api, goods_receipt_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_goods_receipt(_api::GoodsReceiptApi, response_stream::Channel, goods_receipt_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_goods_receipt(_api, goods_receipt_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_goods_receipt_GoodsReceiptApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => GoodsReceipt,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_goods_receipt(_api::GoodsReceiptApi, goods_receipt_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_goods_receipt_GoodsReceiptApi, "/api/v1/goods-receipts/{goods_receipt_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "goods_receipt_id", goods_receipt_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `goods_receipt_id`::`String` (required)

Return: `GoodsReceipt`, `OpenAPI.Clients.ApiResponse`
"""
function get_goods_receipt(_api::GoodsReceiptApi, goods_receipt_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_goods_receipt(_api, goods_receipt_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_goods_receipt(_api::GoodsReceiptApi, response_stream::Channel, goods_receipt_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_goods_receipt(_api, goods_receipt_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_goods_receipts_GoodsReceiptApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{GoodsReceipt},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_goods_receipts(_api::GoodsReceiptApi; page=nothing, page_size=nothing, purchase_order_id=nothing, supplier_name=nothing, warehouse_id=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_goods_receipts", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_goods_receipts", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_goods_receipts_GoodsReceiptApi, "/api/v1/goods-receipts/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "purchase_order_id", purchase_order_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "supplier_name", supplier_name; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "warehouse_id", warehouse_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `purchase_order_id`::`String`
- `supplier_name`::`String`
- `warehouse_id`::`String`

Return: `Vector{GoodsReceipt}`, `OpenAPI.Clients.ApiResponse`
"""
function list_goods_receipts(_api::GoodsReceiptApi; page=nothing, page_size=nothing, purchase_order_id=nothing, supplier_name=nothing, warehouse_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_goods_receipts(_api; page=page, page_size=page_size, purchase_order_id=purchase_order_id, supplier_name=supplier_name, warehouse_id=warehouse_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_goods_receipts(_api::GoodsReceiptApi, response_stream::Channel; page=nothing, page_size=nothing, purchase_order_id=nothing, supplier_name=nothing, warehouse_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_goods_receipts(_api; page=page, page_size=page_size, purchase_order_id=purchase_order_id, supplier_name=supplier_name, warehouse_id=warehouse_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_goods_receipt
export delete_goods_receipt
export get_goods_receipt
export list_goods_receipts
