# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct AdminApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `AdminApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ AdminApi }) = "https://demo.simplebilly.com"

const _returntypes_trigger_mirror_AdminApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => MirrorTriggerResponse,
    Regex("^" * replace("403", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_trigger_mirror(_api::AdminApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_trigger_mirror_AdminApi, "/api/v1/admin/storage/mirror", ["bearer_token", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:

Return: `MirrorTriggerResponse`, `OpenAPI.Clients.ApiResponse`
"""
function trigger_mirror(_api::AdminApi; _mediaType=nothing)
    _ctx = _oacinternal_trigger_mirror(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function trigger_mirror(_api::AdminApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_trigger_mirror(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export trigger_mirror
