# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct VoucherApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `VoucherApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ VoucherApi }) = "https://demo.simplebilly.com"

const _returntypes_create_voucher_VoucherApi = Dict{Regex,Type}(
    Regex("^" * replace("201", "x"=>".") * "\$") => Voucher,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_create_voucher(_api::VoucherApi, voucher_create::VoucherCreate; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_create_voucher_VoucherApi, "/api/v1/vouchers", ["bearer_token", ], voucher_create)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `voucher_create`::`VoucherCreate` (required)

Return: `Voucher`, `OpenAPI.Clients.ApiResponse`
"""
function create_voucher(_api::VoucherApi, voucher_create::VoucherCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_voucher(_api, voucher_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function create_voucher(_api::VoucherApi, response_stream::Channel, voucher_create::VoucherCreate; _mediaType=nothing)
    _ctx = _oacinternal_create_voucher(_api, voucher_create; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_delete_voucher_VoucherApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_delete_voucher(_api::VoucherApi, voucher_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "DELETE", _returntypes_delete_voucher_VoucherApi, "/api/v1/vouchers/{voucher_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "voucher_id", voucher_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `voucher_id`::`String` (required)

Return: `Nothing`, `OpenAPI.Clients.ApiResponse`
"""
function delete_voucher(_api::VoucherApi, voucher_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_voucher(_api, voucher_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function delete_voucher(_api::VoucherApi, response_stream::Channel, voucher_id::String; _mediaType=nothing)
    _ctx = _oacinternal_delete_voucher(_api, voucher_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_get_voucher_VoucherApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Voucher,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_get_voucher(_api::VoucherApi, voucher_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_voucher_VoucherApi, "/api/v1/vouchers/{voucher_id}", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "voucher_id", voucher_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `voucher_id`::`String` (required)

Return: `Voucher`, `OpenAPI.Clients.ApiResponse`
"""
function get_voucher(_api::VoucherApi, voucher_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_voucher(_api, voucher_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_voucher(_api::VoucherApi, response_stream::Channel, voucher_id::String; _mediaType=nothing)
    _ctx = _oacinternal_get_voucher(_api, voucher_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_vouchers_VoucherApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{Voucher},
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_list_vouchers(_api::VoucherApi; page=nothing, page_size=nothing, voucher_type=nothing, voucher_status=nothing, contact_name=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    OpenAPI.validate_param("page", "list_vouchers", :minimum, page, 0, false)

    OpenAPI.validate_param("page_size", "list_vouchers", :minimum, page_size, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_vouchers_VoucherApi, "/api/v1/vouchers/", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "page", page; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "page_size", page_size; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "voucher_type", voucher_type; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "voucher_status", voucher_status; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "contact_name", contact_name; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "date_from", date_from; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "date_to", date_to; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `page`::`Int64`
- `page_size`::`Int64`
- `voucher_type`::`String`
- `voucher_status`::`String`
- `contact_name`::`String`
- `date_from`::`Date`
- `date_to`::`Date`

Return: `Vector{Voucher}`, `OpenAPI.Clients.ApiResponse`
"""
function list_vouchers(_api::VoucherApi; page=nothing, page_size=nothing, voucher_type=nothing, voucher_status=nothing, contact_name=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_vouchers(_api; page=page, page_size=page_size, voucher_type=voucher_type, voucher_status=voucher_status, contact_name=contact_name, date_from=date_from, date_to=date_to, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_vouchers(_api::VoucherApi, response_stream::Channel; page=nothing, page_size=nothing, voucher_type=nothing, voucher_status=nothing, contact_name=nothing, date_from=nothing, date_to=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_vouchers(_api; page=page, page_size=page_size, voucher_type=voucher_type, voucher_status=voucher_status, contact_name=contact_name, date_from=date_from, date_to=date_to, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_update_voucher_VoucherApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Voucher,
    Regex("^" * replace("400", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_update_voucher(_api::VoucherApi, voucher_id::String, body::Any; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "PUT", _returntypes_update_voucher_VoucherApi, "/api/v1/vouchers/{voucher_id}", ["bearer_token", ], body)
    OpenAPI.Clients.set_param(_ctx.path, "voucher_id", voucher_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `voucher_id`::`String` (required)
- `body`::`Any` (required)

Return: `Voucher`, `OpenAPI.Clients.ApiResponse`
"""
function update_voucher(_api::VoucherApi, voucher_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_voucher(_api, voucher_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function update_voucher(_api::VoucherApi, response_stream::Channel, voucher_id::String, body::Any; _mediaType=nothing)
    _ctx = _oacinternal_update_voucher(_api, voucher_id, body; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_voucher_restore_VoucherApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Voucher,
    Regex("^" * replace("404", "x"=>".") * "\$") => PluginError,
    Regex("^" * replace("500", "x"=>".") * "\$") => PluginError,
)

function _oacinternal_voucher_restore(_api::VoucherApi, voucher_id::String; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_voucher_restore_VoucherApi, "/api/v1/vouchers/{voucher_id}/restore", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.path, "voucher_id", voucher_id)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `voucher_id`::`String` (required)

Return: `Voucher`, `OpenAPI.Clients.ApiResponse`
"""
function voucher_restore(_api::VoucherApi, voucher_id::String; _mediaType=nothing)
    _ctx = _oacinternal_voucher_restore(_api, voucher_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function voucher_restore(_api::VoucherApi, response_stream::Channel, voucher_id::String; _mediaType=nothing)
    _ctx = _oacinternal_voucher_restore(_api, voucher_id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export create_voucher
export delete_voucher
export get_voucher
export list_vouchers
export update_voucher
export voucher_restore
