# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct StilleApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `StilleApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ StilleApi }) = "https://demo.simplebilly.com"

const _returntypes_stille_export_api_StilleApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => StilleExportResponse,
)

function _oacinternal_stille_export_api(_api::StilleApi, year::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stille_export_api_StilleApi, "/api/v1/bookkeeping/stille/export", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "year", year; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64` (required)

Return: `StilleExportResponse`, `OpenAPI.Clients.ApiResponse`
"""
function stille_export_api(_api::StilleApi, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_stille_export_api(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stille_export_api(_api::StilleApi, response_stream::Channel, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_stille_export_api(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stille_report_api_StilleApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => StilleReport,
)

function _oacinternal_stille_report_api(_api::StilleApi, year::Int64; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stille_report_api_StilleApi, "/api/v1/bookkeeping/stille/report", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "year", year; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64` (required)

Return: `StilleReport`, `OpenAPI.Clients.ApiResponse`
"""
function stille_report_api(_api::StilleApi, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_stille_report_api(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stille_report_api(_api::StilleApi, response_stream::Channel, year::Int64; _mediaType=nothing)
    _ctx = _oacinternal_stille_report_api(_api, year; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export stille_export_api
export stille_report_api
