# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct KostenVorschauApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `KostenVorschauApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ KostenVorschauApi }) = "https://demo.simplebilly.com"

const _returntypes_kosten_vorschau_api_KostenVorschauApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => KostenVorschau,
)

function _oacinternal_kosten_vorschau_api(_api::KostenVorschauApi, year::Int64, month::Int64; _mediaType=nothing)
    OpenAPI.validate_param("month", "kosten_vorschau_api", :minimum, month, 0, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_kosten_vorschau_api_KostenVorschauApi, "/api/v1/bookkeeping/kosten-vorschau", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "year", year; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "month", month; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `year`::`Int64` (required)
- `month`::`Int64` (required)

Return: `KostenVorschau`, `OpenAPI.Clients.ApiResponse`
"""
function kosten_vorschau_api(_api::KostenVorschauApi, year::Int64, month::Int64; _mediaType=nothing)
    _ctx = _oacinternal_kosten_vorschau_api(_api, year, month; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function kosten_vorschau_api(_api::KostenVorschauApi, response_stream::Channel, year::Int64, month::Int64; _mediaType=nothing)
    _ctx = _oacinternal_kosten_vorschau_api(_api, year, month; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export kosten_vorschau_api
