# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ListOpenItemsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ListOpenItemsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ListOpenItemsApi }) = "https://demo.simplebilly.com"

const _returntypes_list_open_items_api_ListOpenItemsApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{OpenItem},
    Regex("^" * replace("500", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_list_open_items_api(_api::ListOpenItemsApi; reminder_level1_days=nothing, reminder_level2_days=nothing, reminder_level3_days=nothing, customer_id=nothing, _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_open_items_api_ListOpenItemsApi, "/api/v1/bookkeeping/open-items", ["bearer_token", ])
    OpenAPI.Clients.set_param(_ctx.query, "reminder_level1_days", reminder_level1_days; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "reminder_level2_days", reminder_level2_days; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "reminder_level3_days", reminder_level3_days; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "customer_id", customer_id; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Params:
- `reminder_level1_days`::`Int64`
- `reminder_level2_days`::`Int64`
- `reminder_level3_days`::`Int64`
- `customer_id`::`String`

Return: `Vector{OpenItem}`, `OpenAPI.Clients.ApiResponse`
"""
function list_open_items_api(_api::ListOpenItemsApi; reminder_level1_days=nothing, reminder_level2_days=nothing, reminder_level3_days=nothing, customer_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_open_items_api(_api; reminder_level1_days=reminder_level1_days, reminder_level2_days=reminder_level2_days, reminder_level3_days=reminder_level3_days, customer_id=customer_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_open_items_api(_api::ListOpenItemsApi, response_stream::Channel; reminder_level1_days=nothing, reminder_level2_days=nothing, reminder_level3_days=nothing, customer_id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_list_open_items_api(_api; reminder_level1_days=reminder_level1_days, reminder_level2_days=reminder_level2_days, reminder_level3_days=reminder_level3_days, customer_id=customer_id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export list_open_items_api
