# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BankLookup

    BankLookup(;
        bank_name=nothing,
        bic=nothing,
        iban=nothing,
        nextgenpsd2_url=nothing,
        psd2_supported=nothing,
    )

    - bank_name::String
    - bic::String
    - iban::String
    - nextgenpsd2_url::String
    - psd2_supported::Bool
"""
Base.@kwdef mutable struct BankLookup <: OpenAPI.APIModel
    bank_name::Union{Nothing, String} = nothing
    bic::Union{Nothing, String} = nothing
    iban::Union{Nothing, String} = nothing
    nextgenpsd2_url::Union{Nothing, String} = nothing
    psd2_supported::Union{Nothing, Bool} = nothing

    function BankLookup(bank_name, bic, iban, nextgenpsd2_url, psd2_supported, )
        o = new(bank_name, bic, iban, nextgenpsd2_url, psd2_supported, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BankLookup

const _property_types_BankLookup = Dict{Symbol,String}(Symbol("bank_name")=>"String", Symbol("bic")=>"String", Symbol("iban")=>"String", Symbol("nextgenpsd2_url")=>"String", Symbol("psd2_supported")=>"Bool", )
OpenAPI.property_type(::Type{ BankLookup }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BankLookup[name]))}

function OpenAPI.check_required(o::BankLookup)
    o.iban === nothing && (return false)
    o.psd2_supported === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::BankLookup)
    OpenAPI.validate_property(BankLookup, Symbol("bank_name"), o.bank_name)
    OpenAPI.validate_property(BankLookup, Symbol("bic"), o.bic)
    OpenAPI.validate_property(BankLookup, Symbol("iban"), o.iban)
    OpenAPI.validate_property(BankLookup, Symbol("nextgenpsd2_url"), o.nextgenpsd2_url)
    OpenAPI.validate_property(BankLookup, Symbol("psd2_supported"), o.psd2_supported)
end

function OpenAPI.validate_property(::Type{ BankLookup }, name::Symbol, val)





end
