# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BudgetGoalRequest

    BudgetGoalRequest(;
        monthly_goal=nothing,
        year=nothing,
    )

    - monthly_goal::String : Monthly goal amount (gross). 0 means \&quot;no goal\&quot; (fallback to default).
    - year::Int64 : Budget year the goal applies to.
"""
Base.@kwdef mutable struct BudgetGoalRequest <: OpenAPI.APIModel
    monthly_goal::Union{Nothing, String} = nothing
    year::Union{Nothing, Int64} = nothing

    function BudgetGoalRequest(monthly_goal, year, )
        o = new(monthly_goal, year, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BudgetGoalRequest

const _property_types_BudgetGoalRequest = Dict{Symbol,String}(Symbol("monthly_goal")=>"String", Symbol("year")=>"Int64", )
OpenAPI.property_type(::Type{ BudgetGoalRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BudgetGoalRequest[name]))}

function OpenAPI.check_required(o::BudgetGoalRequest)
    o.monthly_goal === nothing && (return false)
    o.year === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::BudgetGoalRequest)
    OpenAPI.validate_property(BudgetGoalRequest, Symbol("monthly_goal"), o.monthly_goal)
    OpenAPI.validate_property(BudgetGoalRequest, Symbol("year"), o.year)
end

function OpenAPI.validate_property(::Type{ BudgetGoalRequest }, name::Symbol, val)


    if name === Symbol("year")
        OpenAPI.validate_param(name, "BudgetGoalRequest", :format, val, "int32")
    end
end
