# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DataQuality

    DataQuality(;
        activity_lines=nothing,
        activity_share_pct=nothing,
        spend_lines=nothing,
    )

    - activity_lines::Int64
    - activity_share_pct::Float64
    - spend_lines::Int64
"""
Base.@kwdef mutable struct DataQuality <: OpenAPI.APIModel
    activity_lines::Union{Nothing, Int64} = nothing
    activity_share_pct::Union{Nothing, Float64} = nothing
    spend_lines::Union{Nothing, Int64} = nothing

    function DataQuality(activity_lines, activity_share_pct, spend_lines, )
        o = new(activity_lines, activity_share_pct, spend_lines, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DataQuality

const _property_types_DataQuality = Dict{Symbol,String}(Symbol("activity_lines")=>"Int64", Symbol("activity_share_pct")=>"Float64", Symbol("spend_lines")=>"Int64", )
OpenAPI.property_type(::Type{ DataQuality }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DataQuality[name]))}

function OpenAPI.check_required(o::DataQuality)
    o.activity_lines === nothing && (return false)
    o.activity_share_pct === nothing && (return false)
    o.spend_lines === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DataQuality)
    OpenAPI.validate_property(DataQuality, Symbol("activity_lines"), o.activity_lines)
    OpenAPI.validate_property(DataQuality, Symbol("activity_share_pct"), o.activity_share_pct)
    OpenAPI.validate_property(DataQuality, Symbol("spend_lines"), o.spend_lines)
end

function OpenAPI.validate_property(::Type{ DataQuality }, name::Symbol, val)

    if name === Symbol("activity_lines")
        OpenAPI.validate_param(name, "DataQuality", :minimum, val, 0, false)
    end

    if name === Symbol("activity_share_pct")
        OpenAPI.validate_param(name, "DataQuality", :format, val, "double")
    end

    if name === Symbol("spend_lines")
        OpenAPI.validate_param(name, "DataQuality", :minimum, val, 0, false)
    end
end
