# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""StilleReport

    StilleReport(;
        jahresueberschuss=nothing,
        partners=nothing,
        year=nothing,
    )

    - jahresueberschuss::String
    - partners::Vector{StillePartnerZeile}
    - year::Int64
"""
Base.@kwdef mutable struct StilleReport <: OpenAPI.APIModel
    jahresueberschuss::Union{Nothing, String} = nothing
    partners::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{StillePartnerZeile} }
    year::Union{Nothing, Int64} = nothing

    function StilleReport(jahresueberschuss, partners, year, )
        o = new(jahresueberschuss, partners, year, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type StilleReport

const _property_types_StilleReport = Dict{Symbol,String}(Symbol("jahresueberschuss")=>"String", Symbol("partners")=>"Vector{StillePartnerZeile}", Symbol("year")=>"Int64", )
OpenAPI.property_type(::Type{ StilleReport }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StilleReport[name]))}

function OpenAPI.check_required(o::StilleReport)
    o.jahresueberschuss === nothing && (return false)
    o.partners === nothing && (return false)
    o.year === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::StilleReport)
    OpenAPI.validate_property(StilleReport, Symbol("jahresueberschuss"), o.jahresueberschuss)
    OpenAPI.validate_property(StilleReport, Symbol("partners"), o.partners)
    OpenAPI.validate_property(StilleReport, Symbol("year"), o.year)
end

function OpenAPI.validate_property(::Type{ StilleReport }, name::Symbol, val)



    if name === Symbol("year")
        OpenAPI.validate_param(name, "StilleReport", :format, val, "int32")
    end
end
