# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UsageSnapshot
Current usage for a tenant. &#x60;overage_seats&#x60; is what billing charges 5€/seat/month on.

    UsageSnapshot(;
        connectors=nothing,
        invoicesThisMonth=nothing,
        overageSeats=nothing,
        users=nothing,
    )

    - connectors::Int64
    - invoicesThisMonth::Int64
    - overageSeats::Int64
    - users::Int64
"""
Base.@kwdef mutable struct UsageSnapshot <: OpenAPI.APIModel
    connectors::Union{Nothing, Int64} = nothing
    invoicesThisMonth::Union{Nothing, Int64} = nothing
    overageSeats::Union{Nothing, Int64} = nothing
    users::Union{Nothing, Int64} = nothing

    function UsageSnapshot(connectors, invoicesThisMonth, overageSeats, users, )
        o = new(connectors, invoicesThisMonth, overageSeats, users, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type UsageSnapshot

const _property_types_UsageSnapshot = Dict{Symbol,String}(Symbol("connectors")=>"Int64", Symbol("invoicesThisMonth")=>"Int64", Symbol("overageSeats")=>"Int64", Symbol("users")=>"Int64", )
OpenAPI.property_type(::Type{ UsageSnapshot }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UsageSnapshot[name]))}

function OpenAPI.check_required(o::UsageSnapshot)
    o.connectors === nothing && (return false)
    o.invoicesThisMonth === nothing && (return false)
    o.overageSeats === nothing && (return false)
    o.users === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::UsageSnapshot)
    OpenAPI.validate_property(UsageSnapshot, Symbol("connectors"), o.connectors)
    OpenAPI.validate_property(UsageSnapshot, Symbol("invoicesThisMonth"), o.invoicesThisMonth)
    OpenAPI.validate_property(UsageSnapshot, Symbol("overageSeats"), o.overageSeats)
    OpenAPI.validate_property(UsageSnapshot, Symbol("users"), o.users)
end

function OpenAPI.validate_property(::Type{ UsageSnapshot }, name::Symbol, val)

    if name === Symbol("connectors")
        OpenAPI.validate_param(name, "UsageSnapshot", :format, val, "int64")
    end

    if name === Symbol("invoicesThisMonth")
        OpenAPI.validate_param(name, "UsageSnapshot", :format, val, "int64")
    end

    if name === Symbol("overageSeats")
        OpenAPI.validate_param(name, "UsageSnapshot", :format, val, "int64")
    end

    if name === Symbol("users")
        OpenAPI.validate_param(name, "UsageSnapshot", :format, val, "int64")
    end
end
