# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""YearlyPayrollSummary

    YearlyPayrollSummary(;
        avg_employee_count=nothing,
        months=nothing,
        year=nothing,
        yearly_employer_cost=nothing,
        yearly_gross=nothing,
        yearly_net=nothing,
    )

    - avg_employee_count::Int64
    - months::Vector{PayrollSummaryItem}
    - year::Int64
    - yearly_employer_cost::String
    - yearly_gross::String
    - yearly_net::String
"""
Base.@kwdef mutable struct YearlyPayrollSummary <: OpenAPI.APIModel
    avg_employee_count::Union{Nothing, Int64} = nothing
    months::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{PayrollSummaryItem} }
    year::Union{Nothing, Int64} = nothing
    yearly_employer_cost::Union{Nothing, String} = nothing
    yearly_gross::Union{Nothing, String} = nothing
    yearly_net::Union{Nothing, String} = nothing

    function YearlyPayrollSummary(avg_employee_count, months, year, yearly_employer_cost, yearly_gross, yearly_net, )
        o = new(avg_employee_count, months, year, yearly_employer_cost, yearly_gross, yearly_net, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type YearlyPayrollSummary

const _property_types_YearlyPayrollSummary = Dict{Symbol,String}(Symbol("avg_employee_count")=>"Int64", Symbol("months")=>"Vector{PayrollSummaryItem}", Symbol("year")=>"Int64", Symbol("yearly_employer_cost")=>"String", Symbol("yearly_gross")=>"String", Symbol("yearly_net")=>"String", )
OpenAPI.property_type(::Type{ YearlyPayrollSummary }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_YearlyPayrollSummary[name]))}

function OpenAPI.check_required(o::YearlyPayrollSummary)
    o.avg_employee_count === nothing && (return false)
    o.months === nothing && (return false)
    o.year === nothing && (return false)
    o.yearly_employer_cost === nothing && (return false)
    o.yearly_gross === nothing && (return false)
    o.yearly_net === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::YearlyPayrollSummary)
    OpenAPI.validate_property(YearlyPayrollSummary, Symbol("avg_employee_count"), o.avg_employee_count)
    OpenAPI.validate_property(YearlyPayrollSummary, Symbol("months"), o.months)
    OpenAPI.validate_property(YearlyPayrollSummary, Symbol("year"), o.year)
    OpenAPI.validate_property(YearlyPayrollSummary, Symbol("yearly_employer_cost"), o.yearly_employer_cost)
    OpenAPI.validate_property(YearlyPayrollSummary, Symbol("yearly_gross"), o.yearly_gross)
    OpenAPI.validate_property(YearlyPayrollSummary, Symbol("yearly_net"), o.yearly_net)
end

function OpenAPI.validate_property(::Type{ YearlyPayrollSummary }, name::Symbol, val)

    if name === Symbol("avg_employee_count")
        OpenAPI.validate_param(name, "YearlyPayrollSummary", :format, val, "int32")
    end


    if name === Symbol("year")
        OpenAPI.validate_param(name, "YearlyPayrollSummary", :format, val, "int32")
    end



end
