# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DeliverableResponse

    DeliverableResponse(;
        availableStock=nothing,
        deliverableQuantity=nothing,
        maxSellable=nothing,
        productId=nothing,
        reservedStock=nothing,
        warehouseId=nothing,
    )

    - availableStock::Int64
    - deliverableQuantity::Int64
    - maxSellable::Int64
    - productId::String
    - reservedStock::Int64
    - warehouseId::String
"""
Base.@kwdef mutable struct DeliverableResponse <: OpenAPI.APIModel
    availableStock::Union{Nothing, Int64} = nothing
    deliverableQuantity::Union{Nothing, Int64} = nothing
    maxSellable::Union{Nothing, Int64} = nothing
    productId::Union{Nothing, String} = nothing
    reservedStock::Union{Nothing, Int64} = nothing
    warehouseId::Union{Nothing, String} = nothing

    function DeliverableResponse(availableStock, deliverableQuantity, maxSellable, productId, reservedStock, warehouseId, )
        o = new(availableStock, deliverableQuantity, maxSellable, productId, reservedStock, warehouseId, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DeliverableResponse

const _property_types_DeliverableResponse = Dict{Symbol,String}(Symbol("availableStock")=>"Int64", Symbol("deliverableQuantity")=>"Int64", Symbol("maxSellable")=>"Int64", Symbol("productId")=>"String", Symbol("reservedStock")=>"Int64", Symbol("warehouseId")=>"String", )
OpenAPI.property_type(::Type{ DeliverableResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DeliverableResponse[name]))}

function OpenAPI.check_required(o::DeliverableResponse)
    o.availableStock === nothing && (return false)
    o.deliverableQuantity === nothing && (return false)
    o.productId === nothing && (return false)
    o.reservedStock === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DeliverableResponse)
    OpenAPI.validate_property(DeliverableResponse, Symbol("availableStock"), o.availableStock)
    OpenAPI.validate_property(DeliverableResponse, Symbol("deliverableQuantity"), o.deliverableQuantity)
    OpenAPI.validate_property(DeliverableResponse, Symbol("maxSellable"), o.maxSellable)
    OpenAPI.validate_property(DeliverableResponse, Symbol("productId"), o.productId)
    OpenAPI.validate_property(DeliverableResponse, Symbol("reservedStock"), o.reservedStock)
    OpenAPI.validate_property(DeliverableResponse, Symbol("warehouseId"), o.warehouseId)
end

function OpenAPI.validate_property(::Type{ DeliverableResponse }, name::Symbol, val)

    if name === Symbol("availableStock")
        OpenAPI.validate_param(name, "DeliverableResponse", :format, val, "int64")
    end

    if name === Symbol("deliverableQuantity")
        OpenAPI.validate_param(name, "DeliverableResponse", :format, val, "int64")
    end

    if name === Symbol("maxSellable")
        OpenAPI.validate_param(name, "DeliverableResponse", :format, val, "int64")
    end

    if name === Symbol("productId")
        OpenAPI.validate_param(name, "DeliverableResponse", :format, val, "uuid")
    end

    if name === Symbol("reservedStock")
        OpenAPI.validate_param(name, "DeliverableResponse", :format, val, "int64")
    end

end
