# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProductVariantUpdate

    ProductVariantUpdate(;
        barcode=nothing,
        imageLink=nothing,
        isActive=nothing,
        name=nothing,
        optionValues=nothing,
        price=nothing,
        priceDelta=nothing,
        productId=nothing,
        sku=nothing,
        stockQuantity=nothing,
    )

    - barcode::String
    - imageLink::String
    - isActive::Bool
    - name::String : Human-readable variant label, e.g. \&quot;Red / M\&quot;.
    - optionValues::Any : Option name → value map, e.g. &#x60;{\&quot;Color\&quot;: \&quot;Red\&quot;, \&quot;Size\&quot;: \&quot;M\&quot;}&#x60;.
    - price::String : Explicit override price for this variant (takes precedence over parent price + delta).
    - priceDelta::String : Price adjustment relative to the parent product&#39;s &#x60;default_price&#x60;.
    - productId::String : The parent product this variant belongs to. References the product entity.
    - sku::String : Variant-specific SKU (must be unique per tenant).
    - stockQuantity::Int64 : Variant-level stock (optional — may be tracked on the parent only).
"""
Base.@kwdef mutable struct ProductVariantUpdate <: OpenAPI.APIModel
    barcode::Union{Nothing, String} = nothing
    imageLink::Union{Nothing, String} = nothing
    isActive::Union{Nothing, Bool} = nothing
    name::Union{Nothing, String} = nothing
    optionValues::Union{Nothing, Any} = nothing
    price::Union{Nothing, String} = nothing
    priceDelta::Union{Nothing, String} = nothing
    productId::Union{Nothing, String} = nothing
    sku::Union{Nothing, String} = nothing
    stockQuantity::Union{Nothing, Int64} = nothing

    function ProductVariantUpdate(barcode, imageLink, isActive, name, optionValues, price, priceDelta, productId, sku, stockQuantity, )
        o = new(barcode, imageLink, isActive, name, optionValues, price, priceDelta, productId, sku, stockQuantity, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ProductVariantUpdate

const _property_types_ProductVariantUpdate = Dict{Symbol,String}(Symbol("barcode")=>"String", Symbol("imageLink")=>"String", Symbol("isActive")=>"Bool", Symbol("name")=>"String", Symbol("optionValues")=>"Any", Symbol("price")=>"String", Symbol("priceDelta")=>"String", Symbol("productId")=>"String", Symbol("sku")=>"String", Symbol("stockQuantity")=>"Int64", )
OpenAPI.property_type(::Type{ ProductVariantUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductVariantUpdate[name]))}

function OpenAPI.check_required(o::ProductVariantUpdate)
    true
end

function OpenAPI.validate_properties(o::ProductVariantUpdate)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("barcode"), o.barcode)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("imageLink"), o.imageLink)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("isActive"), o.isActive)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("name"), o.name)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("optionValues"), o.optionValues)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("price"), o.price)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("priceDelta"), o.priceDelta)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("productId"), o.productId)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("sku"), o.sku)
    OpenAPI.validate_property(ProductVariantUpdate, Symbol("stockQuantity"), o.stockQuantity)
end

function OpenAPI.validate_property(::Type{ ProductVariantUpdate }, name::Symbol, val)








    if name === Symbol("productId")
        OpenAPI.validate_param(name, "ProductVariantUpdate", :format, val, "uuid")
    end


    if name === Symbol("stockQuantity")
        OpenAPI.validate_param(name, "ProductVariantUpdate", :format, val, "int64")
    end
end
