# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GenerateCountRequest
Body for the cycle-count generator: create a draft count document for a warehouse, optionally restricted to a set of product ids.

    GenerateCountRequest(;
        notes=nothing,
        productIds=nothing,
        warehouseId=nothing,
    )

    - notes::String
    - productIds::Vector{String}
    - warehouseId::String
"""
Base.@kwdef mutable struct GenerateCountRequest <: OpenAPI.APIModel
    notes::Union{Nothing, String} = nothing
    productIds::Union{Nothing, Vector{String}} = nothing
    warehouseId::Union{Nothing, String} = nothing

    function GenerateCountRequest(notes, productIds, warehouseId, )
        o = new(notes, productIds, warehouseId, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type GenerateCountRequest

const _property_types_GenerateCountRequest = Dict{Symbol,String}(Symbol("notes")=>"String", Symbol("productIds")=>"Vector{String}", Symbol("warehouseId")=>"String", )
OpenAPI.property_type(::Type{ GenerateCountRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GenerateCountRequest[name]))}

function OpenAPI.check_required(o::GenerateCountRequest)
    o.warehouseId === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::GenerateCountRequest)
    OpenAPI.validate_property(GenerateCountRequest, Symbol("notes"), o.notes)
    OpenAPI.validate_property(GenerateCountRequest, Symbol("productIds"), o.productIds)
    OpenAPI.validate_property(GenerateCountRequest, Symbol("warehouseId"), o.warehouseId)
end

function OpenAPI.validate_property(::Type{ GenerateCountRequest }, name::Symbol, val)



end
