# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApiResponse_Vec_Team

    ApiResponseVecTeam(;
        data=nothing,
        error=nothing,
        message=nothing,
        success=nothing,
    )

    - data::Vector{ApiResponseTeamData}
    - error::String
    - message::String
    - success::Bool
"""
Base.@kwdef mutable struct ApiResponseVecTeam <: OpenAPI.APIModel
    data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ApiResponseTeamData} }
    error::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing
    success::Union{Nothing, Bool} = nothing

    function ApiResponseVecTeam(data, error, message, success, )
        o = new(data, error, message, success, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ApiResponseVecTeam

const _property_types_ApiResponseVecTeam = Dict{Symbol,String}(Symbol("data")=>"Vector{ApiResponseTeamData}", Symbol("error")=>"String", Symbol("message")=>"String", Symbol("success")=>"Bool", )
OpenAPI.property_type(::Type{ ApiResponseVecTeam }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApiResponseVecTeam[name]))}

function OpenAPI.check_required(o::ApiResponseVecTeam)
    o.success === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ApiResponseVecTeam)
    OpenAPI.validate_property(ApiResponseVecTeam, Symbol("data"), o.data)
    OpenAPI.validate_property(ApiResponseVecTeam, Symbol("error"), o.error)
    OpenAPI.validate_property(ApiResponseVecTeam, Symbol("message"), o.message)
    OpenAPI.validate_property(ApiResponseVecTeam, Symbol("success"), o.success)
end

function OpenAPI.validate_property(::Type{ ApiResponseVecTeam }, name::Symbol, val)




end
