# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PlanFeatures
Feature flags per plan.

    PlanFeatures(;
        connectors=nothing,
        erp=nothing,
        fancyReports=nothing,
        taxAutomations=nothing,
    )

    - connectors::Bool
    - erp::Bool
    - fancyReports::Bool
    - taxAutomations::Bool
"""
Base.@kwdef mutable struct PlanFeatures <: OpenAPI.APIModel
    connectors::Union{Nothing, Bool} = nothing
    erp::Union{Nothing, Bool} = nothing
    fancyReports::Union{Nothing, Bool} = nothing
    taxAutomations::Union{Nothing, Bool} = nothing

    function PlanFeatures(connectors, erp, fancyReports, taxAutomations, )
        o = new(connectors, erp, fancyReports, taxAutomations, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PlanFeatures

const _property_types_PlanFeatures = Dict{Symbol,String}(Symbol("connectors")=>"Bool", Symbol("erp")=>"Bool", Symbol("fancyReports")=>"Bool", Symbol("taxAutomations")=>"Bool", )
OpenAPI.property_type(::Type{ PlanFeatures }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlanFeatures[name]))}

function OpenAPI.check_required(o::PlanFeatures)
    o.connectors === nothing && (return false)
    o.erp === nothing && (return false)
    o.fancyReports === nothing && (return false)
    o.taxAutomations === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PlanFeatures)
    OpenAPI.validate_property(PlanFeatures, Symbol("connectors"), o.connectors)
    OpenAPI.validate_property(PlanFeatures, Symbol("erp"), o.erp)
    OpenAPI.validate_property(PlanFeatures, Symbol("fancyReports"), o.fancyReports)
    OpenAPI.validate_property(PlanFeatures, Symbol("taxAutomations"), o.taxAutomations)
end

function OpenAPI.validate_property(::Type{ PlanFeatures }, name::Symbol, val)




end
