# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DhlCredentials

    DhlCredentials(;
        api_key=nothing,
        client_id=nothing,
        client_secret=nothing,
    )

    - api_key::String : DHL-API-Key from developer.dhl.com (required for tracking).
    - client_id::String : Client credentials from the DHL developer app; required for label creation.
    - client_secret::String
"""
Base.@kwdef mutable struct DhlCredentials <: OpenAPI.APIModel
    api_key::Union{Nothing, String} = nothing
    client_id::Union{Nothing, String} = nothing
    client_secret::Union{Nothing, String} = nothing

    function DhlCredentials(api_key, client_id, client_secret, )
        o = new(api_key, client_id, client_secret, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DhlCredentials

const _property_types_DhlCredentials = Dict{Symbol,String}(Symbol("api_key")=>"String", Symbol("client_id")=>"String", Symbol("client_secret")=>"String", )
OpenAPI.property_type(::Type{ DhlCredentials }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DhlCredentials[name]))}

function OpenAPI.check_required(o::DhlCredentials)
    o.api_key === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::DhlCredentials)
    OpenAPI.validate_property(DhlCredentials, Symbol("api_key"), o.api_key)
    OpenAPI.validate_property(DhlCredentials, Symbol("client_id"), o.client_id)
    OpenAPI.validate_property(DhlCredentials, Symbol("client_secret"), o.client_secret)
end

function OpenAPI.validate_property(::Type{ DhlCredentials }, name::Symbol, val)



end
