# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateTicketRequest
Request body for creating a support ticket. Wraps the generated &#x60;SupportTicketCreateDto&#x60; fields plus &#x60;message_body&#x60; which is not a Model field (used to create the initial &#x60;ticket_message&#x60;).

    CreateTicketRequest(;
        channel_id=nothing,
        channel_type=nothing,
        customer_email=nothing,
        customer_id=nothing,
        customer_name=nothing,
        external_id=nothing,
        message_body=nothing,
        order_ref=nothing,
        subject=nothing,
    )

    - channel_id::String
    - channel_type::String
    - customer_email::String
    - customer_id::String
    - customer_name::String
    - external_id::String
    - message_body::String
    - order_ref::String
    - subject::String
"""
Base.@kwdef mutable struct CreateTicketRequest <: OpenAPI.APIModel
    channel_id::Union{Nothing, String} = nothing
    channel_type::Union{Nothing, String} = nothing
    customer_email::Union{Nothing, String} = nothing
    customer_id::Union{Nothing, String} = nothing
    customer_name::Union{Nothing, String} = nothing
    external_id::Union{Nothing, String} = nothing
    message_body::Union{Nothing, String} = nothing
    order_ref::Union{Nothing, String} = nothing
    subject::Union{Nothing, String} = nothing

    function CreateTicketRequest(channel_id, channel_type, customer_email, customer_id, customer_name, external_id, message_body, order_ref, subject, )
        o = new(channel_id, channel_type, customer_email, customer_id, customer_name, external_id, message_body, order_ref, subject, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type CreateTicketRequest

const _property_types_CreateTicketRequest = Dict{Symbol,String}(Symbol("channel_id")=>"String", Symbol("channel_type")=>"String", Symbol("customer_email")=>"String", Symbol("customer_id")=>"String", Symbol("customer_name")=>"String", Symbol("external_id")=>"String", Symbol("message_body")=>"String", Symbol("order_ref")=>"String", Symbol("subject")=>"String", )
OpenAPI.property_type(::Type{ CreateTicketRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateTicketRequest[name]))}

function OpenAPI.check_required(o::CreateTicketRequest)
    o.message_body === nothing && (return false)
    o.subject === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::CreateTicketRequest)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("channel_id"), o.channel_id)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("channel_type"), o.channel_type)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("customer_email"), o.customer_email)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("customer_id"), o.customer_id)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("customer_name"), o.customer_name)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("external_id"), o.external_id)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("message_body"), o.message_body)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("order_ref"), o.order_ref)
    OpenAPI.validate_property(CreateTicketRequest, Symbol("subject"), o.subject)
end

function OpenAPI.validate_property(::Type{ CreateTicketRequest }, name::Symbol, val)

    if name === Symbol("channel_id")
        OpenAPI.validate_param(name, "CreateTicketRequest", :format, val, "uuid")
    end








end
