# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SalesVolumeReport

    SalesVolumeReport(;
        grand_total=nothing,
        items=nothing,
        total_count=nothing,
    )

    - grand_total::String
    - items::Vector{SalesVolumeItem}
    - total_count::Int64
"""
Base.@kwdef mutable struct SalesVolumeReport <: OpenAPI.APIModel
    grand_total::Union{Nothing, String} = nothing
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SalesVolumeItem} }
    total_count::Union{Nothing, Int64} = nothing

    function SalesVolumeReport(grand_total, items, total_count, )
        o = new(grand_total, items, total_count, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SalesVolumeReport

const _property_types_SalesVolumeReport = Dict{Symbol,String}(Symbol("grand_total")=>"String", Symbol("items")=>"Vector{SalesVolumeItem}", Symbol("total_count")=>"Int64", )
OpenAPI.property_type(::Type{ SalesVolumeReport }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SalesVolumeReport[name]))}

function OpenAPI.check_required(o::SalesVolumeReport)
    o.grand_total === nothing && (return false)
    o.items === nothing && (return false)
    o.total_count === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SalesVolumeReport)
    OpenAPI.validate_property(SalesVolumeReport, Symbol("grand_total"), o.grand_total)
    OpenAPI.validate_property(SalesVolumeReport, Symbol("items"), o.items)
    OpenAPI.validate_property(SalesVolumeReport, Symbol("total_count"), o.total_count)
end

function OpenAPI.validate_property(::Type{ SalesVolumeReport }, name::Symbol, val)



    if name === Symbol("total_count")
        OpenAPI.validate_param(name, "SalesVolumeReport", :format, val, "int64")
    end
end
