# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApiResponse_Vec_UserTenantInfo_data_inner

    ApiResponseVecUserTenantInfoDataInner(;
        custom_domain=nothing,
        role=nothing,
        subdomain=nothing,
        tenant_id=nothing,
        tenant_name=nothing,
    )

    - custom_domain::String
    - role::String
    - subdomain::String
    - tenant_id::String
    - tenant_name::String
"""
Base.@kwdef mutable struct ApiResponseVecUserTenantInfoDataInner <: OpenAPI.APIModel
    custom_domain::Union{Nothing, String} = nothing
    role::Union{Nothing, String} = nothing
    subdomain::Union{Nothing, String} = nothing
    tenant_id::Union{Nothing, String} = nothing
    tenant_name::Union{Nothing, String} = nothing

    function ApiResponseVecUserTenantInfoDataInner(custom_domain, role, subdomain, tenant_id, tenant_name, )
        o = new(custom_domain, role, subdomain, tenant_id, tenant_name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ApiResponseVecUserTenantInfoDataInner

const _property_types_ApiResponseVecUserTenantInfoDataInner = Dict{Symbol,String}(Symbol("custom_domain")=>"String", Symbol("role")=>"String", Symbol("subdomain")=>"String", Symbol("tenant_id")=>"String", Symbol("tenant_name")=>"String", )
OpenAPI.property_type(::Type{ ApiResponseVecUserTenantInfoDataInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApiResponseVecUserTenantInfoDataInner[name]))}

function OpenAPI.check_required(o::ApiResponseVecUserTenantInfoDataInner)
    o.role === nothing && (return false)
    o.tenant_id === nothing && (return false)
    o.tenant_name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ApiResponseVecUserTenantInfoDataInner)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfoDataInner, Symbol("custom_domain"), o.custom_domain)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfoDataInner, Symbol("role"), o.role)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfoDataInner, Symbol("subdomain"), o.subdomain)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfoDataInner, Symbol("tenant_id"), o.tenant_id)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfoDataInner, Symbol("tenant_name"), o.tenant_name)
end

function OpenAPI.validate_property(::Type{ ApiResponseVecUserTenantInfoDataInner }, name::Symbol, val)




    if name === Symbol("tenant_id")
        OpenAPI.validate_param(name, "ApiResponseVecUserTenantInfoDataInner", :format, val, "uuid")
    end

end
