# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PluginError_oneOf

    PluginErrorOneOf(;
        BadRequest=nothing,
    )

    - BadRequest::Vector{Any}
"""
Base.@kwdef mutable struct PluginErrorOneOf <: OpenAPI.APIModel
    BadRequest::Union{Nothing, Vector{Any}} = nothing

    function PluginErrorOneOf(BadRequest, )
        o = new(BadRequest, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PluginErrorOneOf

const _property_types_PluginErrorOneOf = Dict{Symbol,String}(Symbol("BadRequest")=>"Vector{Any}", )
OpenAPI.property_type(::Type{ PluginErrorOneOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PluginErrorOneOf[name]))}

function OpenAPI.check_required(o::PluginErrorOneOf)
    o.BadRequest === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PluginErrorOneOf)
    OpenAPI.validate_property(PluginErrorOneOf, Symbol("BadRequest"), o.BadRequest)
end

function OpenAPI.validate_property(::Type{ PluginErrorOneOf }, name::Symbol, val)

    if name === Symbol("BadRequest")
        OpenAPI.validate_param(name, "PluginErrorOneOf", :maxItems, val, 2)
        OpenAPI.validate_param(name, "PluginErrorOneOf", :minItems, val, 2)
    end
end
