# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""QuizQuestion

    QuizQuestion(;
        id=nothing,
        options=nothing,
        optionsEn=nothing,
        question=nothing,
        questionEn=nothing,
    )

    - id::String
    - options::Vector{String}
    - optionsEn::Vector{String}
    - question::String
    - questionEn::String
"""
Base.@kwdef mutable struct QuizQuestion <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    options::Union{Nothing, Vector{String}} = nothing
    optionsEn::Union{Nothing, Vector{String}} = nothing
    question::Union{Nothing, String} = nothing
    questionEn::Union{Nothing, String} = nothing

    function QuizQuestion(id, options, optionsEn, question, questionEn, )
        o = new(id, options, optionsEn, question, questionEn, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type QuizQuestion

const _property_types_QuizQuestion = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("options")=>"Vector{String}", Symbol("optionsEn")=>"Vector{String}", Symbol("question")=>"String", Symbol("questionEn")=>"String", )
OpenAPI.property_type(::Type{ QuizQuestion }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_QuizQuestion[name]))}

function OpenAPI.check_required(o::QuizQuestion)
    o.id === nothing && (return false)
    o.options === nothing && (return false)
    o.optionsEn === nothing && (return false)
    o.question === nothing && (return false)
    o.questionEn === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::QuizQuestion)
    OpenAPI.validate_property(QuizQuestion, Symbol("id"), o.id)
    OpenAPI.validate_property(QuizQuestion, Symbol("options"), o.options)
    OpenAPI.validate_property(QuizQuestion, Symbol("optionsEn"), o.optionsEn)
    OpenAPI.validate_property(QuizQuestion, Symbol("question"), o.question)
    OpenAPI.validate_property(QuizQuestion, Symbol("questionEn"), o.questionEn)
end

function OpenAPI.validate_property(::Type{ QuizQuestion }, name::Symbol, val)





end
