# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BilanzItem

    BilanzItem(;
        amount=nothing,
        konto=nothing,
        name=nothing,
    )

    - amount::String
    - konto::String
    - name::String
"""
Base.@kwdef mutable struct BilanzItem <: OpenAPI.APIModel
    amount::Union{Nothing, String} = nothing
    konto::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function BilanzItem(amount, konto, name, )
        o = new(amount, konto, name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BilanzItem

const _property_types_BilanzItem = Dict{Symbol,String}(Symbol("amount")=>"String", Symbol("konto")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ BilanzItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BilanzItem[name]))}

function OpenAPI.check_required(o::BilanzItem)
    o.amount === nothing && (return false)
    o.konto === nothing && (return false)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::BilanzItem)
    OpenAPI.validate_property(BilanzItem, Symbol("amount"), o.amount)
    OpenAPI.validate_property(BilanzItem, Symbol("konto"), o.konto)
    OpenAPI.validate_property(BilanzItem, Symbol("name"), o.name)
end

function OpenAPI.validate_property(::Type{ BilanzItem }, name::Symbol, val)



end
