# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ElsterStatus

    ElsterStatus(;
        cert_configured=nothing,
        eric_available=nothing,
        eric_version=nothing,
        feature_enabled=nothing,
        hint=nothing,
        mode=nothing,
        vendor_id_configured=nothing,
    )

    - cert_configured::Bool
    - eric_available::Bool
    - eric_version::String
    - feature_enabled::Bool
    - hint::String
    - mode::String
    - vendor_id_configured::Bool
"""
Base.@kwdef mutable struct ElsterStatus <: OpenAPI.APIModel
    cert_configured::Union{Nothing, Bool} = nothing
    eric_available::Union{Nothing, Bool} = nothing
    eric_version::Union{Nothing, String} = nothing
    feature_enabled::Union{Nothing, Bool} = nothing
    hint::Union{Nothing, String} = nothing
    mode::Union{Nothing, String} = nothing
    vendor_id_configured::Union{Nothing, Bool} = nothing

    function ElsterStatus(cert_configured, eric_available, eric_version, feature_enabled, hint, mode, vendor_id_configured, )
        o = new(cert_configured, eric_available, eric_version, feature_enabled, hint, mode, vendor_id_configured, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ElsterStatus

const _property_types_ElsterStatus = Dict{Symbol,String}(Symbol("cert_configured")=>"Bool", Symbol("eric_available")=>"Bool", Symbol("eric_version")=>"String", Symbol("feature_enabled")=>"Bool", Symbol("hint")=>"String", Symbol("mode")=>"String", Symbol("vendor_id_configured")=>"Bool", )
OpenAPI.property_type(::Type{ ElsterStatus }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ElsterStatus[name]))}

function OpenAPI.check_required(o::ElsterStatus)
    o.cert_configured === nothing && (return false)
    o.eric_available === nothing && (return false)
    o.feature_enabled === nothing && (return false)
    o.hint === nothing && (return false)
    o.mode === nothing && (return false)
    o.vendor_id_configured === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ElsterStatus)
    OpenAPI.validate_property(ElsterStatus, Symbol("cert_configured"), o.cert_configured)
    OpenAPI.validate_property(ElsterStatus, Symbol("eric_available"), o.eric_available)
    OpenAPI.validate_property(ElsterStatus, Symbol("eric_version"), o.eric_version)
    OpenAPI.validate_property(ElsterStatus, Symbol("feature_enabled"), o.feature_enabled)
    OpenAPI.validate_property(ElsterStatus, Symbol("hint"), o.hint)
    OpenAPI.validate_property(ElsterStatus, Symbol("mode"), o.mode)
    OpenAPI.validate_property(ElsterStatus, Symbol("vendor_id_configured"), o.vendor_id_configured)
end

function OpenAPI.validate_property(::Type{ ElsterStatus }, name::Symbol, val)







end
