# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Attachment

    Attachment(;
        contactId=nothing,
        fileName=nothing,
        fileSize=nothing,
        mimeType=nothing,
        ocrText=nothing,
        originalName=nothing,
        pdfaPath=nothing,
        sha256Hash=nothing,
        uploadedBy=nothing,
    )

    - contactId::String : Contact this attachment belongs to (per-contact DMS). References the contact entity.
    - fileName::String
    - fileSize::Int64
    - mimeType::String
    - ocrText::String : Raw text extracted by client-side OCR (tesseract.js), if run.
    - originalName::String
    - pdfaPath::String
    - sha256Hash::String
    - uploadedBy::String
"""
Base.@kwdef mutable struct Attachment <: OpenAPI.APIModel
    contactId::Union{Nothing, String} = nothing
    fileName::Union{Nothing, String} = nothing
    fileSize::Union{Nothing, Int64} = nothing
    mimeType::Union{Nothing, String} = nothing
    ocrText::Union{Nothing, String} = nothing
    originalName::Union{Nothing, String} = nothing
    pdfaPath::Union{Nothing, String} = nothing
    sha256Hash::Union{Nothing, String} = nothing
    uploadedBy::Union{Nothing, String} = nothing

    function Attachment(contactId, fileName, fileSize, mimeType, ocrText, originalName, pdfaPath, sha256Hash, uploadedBy, )
        o = new(contactId, fileName, fileSize, mimeType, ocrText, originalName, pdfaPath, sha256Hash, uploadedBy, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Attachment

const _property_types_Attachment = Dict{Symbol,String}(Symbol("contactId")=>"String", Symbol("fileName")=>"String", Symbol("fileSize")=>"Int64", Symbol("mimeType")=>"String", Symbol("ocrText")=>"String", Symbol("originalName")=>"String", Symbol("pdfaPath")=>"String", Symbol("sha256Hash")=>"String", Symbol("uploadedBy")=>"String", )
OpenAPI.property_type(::Type{ Attachment }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Attachment[name]))}

function OpenAPI.check_required(o::Attachment)
    o.fileName === nothing && (return false)
    o.originalName === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Attachment)
    OpenAPI.validate_property(Attachment, Symbol("contactId"), o.contactId)
    OpenAPI.validate_property(Attachment, Symbol("fileName"), o.fileName)
    OpenAPI.validate_property(Attachment, Symbol("fileSize"), o.fileSize)
    OpenAPI.validate_property(Attachment, Symbol("mimeType"), o.mimeType)
    OpenAPI.validate_property(Attachment, Symbol("ocrText"), o.ocrText)
    OpenAPI.validate_property(Attachment, Symbol("originalName"), o.originalName)
    OpenAPI.validate_property(Attachment, Symbol("pdfaPath"), o.pdfaPath)
    OpenAPI.validate_property(Attachment, Symbol("sha256Hash"), o.sha256Hash)
    OpenAPI.validate_property(Attachment, Symbol("uploadedBy"), o.uploadedBy)
end

function OpenAPI.validate_property(::Type{ Attachment }, name::Symbol, val)



    if name === Symbol("fileSize")
        OpenAPI.validate_param(name, "Attachment", :format, val, "int64")
    end






    if name === Symbol("uploadedBy")
        OpenAPI.validate_param(name, "Attachment", :format, val, "uuid")
    end
end
