# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""YearTotal

    YearTotal(;
        tco2e=nothing,
        year=nothing,
    )

    - tco2e::String
    - year::Int64
"""
Base.@kwdef mutable struct YearTotal <: OpenAPI.APIModel
    tco2e::Union{Nothing, String} = nothing
    year::Union{Nothing, Int64} = nothing

    function YearTotal(tco2e, year, )
        o = new(tco2e, year, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type YearTotal

const _property_types_YearTotal = Dict{Symbol,String}(Symbol("tco2e")=>"String", Symbol("year")=>"Int64", )
OpenAPI.property_type(::Type{ YearTotal }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_YearTotal[name]))}

function OpenAPI.check_required(o::YearTotal)
    o.tco2e === nothing && (return false)
    o.year === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::YearTotal)
    OpenAPI.validate_property(YearTotal, Symbol("tco2e"), o.tco2e)
    OpenAPI.validate_property(YearTotal, Symbol("year"), o.year)
end

function OpenAPI.validate_property(::Type{ YearTotal }, name::Symbol, val)


    if name === Symbol("year")
        OpenAPI.validate_param(name, "YearTotal", :format, val, "int32")
    end
end
