# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ConvertResponse
Response of the proforma → invoice conversion.

    ConvertResponse(;
        invoiceId=nothing,
        invoiceNumber=nothing,
        proformaId=nothing,
        proformaNumber=nothing,
    )

    - invoiceId::String
    - invoiceNumber::String
    - proformaId::String
    - proformaNumber::String
"""
Base.@kwdef mutable struct ConvertResponse <: OpenAPI.APIModel
    invoiceId::Union{Nothing, String} = nothing
    invoiceNumber::Union{Nothing, String} = nothing
    proformaId::Union{Nothing, String} = nothing
    proformaNumber::Union{Nothing, String} = nothing

    function ConvertResponse(invoiceId, invoiceNumber, proformaId, proformaNumber, )
        o = new(invoiceId, invoiceNumber, proformaId, proformaNumber, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ConvertResponse

const _property_types_ConvertResponse = Dict{Symbol,String}(Symbol("invoiceId")=>"String", Symbol("invoiceNumber")=>"String", Symbol("proformaId")=>"String", Symbol("proformaNumber")=>"String", )
OpenAPI.property_type(::Type{ ConvertResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConvertResponse[name]))}

function OpenAPI.check_required(o::ConvertResponse)
    o.invoiceId === nothing && (return false)
    o.invoiceNumber === nothing && (return false)
    o.proformaId === nothing && (return false)
    o.proformaNumber === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ConvertResponse)
    OpenAPI.validate_property(ConvertResponse, Symbol("invoiceId"), o.invoiceId)
    OpenAPI.validate_property(ConvertResponse, Symbol("invoiceNumber"), o.invoiceNumber)
    OpenAPI.validate_property(ConvertResponse, Symbol("proformaId"), o.proformaId)
    OpenAPI.validate_property(ConvertResponse, Symbol("proformaNumber"), o.proformaNumber)
end

function OpenAPI.validate_property(::Type{ ConvertResponse }, name::Symbol, val)




end
