# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""MyTrainingItem

    MyTrainingItem(;
        assignmentId=nothing,
        certificateId=nothing,
        code=nothing,
        description=nothing,
        dueDate=nothing,
        lastScore=nothing,
        passScore=nothing,
        passed=nothing,
        status=nothing,
        title=nothing,
        trainingId=nothing,
        validUntil=nothing,
    )

    - assignmentId::String
    - certificateId::String
    - code::String
    - description::String
    - dueDate::Date
    - lastScore::Int64
    - passScore::Int64
    - passed::Bool
    - status::AssignmentStatus
    - title::String
    - trainingId::String
    - validUntil::ZonedDateTime
"""
Base.@kwdef mutable struct MyTrainingItem <: OpenAPI.APIModel
    assignmentId::Union{Nothing, String} = nothing
    certificateId::Union{Nothing, String} = nothing
    code::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    dueDate::Union{Nothing, Date} = nothing
    lastScore::Union{Nothing, Int64} = nothing
    passScore::Union{Nothing, Int64} = nothing
    passed::Union{Nothing, Bool} = nothing
    status = nothing # spec type: Union{ Nothing, AssignmentStatus }
    title::Union{Nothing, String} = nothing
    trainingId::Union{Nothing, String} = nothing
    validUntil::Union{Nothing, ZonedDateTime} = nothing

    function MyTrainingItem(assignmentId, certificateId, code, description, dueDate, lastScore, passScore, passed, status, title, trainingId, validUntil, )
        o = new(assignmentId, certificateId, code, description, dueDate, lastScore, passScore, passed, status, title, trainingId, validUntil, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type MyTrainingItem

const _property_types_MyTrainingItem = Dict{Symbol,String}(Symbol("assignmentId")=>"String", Symbol("certificateId")=>"String", Symbol("code")=>"String", Symbol("description")=>"String", Symbol("dueDate")=>"Date", Symbol("lastScore")=>"Int64", Symbol("passScore")=>"Int64", Symbol("passed")=>"Bool", Symbol("status")=>"AssignmentStatus", Symbol("title")=>"String", Symbol("trainingId")=>"String", Symbol("validUntil")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ MyTrainingItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_MyTrainingItem[name]))}

function OpenAPI.check_required(o::MyTrainingItem)
    o.assignmentId === nothing && (return false)
    o.code === nothing && (return false)
    o.passScore === nothing && (return false)
    o.status === nothing && (return false)
    o.title === nothing && (return false)
    o.trainingId === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::MyTrainingItem)
    OpenAPI.validate_property(MyTrainingItem, Symbol("assignmentId"), o.assignmentId)
    OpenAPI.validate_property(MyTrainingItem, Symbol("certificateId"), o.certificateId)
    OpenAPI.validate_property(MyTrainingItem, Symbol("code"), o.code)
    OpenAPI.validate_property(MyTrainingItem, Symbol("description"), o.description)
    OpenAPI.validate_property(MyTrainingItem, Symbol("dueDate"), o.dueDate)
    OpenAPI.validate_property(MyTrainingItem, Symbol("lastScore"), o.lastScore)
    OpenAPI.validate_property(MyTrainingItem, Symbol("passScore"), o.passScore)
    OpenAPI.validate_property(MyTrainingItem, Symbol("passed"), o.passed)
    OpenAPI.validate_property(MyTrainingItem, Symbol("status"), o.status)
    OpenAPI.validate_property(MyTrainingItem, Symbol("title"), o.title)
    OpenAPI.validate_property(MyTrainingItem, Symbol("trainingId"), o.trainingId)
    OpenAPI.validate_property(MyTrainingItem, Symbol("validUntil"), o.validUntil)
end

function OpenAPI.validate_property(::Type{ MyTrainingItem }, name::Symbol, val)

    if name === Symbol("assignmentId")
        OpenAPI.validate_param(name, "MyTrainingItem", :format, val, "uuid")
    end




    if name === Symbol("dueDate")
        OpenAPI.validate_param(name, "MyTrainingItem", :format, val, "date")
    end

    if name === Symbol("lastScore")
        OpenAPI.validate_param(name, "MyTrainingItem", :format, val, "int32")
    end

    if name === Symbol("passScore")
        OpenAPI.validate_param(name, "MyTrainingItem", :format, val, "int32")
    end




    if name === Symbol("trainingId")
        OpenAPI.validate_param(name, "MyTrainingItem", :format, val, "uuid")
    end

    if name === Symbol("validUntil")
        OpenAPI.validate_param(name, "MyTrainingItem", :format, val, "date-time")
    end
end
