# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderConfirmationCreate

    OrderConfirmationCreate(;
        address=nothing,
        confirmationNumber=nothing,
        contactId=nothing,
        contactName=nothing,
        currency=nothing,
        files=nothing,
        introduction=nothing,
        lineItems=nothing,
        precedingSalesVoucherId=nothing,
        precedingSalesVoucherType=nothing,
        remark=nothing,
        taxCondition=nothing,
        title=nothing,
        voucherDate=nothing,
        voucherStatus=nothing,
    )

    - address::Any
    - confirmationNumber::String
    - contactId::String : References the contact entity.
    - contactName::String
    - currency::String
    - files::Any
    - introduction::String
    - lineItems::Any
    - precedingSalesVoucherId::String : References the preceding sales voucher entity.
    - precedingSalesVoucherType::PrecedingSalesVoucherType
    - remark::String
    - taxCondition::String
    - title::String
    - voucherDate::Date
    - voucherStatus::VoucherStatus
"""
Base.@kwdef mutable struct OrderConfirmationCreate <: OpenAPI.APIModel
    address::Union{Nothing, Any} = nothing
    confirmationNumber::Union{Nothing, String} = nothing
    contactId::Union{Nothing, String} = nothing
    contactName::Union{Nothing, String} = nothing
    currency::Union{Nothing, String} = nothing
    files::Union{Nothing, Any} = nothing
    introduction::Union{Nothing, String} = nothing
    lineItems::Union{Nothing, Any} = nothing
    precedingSalesVoucherId::Union{Nothing, String} = nothing
    precedingSalesVoucherType = nothing # spec type: Union{ Nothing, PrecedingSalesVoucherType }
    remark::Union{Nothing, String} = nothing
    taxCondition::Union{Nothing, String} = nothing
    title::Union{Nothing, String} = nothing
    voucherDate::Union{Nothing, Date} = nothing
    voucherStatus = nothing # spec type: Union{ Nothing, VoucherStatus }

    function OrderConfirmationCreate(address, confirmationNumber, contactId, contactName, currency, files, introduction, lineItems, precedingSalesVoucherId, precedingSalesVoucherType, remark, taxCondition, title, voucherDate, voucherStatus, )
        o = new(address, confirmationNumber, contactId, contactName, currency, files, introduction, lineItems, precedingSalesVoucherId, precedingSalesVoucherType, remark, taxCondition, title, voucherDate, voucherStatus, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type OrderConfirmationCreate

const _property_types_OrderConfirmationCreate = Dict{Symbol,String}(Symbol("address")=>"Any", Symbol("confirmationNumber")=>"String", Symbol("contactId")=>"String", Symbol("contactName")=>"String", Symbol("currency")=>"String", Symbol("files")=>"Any", Symbol("introduction")=>"String", Symbol("lineItems")=>"Any", Symbol("precedingSalesVoucherId")=>"String", Symbol("precedingSalesVoucherType")=>"PrecedingSalesVoucherType", Symbol("remark")=>"String", Symbol("taxCondition")=>"String", Symbol("title")=>"String", Symbol("voucherDate")=>"Date", Symbol("voucherStatus")=>"VoucherStatus", )
OpenAPI.property_type(::Type{ OrderConfirmationCreate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderConfirmationCreate[name]))}

function OpenAPI.check_required(o::OrderConfirmationCreate)
    o.currency === nothing && (return false)
    o.voucherDate === nothing && (return false)
    o.voucherStatus === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::OrderConfirmationCreate)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("address"), o.address)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("confirmationNumber"), o.confirmationNumber)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("contactId"), o.contactId)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("contactName"), o.contactName)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("currency"), o.currency)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("files"), o.files)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("introduction"), o.introduction)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("lineItems"), o.lineItems)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("precedingSalesVoucherId"), o.precedingSalesVoucherId)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("precedingSalesVoucherType"), o.precedingSalesVoucherType)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("remark"), o.remark)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("taxCondition"), o.taxCondition)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("title"), o.title)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("voucherDate"), o.voucherDate)
    OpenAPI.validate_property(OrderConfirmationCreate, Symbol("voucherStatus"), o.voucherStatus)
end

function OpenAPI.validate_property(::Type{ OrderConfirmationCreate }, name::Symbol, val)














    if name === Symbol("voucherDate")
        OpenAPI.validate_param(name, "OrderConfirmationCreate", :format, val, "date")
    end

end
