# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""InventoryCount

    InventoryCount(;
        countDate=nothing,
        countNumber=nothing,
        lineItems=nothing,
        notes=nothing,
        status=nothing,
        warehouseId=nothing,
    )

    - countDate::Date
    - countNumber::String
    - lineItems::Any : JSON array of &#x60;{product_id, name, sku, expected_quantity, counted_quantity, bin_location?, batch_number?, variance}&#x60;.
    - notes::String
    - status::InventoryCountStatus : One of: draft | counting | reviewed | posted
    - warehouseId::String : References the warehouse entity.
"""
Base.@kwdef mutable struct InventoryCount <: OpenAPI.APIModel
    countDate::Union{Nothing, Date} = nothing
    countNumber::Union{Nothing, String} = nothing
    lineItems::Union{Nothing, Any} = nothing
    notes::Union{Nothing, String} = nothing
    status = nothing # spec type: Union{ Nothing, InventoryCountStatus }
    warehouseId::Union{Nothing, String} = nothing

    function InventoryCount(countDate, countNumber, lineItems, notes, status, warehouseId, )
        o = new(countDate, countNumber, lineItems, notes, status, warehouseId, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type InventoryCount

const _property_types_InventoryCount = Dict{Symbol,String}(Symbol("countDate")=>"Date", Symbol("countNumber")=>"String", Symbol("lineItems")=>"Any", Symbol("notes")=>"String", Symbol("status")=>"InventoryCountStatus", Symbol("warehouseId")=>"String", )
OpenAPI.property_type(::Type{ InventoryCount }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InventoryCount[name]))}

function OpenAPI.check_required(o::InventoryCount)
    o.countDate === nothing && (return false)
    o.countNumber === nothing && (return false)
    o.lineItems === nothing && (return false)
    o.status === nothing && (return false)
    o.warehouseId === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::InventoryCount)
    OpenAPI.validate_property(InventoryCount, Symbol("countDate"), o.countDate)
    OpenAPI.validate_property(InventoryCount, Symbol("countNumber"), o.countNumber)
    OpenAPI.validate_property(InventoryCount, Symbol("lineItems"), o.lineItems)
    OpenAPI.validate_property(InventoryCount, Symbol("notes"), o.notes)
    OpenAPI.validate_property(InventoryCount, Symbol("status"), o.status)
    OpenAPI.validate_property(InventoryCount, Symbol("warehouseId"), o.warehouseId)
end

function OpenAPI.validate_property(::Type{ InventoryCount }, name::Symbol, val)

    if name === Symbol("countDate")
        OpenAPI.validate_param(name, "InventoryCount", :format, val, "date")
    end





end
