# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateChannelDto

    CreateChannelDto(;
        channel_type=nothing,
        config=nothing,
        name=nothing,
    )

    - channel_type::String
    - config::Any
    - name::String
"""
Base.@kwdef mutable struct CreateChannelDto <: OpenAPI.APIModel
    channel_type::Union{Nothing, String} = nothing
    config::Union{Nothing, Any} = nothing
    name::Union{Nothing, String} = nothing

    function CreateChannelDto(channel_type, config, name, )
        o = new(channel_type, config, name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type CreateChannelDto

const _property_types_CreateChannelDto = Dict{Symbol,String}(Symbol("channel_type")=>"String", Symbol("config")=>"Any", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ CreateChannelDto }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateChannelDto[name]))}

function OpenAPI.check_required(o::CreateChannelDto)
    o.channel_type === nothing && (return false)
    o.config === nothing && (return false)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::CreateChannelDto)
    OpenAPI.validate_property(CreateChannelDto, Symbol("channel_type"), o.channel_type)
    OpenAPI.validate_property(CreateChannelDto, Symbol("config"), o.config)
    OpenAPI.validate_property(CreateChannelDto, Symbol("name"), o.name)
end

function OpenAPI.validate_property(::Type{ CreateChannelDto }, name::Symbol, val)



end
