# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GdprUser

    GdprUser(;
        createdAt=nothing,
        email=nothing,
        id=nothing,
        name=nothing,
    )

    - createdAt::ZonedDateTime
    - email::String
    - id::String
    - name::String
"""
Base.@kwdef mutable struct GdprUser <: OpenAPI.APIModel
    createdAt::Union{Nothing, ZonedDateTime} = nothing
    email::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function GdprUser(createdAt, email, id, name, )
        o = new(createdAt, email, id, name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type GdprUser

const _property_types_GdprUser = Dict{Symbol,String}(Symbol("createdAt")=>"ZonedDateTime", Symbol("email")=>"String", Symbol("id")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ GdprUser }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GdprUser[name]))}

function OpenAPI.check_required(o::GdprUser)
    o.createdAt === nothing && (return false)
    o.email === nothing && (return false)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::GdprUser)
    OpenAPI.validate_property(GdprUser, Symbol("createdAt"), o.createdAt)
    OpenAPI.validate_property(GdprUser, Symbol("email"), o.email)
    OpenAPI.validate_property(GdprUser, Symbol("id"), o.id)
    OpenAPI.validate_property(GdprUser, Symbol("name"), o.name)
end

function OpenAPI.validate_property(::Type{ GdprUser }, name::Symbol, val)

    if name === Symbol("createdAt")
        OpenAPI.validate_param(name, "GdprUser", :format, val, "date-time")
    end


    if name === Symbol("id")
        OpenAPI.validate_param(name, "GdprUser", :format, val, "uuid")
    end

end
