# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ActivityUpdate

    ActivityUpdate(;
        activityType=nothing,
        assignedTo=nothing,
        contactId=nothing,
        description=nothing,
        dueDate=nothing,
        reminderDate=nothing,
        status=nothing,
        subject=nothing,
    )

    - activityType::ActivityType : One of: call | email | meeting | task | note
    - assignedTo::String : User responsible (&#x60;employee.employee_id&#x60;).
    - contactId::String : Contact this activity belongs to (&#x60;contact.contact_id&#x60;). References the contact entity.
    - description::String
    - dueDate::Date : Follow-up / Wiedervorlage date. Open activities with a due date in the past are overdue.
    - reminderDate::Date : When to remind about the follow-up.
    - status::ActivityStatus : One of: open | done | cancelled
    - subject::String : Short subject line.
"""
Base.@kwdef mutable struct ActivityUpdate <: OpenAPI.APIModel
    activityType = nothing # spec type: Union{ Nothing, ActivityType }
    assignedTo::Union{Nothing, String} = nothing
    contactId::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    dueDate::Union{Nothing, Date} = nothing
    reminderDate::Union{Nothing, Date} = nothing
    status = nothing # spec type: Union{ Nothing, ActivityStatus }
    subject::Union{Nothing, String} = nothing

    function ActivityUpdate(activityType, assignedTo, contactId, description, dueDate, reminderDate, status, subject, )
        o = new(activityType, assignedTo, contactId, description, dueDate, reminderDate, status, subject, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ActivityUpdate

const _property_types_ActivityUpdate = Dict{Symbol,String}(Symbol("activityType")=>"ActivityType", Symbol("assignedTo")=>"String", Symbol("contactId")=>"String", Symbol("description")=>"String", Symbol("dueDate")=>"Date", Symbol("reminderDate")=>"Date", Symbol("status")=>"ActivityStatus", Symbol("subject")=>"String", )
OpenAPI.property_type(::Type{ ActivityUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ActivityUpdate[name]))}

function OpenAPI.check_required(o::ActivityUpdate)
    true
end

function OpenAPI.validate_properties(o::ActivityUpdate)
    OpenAPI.validate_property(ActivityUpdate, Symbol("activityType"), o.activityType)
    OpenAPI.validate_property(ActivityUpdate, Symbol("assignedTo"), o.assignedTo)
    OpenAPI.validate_property(ActivityUpdate, Symbol("contactId"), o.contactId)
    OpenAPI.validate_property(ActivityUpdate, Symbol("description"), o.description)
    OpenAPI.validate_property(ActivityUpdate, Symbol("dueDate"), o.dueDate)
    OpenAPI.validate_property(ActivityUpdate, Symbol("reminderDate"), o.reminderDate)
    OpenAPI.validate_property(ActivityUpdate, Symbol("status"), o.status)
    OpenAPI.validate_property(ActivityUpdate, Symbol("subject"), o.subject)
end

function OpenAPI.validate_property(::Type{ ActivityUpdate }, name::Symbol, val)





    if name === Symbol("dueDate")
        OpenAPI.validate_param(name, "ActivityUpdate", :format, val, "date")
    end

    if name === Symbol("reminderDate")
        OpenAPI.validate_param(name, "ActivityUpdate", :format, val, "date")
    end


end
