# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LegalDocumentUpsert
One document to upsert (&#x60;PUT /api/v1/legal/documents&#x60; body element).

    LegalDocumentUpsert(;
        content=nothing,
        docType=nothing,
        lang=nothing,
        title=nothing,
    )

    - content::String
    - docType::String
    - lang::String
    - title::String
"""
Base.@kwdef mutable struct LegalDocumentUpsert <: OpenAPI.APIModel
    content::Union{Nothing, String} = nothing
    docType::Union{Nothing, String} = nothing
    lang::Union{Nothing, String} = nothing
    title::Union{Nothing, String} = nothing

    function LegalDocumentUpsert(content, docType, lang, title, )
        o = new(content, docType, lang, title, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type LegalDocumentUpsert

const _property_types_LegalDocumentUpsert = Dict{Symbol,String}(Symbol("content")=>"String", Symbol("docType")=>"String", Symbol("lang")=>"String", Symbol("title")=>"String", )
OpenAPI.property_type(::Type{ LegalDocumentUpsert }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LegalDocumentUpsert[name]))}

function OpenAPI.check_required(o::LegalDocumentUpsert)
    o.content === nothing && (return false)
    o.docType === nothing && (return false)
    o.lang === nothing && (return false)
    o.title === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::LegalDocumentUpsert)
    OpenAPI.validate_property(LegalDocumentUpsert, Symbol("content"), o.content)
    OpenAPI.validate_property(LegalDocumentUpsert, Symbol("docType"), o.docType)
    OpenAPI.validate_property(LegalDocumentUpsert, Symbol("lang"), o.lang)
    OpenAPI.validate_property(LegalDocumentUpsert, Symbol("title"), o.title)
end

function OpenAPI.validate_property(::Type{ LegalDocumentUpsert }, name::Symbol, val)




end
