# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LegalDocument

    LegalDocument(;
        content=nothing,
        docType=nothing,
        lang=nothing,
        title=nothing,
    )

    - content::String : Plain text, &#x60;\\n\\n&#x60; separates paragraphs.
    - docType::LegalDocType
    - lang::LanguageCode
    - title::String
"""
Base.@kwdef mutable struct LegalDocument <: OpenAPI.APIModel
    content::Union{Nothing, String} = nothing
    docType = nothing # spec type: Union{ Nothing, LegalDocType }
    lang = nothing # spec type: Union{ Nothing, LanguageCode }
    title::Union{Nothing, String} = nothing

    function LegalDocument(content, docType, lang, title, )
        o = new(content, docType, lang, title, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type LegalDocument

const _property_types_LegalDocument = Dict{Symbol,String}(Symbol("content")=>"String", Symbol("docType")=>"LegalDocType", Symbol("lang")=>"LanguageCode", Symbol("title")=>"String", )
OpenAPI.property_type(::Type{ LegalDocument }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LegalDocument[name]))}

function OpenAPI.check_required(o::LegalDocument)
    o.content === nothing && (return false)
    o.docType === nothing && (return false)
    o.lang === nothing && (return false)
    o.title === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::LegalDocument)
    OpenAPI.validate_property(LegalDocument, Symbol("content"), o.content)
    OpenAPI.validate_property(LegalDocument, Symbol("docType"), o.docType)
    OpenAPI.validate_property(LegalDocument, Symbol("lang"), o.lang)
    OpenAPI.validate_property(LegalDocument, Symbol("title"), o.title)
end

function OpenAPI.validate_property(::Type{ LegalDocument }, name::Symbol, val)




end
