# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ReorderProposalResponse
The response envelope for a reorder proposal run.

    ReorderProposalResponse(;
        generatedAt=nothing,
        lines=nothing,
        totalSuggestedQuantity=nothing,
    )

    - generatedAt::ZonedDateTime
    - lines::Vector{ReorderProposalLine}
    - totalSuggestedQuantity::Int64
"""
Base.@kwdef mutable struct ReorderProposalResponse <: OpenAPI.APIModel
    generatedAt::Union{Nothing, ZonedDateTime} = nothing
    lines::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ReorderProposalLine} }
    totalSuggestedQuantity::Union{Nothing, Int64} = nothing

    function ReorderProposalResponse(generatedAt, lines, totalSuggestedQuantity, )
        o = new(generatedAt, lines, totalSuggestedQuantity, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ReorderProposalResponse

const _property_types_ReorderProposalResponse = Dict{Symbol,String}(Symbol("generatedAt")=>"ZonedDateTime", Symbol("lines")=>"Vector{ReorderProposalLine}", Symbol("totalSuggestedQuantity")=>"Int64", )
OpenAPI.property_type(::Type{ ReorderProposalResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ReorderProposalResponse[name]))}

function OpenAPI.check_required(o::ReorderProposalResponse)
    o.generatedAt === nothing && (return false)
    o.lines === nothing && (return false)
    o.totalSuggestedQuantity === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ReorderProposalResponse)
    OpenAPI.validate_property(ReorderProposalResponse, Symbol("generatedAt"), o.generatedAt)
    OpenAPI.validate_property(ReorderProposalResponse, Symbol("lines"), o.lines)
    OpenAPI.validate_property(ReorderProposalResponse, Symbol("totalSuggestedQuantity"), o.totalSuggestedQuantity)
end

function OpenAPI.validate_property(::Type{ ReorderProposalResponse }, name::Symbol, val)

    if name === Symbol("generatedAt")
        OpenAPI.validate_param(name, "ReorderProposalResponse", :format, val, "date-time")
    end


    if name === Symbol("totalSuggestedQuantity")
        OpenAPI.validate_param(name, "ReorderProposalResponse", :format, val, "int64")
    end
end
