# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ImportTestRequest

    ImportTestRequest(;
        apiKey=nothing,
        provider=nothing,
    )

    - apiKey::String
    - provider::String
"""
Base.@kwdef mutable struct ImportTestRequest <: OpenAPI.APIModel
    apiKey::Union{Nothing, String} = nothing
    provider::Union{Nothing, String} = nothing

    function ImportTestRequest(apiKey, provider, )
        o = new(apiKey, provider, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ImportTestRequest

const _property_types_ImportTestRequest = Dict{Symbol,String}(Symbol("apiKey")=>"String", Symbol("provider")=>"String", )
OpenAPI.property_type(::Type{ ImportTestRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ImportTestRequest[name]))}

function OpenAPI.check_required(o::ImportTestRequest)
    o.apiKey === nothing && (return false)
    o.provider === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ImportTestRequest)
    OpenAPI.validate_property(ImportTestRequest, Symbol("apiKey"), o.apiKey)
    OpenAPI.validate_property(ImportTestRequest, Symbol("provider"), o.provider)
end

function OpenAPI.validate_property(::Type{ ImportTestRequest }, name::Symbol, val)


end
