# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateRolePayload

    UpdateRolePayload(;
        role=nothing,
        sync_permissions=nothing,
    )

    - role::String
    - sync_permissions::Bool
"""
Base.@kwdef mutable struct UpdateRolePayload <: OpenAPI.APIModel
    role::Union{Nothing, String} = nothing
    sync_permissions::Union{Nothing, Bool} = nothing

    function UpdateRolePayload(role, sync_permissions, )
        o = new(role, sync_permissions, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type UpdateRolePayload

const _property_types_UpdateRolePayload = Dict{Symbol,String}(Symbol("role")=>"String", Symbol("sync_permissions")=>"Bool", )
OpenAPI.property_type(::Type{ UpdateRolePayload }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateRolePayload[name]))}

function OpenAPI.check_required(o::UpdateRolePayload)
    o.role === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::UpdateRolePayload)
    OpenAPI.validate_property(UpdateRolePayload, Symbol("role"), o.role)
    OpenAPI.validate_property(UpdateRolePayload, Symbol("sync_permissions"), o.sync_permissions)
end

function OpenAPI.validate_property(::Type{ UpdateRolePayload }, name::Symbol, val)


end
