# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SubscriptionOverview
Tenant subscription overview for the billing page: current plan, status, period end, trial state, effective limits, current usage and feature flags. Backed by Paddle Billing webhook data written into &#x60;billing_info&#x60; + &#x60;tenants.plan&#x60;, and by the canonical plans in &#x60;crate::saasy::plans&#x60;.  JSON contract (camelCase, matches the frontend): &#x60;plan&#x60;, &#x60;planName&#x60;, &#x60;priceEur&#x60;, &#x60;status&#x60;, &#x60;currentPeriodEnd&#x60;, &#x60;manageUrl&#x60;, &#x60;trialEndsAt&#x60;, &#x60;isTrialing&#x60;, &#x60;limits:{maxUsers,maxInvoicesPerMonth,maxConnectors}&#x60;, &#x60;usage:{users,invoicesThisMonth,connectors,overageSeats}&#x60;, &#x60;features:{taxAutomations,fancyReports,erp}&#x60;.

    SubscriptionOverview(;
        currentPeriodEnd=nothing,
        features=nothing,
        isTrialing=nothing,
        limits=nothing,
        manageUrl=nothing,
        plan=nothing,
        planName=nothing,
        priceEur=nothing,
        quantity=nothing,
        status=nothing,
        subscriptionId=nothing,
        trialEndsAt=nothing,
        usage=nothing,
    )

    - currentPeriodEnd::ZonedDateTime
    - features::PlanFeatures
    - isTrialing::Bool
    - limits::PlanLimits
    - manageUrl::String
    - plan::String : Resolved plan id (free/starter/business/enterprise, or a custom override id).
    - planName::String
    - priceEur::Float64 : Monthly price in EUR; &#x60;-1.0&#x60; &#x3D; custom pricing (enterprise).
    - quantity::Int64
    - status::String
    - subscriptionId::String
    - trialEndsAt::ZonedDateTime
    - usage::UsageSnapshot
"""
Base.@kwdef mutable struct SubscriptionOverview <: OpenAPI.APIModel
    currentPeriodEnd::Union{Nothing, ZonedDateTime} = nothing
    features = nothing # spec type: Union{ Nothing, PlanFeatures }
    isTrialing::Union{Nothing, Bool} = nothing
    limits = nothing # spec type: Union{ Nothing, PlanLimits }
    manageUrl::Union{Nothing, String} = nothing
    plan::Union{Nothing, String} = nothing
    planName::Union{Nothing, String} = nothing
    priceEur::Union{Nothing, Float64} = nothing
    quantity::Union{Nothing, Int64} = nothing
    status::Union{Nothing, String} = nothing
    subscriptionId::Union{Nothing, String} = nothing
    trialEndsAt::Union{Nothing, ZonedDateTime} = nothing
    usage = nothing # spec type: Union{ Nothing, UsageSnapshot }

    function SubscriptionOverview(currentPeriodEnd, features, isTrialing, limits, manageUrl, plan, planName, priceEur, quantity, status, subscriptionId, trialEndsAt, usage, )
        o = new(currentPeriodEnd, features, isTrialing, limits, manageUrl, plan, planName, priceEur, quantity, status, subscriptionId, trialEndsAt, usage, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SubscriptionOverview

const _property_types_SubscriptionOverview = Dict{Symbol,String}(Symbol("currentPeriodEnd")=>"ZonedDateTime", Symbol("features")=>"PlanFeatures", Symbol("isTrialing")=>"Bool", Symbol("limits")=>"PlanLimits", Symbol("manageUrl")=>"String", Symbol("plan")=>"String", Symbol("planName")=>"String", Symbol("priceEur")=>"Float64", Symbol("quantity")=>"Int64", Symbol("status")=>"String", Symbol("subscriptionId")=>"String", Symbol("trialEndsAt")=>"ZonedDateTime", Symbol("usage")=>"UsageSnapshot", )
OpenAPI.property_type(::Type{ SubscriptionOverview }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SubscriptionOverview[name]))}

function OpenAPI.check_required(o::SubscriptionOverview)
    o.features === nothing && (return false)
    o.isTrialing === nothing && (return false)
    o.limits === nothing && (return false)
    o.plan === nothing && (return false)
    o.planName === nothing && (return false)
    o.priceEur === nothing && (return false)
    o.usage === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SubscriptionOverview)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("currentPeriodEnd"), o.currentPeriodEnd)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("features"), o.features)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("isTrialing"), o.isTrialing)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("limits"), o.limits)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("manageUrl"), o.manageUrl)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("plan"), o.plan)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("planName"), o.planName)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("priceEur"), o.priceEur)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("quantity"), o.quantity)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("status"), o.status)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("subscriptionId"), o.subscriptionId)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("trialEndsAt"), o.trialEndsAt)
    OpenAPI.validate_property(SubscriptionOverview, Symbol("usage"), o.usage)
end

function OpenAPI.validate_property(::Type{ SubscriptionOverview }, name::Symbol, val)

    if name === Symbol("currentPeriodEnd")
        OpenAPI.validate_param(name, "SubscriptionOverview", :format, val, "date-time")
    end







    if name === Symbol("priceEur")
        OpenAPI.validate_param(name, "SubscriptionOverview", :format, val, "double")
    end

    if name === Symbol("quantity")
        OpenAPI.validate_param(name, "SubscriptionOverview", :format, val, "int32")
    end



    if name === Symbol("trialEndsAt")
        OpenAPI.validate_param(name, "SubscriptionOverview", :format, val, "date-time")
    end

end
