# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GezReport
Berechnungsergebnis des Rundfunkbeitrags für ein Unternehmen.

    GezReport(;
        beitragsfreie_kfz=nothing,
        beitragspflichtige_kfz=nothing,
        betriebsstaetten=nothing,
        hinweis=nothing,
        hotelzimmer_beitrag=nothing,
        jaehrlicher_beitrag=nothing,
        jahr=nothing,
        kfz_beitrag=nothing,
        monatlicher_beitrag=nothing,
        vierteljaehrlicher_beitrag=nothing,
    )

    - beitragsfreie_kfz::Int64
    - beitragspflichtige_kfz::Int64
    - betriebsstaetten::Vector{BetriebsstaettenDetail}
    - hinweis::String
    - hotelzimmer_beitrag::String
    - jaehrlicher_beitrag::String
    - jahr::Int64
    - kfz_beitrag::String
    - monatlicher_beitrag::String
    - vierteljaehrlicher_beitrag::String
"""
Base.@kwdef mutable struct GezReport <: OpenAPI.APIModel
    beitragsfreie_kfz::Union{Nothing, Int64} = nothing
    beitragspflichtige_kfz::Union{Nothing, Int64} = nothing
    betriebsstaetten::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{BetriebsstaettenDetail} }
    hinweis::Union{Nothing, String} = nothing
    hotelzimmer_beitrag::Union{Nothing, String} = nothing
    jaehrlicher_beitrag::Union{Nothing, String} = nothing
    jahr::Union{Nothing, Int64} = nothing
    kfz_beitrag::Union{Nothing, String} = nothing
    monatlicher_beitrag::Union{Nothing, String} = nothing
    vierteljaehrlicher_beitrag::Union{Nothing, String} = nothing

    function GezReport(beitragsfreie_kfz, beitragspflichtige_kfz, betriebsstaetten, hinweis, hotelzimmer_beitrag, jaehrlicher_beitrag, jahr, kfz_beitrag, monatlicher_beitrag, vierteljaehrlicher_beitrag, )
        o = new(beitragsfreie_kfz, beitragspflichtige_kfz, betriebsstaetten, hinweis, hotelzimmer_beitrag, jaehrlicher_beitrag, jahr, kfz_beitrag, monatlicher_beitrag, vierteljaehrlicher_beitrag, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type GezReport

const _property_types_GezReport = Dict{Symbol,String}(Symbol("beitragsfreie_kfz")=>"Int64", Symbol("beitragspflichtige_kfz")=>"Int64", Symbol("betriebsstaetten")=>"Vector{BetriebsstaettenDetail}", Symbol("hinweis")=>"String", Symbol("hotelzimmer_beitrag")=>"String", Symbol("jaehrlicher_beitrag")=>"String", Symbol("jahr")=>"Int64", Symbol("kfz_beitrag")=>"String", Symbol("monatlicher_beitrag")=>"String", Symbol("vierteljaehrlicher_beitrag")=>"String", )
OpenAPI.property_type(::Type{ GezReport }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GezReport[name]))}

function OpenAPI.check_required(o::GezReport)
    o.beitragsfreie_kfz === nothing && (return false)
    o.beitragspflichtige_kfz === nothing && (return false)
    o.betriebsstaetten === nothing && (return false)
    o.hinweis === nothing && (return false)
    o.hotelzimmer_beitrag === nothing && (return false)
    o.jaehrlicher_beitrag === nothing && (return false)
    o.jahr === nothing && (return false)
    o.kfz_beitrag === nothing && (return false)
    o.monatlicher_beitrag === nothing && (return false)
    o.vierteljaehrlicher_beitrag === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::GezReport)
    OpenAPI.validate_property(GezReport, Symbol("beitragsfreie_kfz"), o.beitragsfreie_kfz)
    OpenAPI.validate_property(GezReport, Symbol("beitragspflichtige_kfz"), o.beitragspflichtige_kfz)
    OpenAPI.validate_property(GezReport, Symbol("betriebsstaetten"), o.betriebsstaetten)
    OpenAPI.validate_property(GezReport, Symbol("hinweis"), o.hinweis)
    OpenAPI.validate_property(GezReport, Symbol("hotelzimmer_beitrag"), o.hotelzimmer_beitrag)
    OpenAPI.validate_property(GezReport, Symbol("jaehrlicher_beitrag"), o.jaehrlicher_beitrag)
    OpenAPI.validate_property(GezReport, Symbol("jahr"), o.jahr)
    OpenAPI.validate_property(GezReport, Symbol("kfz_beitrag"), o.kfz_beitrag)
    OpenAPI.validate_property(GezReport, Symbol("monatlicher_beitrag"), o.monatlicher_beitrag)
    OpenAPI.validate_property(GezReport, Symbol("vierteljaehrlicher_beitrag"), o.vierteljaehrlicher_beitrag)
end

function OpenAPI.validate_property(::Type{ GezReport }, name::Symbol, val)

    if name === Symbol("beitragsfreie_kfz")
        OpenAPI.validate_param(name, "GezReport", :format, val, "int64")
    end
    if name === Symbol("beitragsfreie_kfz")
        OpenAPI.validate_param(name, "GezReport", :minimum, val, 0, false)
    end

    if name === Symbol("beitragspflichtige_kfz")
        OpenAPI.validate_param(name, "GezReport", :format, val, "int64")
    end
    if name === Symbol("beitragspflichtige_kfz")
        OpenAPI.validate_param(name, "GezReport", :minimum, val, 0, false)
    end





    if name === Symbol("jahr")
        OpenAPI.validate_param(name, "GezReport", :format, val, "int32")
    end



end
