# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EksErgebnis

    EksErgebnis(;
        gesamtergebnis=nothing,
        monate=nothing,
        prognose_naechste_6_monate=nothing,
        summe_ausgaben=nothing,
        summe_einnahmen=nothing,
        zeitraum_bis=nothing,
        zeitraum_von=nothing,
    )

    - gesamtergebnis::String
    - monate::Vector{EksMonatsWert}
    - prognose_naechste_6_monate::String
    - summe_ausgaben::String
    - summe_einnahmen::String
    - zeitraum_bis::String
    - zeitraum_von::String
"""
Base.@kwdef mutable struct EksErgebnis <: OpenAPI.APIModel
    gesamtergebnis::Union{Nothing, String} = nothing
    monate::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{EksMonatsWert} }
    prognose_naechste_6_monate::Union{Nothing, String} = nothing
    summe_ausgaben::Union{Nothing, String} = nothing
    summe_einnahmen::Union{Nothing, String} = nothing
    zeitraum_bis::Union{Nothing, String} = nothing
    zeitraum_von::Union{Nothing, String} = nothing

    function EksErgebnis(gesamtergebnis, monate, prognose_naechste_6_monate, summe_ausgaben, summe_einnahmen, zeitraum_bis, zeitraum_von, )
        o = new(gesamtergebnis, monate, prognose_naechste_6_monate, summe_ausgaben, summe_einnahmen, zeitraum_bis, zeitraum_von, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EksErgebnis

const _property_types_EksErgebnis = Dict{Symbol,String}(Symbol("gesamtergebnis")=>"String", Symbol("monate")=>"Vector{EksMonatsWert}", Symbol("prognose_naechste_6_monate")=>"String", Symbol("summe_ausgaben")=>"String", Symbol("summe_einnahmen")=>"String", Symbol("zeitraum_bis")=>"String", Symbol("zeitraum_von")=>"String", )
OpenAPI.property_type(::Type{ EksErgebnis }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EksErgebnis[name]))}

function OpenAPI.check_required(o::EksErgebnis)
    o.gesamtergebnis === nothing && (return false)
    o.monate === nothing && (return false)
    o.prognose_naechste_6_monate === nothing && (return false)
    o.summe_ausgaben === nothing && (return false)
    o.summe_einnahmen === nothing && (return false)
    o.zeitraum_bis === nothing && (return false)
    o.zeitraum_von === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::EksErgebnis)
    OpenAPI.validate_property(EksErgebnis, Symbol("gesamtergebnis"), o.gesamtergebnis)
    OpenAPI.validate_property(EksErgebnis, Symbol("monate"), o.monate)
    OpenAPI.validate_property(EksErgebnis, Symbol("prognose_naechste_6_monate"), o.prognose_naechste_6_monate)
    OpenAPI.validate_property(EksErgebnis, Symbol("summe_ausgaben"), o.summe_ausgaben)
    OpenAPI.validate_property(EksErgebnis, Symbol("summe_einnahmen"), o.summe_einnahmen)
    OpenAPI.validate_property(EksErgebnis, Symbol("zeitraum_bis"), o.zeitraum_bis)
    OpenAPI.validate_property(EksErgebnis, Symbol("zeitraum_von"), o.zeitraum_von)
end

function OpenAPI.validate_property(::Type{ EksErgebnis }, name::Symbol, val)







end
