# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SupplierInvoiceStatusUpdate

    SupplierInvoiceStatusUpdate(;
        status=nothing,
    )

    - status::String
"""
Base.@kwdef mutable struct SupplierInvoiceStatusUpdate <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing

    function SupplierInvoiceStatusUpdate(status, )
        o = new(status, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SupplierInvoiceStatusUpdate

const _property_types_SupplierInvoiceStatusUpdate = Dict{Symbol,String}(Symbol("status")=>"String", )
OpenAPI.property_type(::Type{ SupplierInvoiceStatusUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SupplierInvoiceStatusUpdate[name]))}

function OpenAPI.check_required(o::SupplierInvoiceStatusUpdate)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SupplierInvoiceStatusUpdate)
    OpenAPI.validate_property(SupplierInvoiceStatusUpdate, Symbol("status"), o.status)
end

function OpenAPI.validate_property(::Type{ SupplierInvoiceStatusUpdate }, name::Symbol, val)

end
