# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UserProfile

    UserProfile(;
        created_at=nothing,
        email=nothing,
        email_verified=nothing,
        first_name=nothing,
        full_name=nothing,
        id=nothing,
        last_name=nothing,
    )

    - created_at::ZonedDateTime
    - email::String
    - email_verified::Bool
    - first_name::String
    - full_name::String
    - id::String
    - last_name::String
"""
Base.@kwdef mutable struct UserProfile <: OpenAPI.APIModel
    created_at::Union{Nothing, ZonedDateTime} = nothing
    email::Union{Nothing, String} = nothing
    email_verified::Union{Nothing, Bool} = nothing
    first_name::Union{Nothing, String} = nothing
    full_name::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing
    last_name::Union{Nothing, String} = nothing

    function UserProfile(created_at, email, email_verified, first_name, full_name, id, last_name, )
        o = new(created_at, email, email_verified, first_name, full_name, id, last_name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type UserProfile

const _property_types_UserProfile = Dict{Symbol,String}(Symbol("created_at")=>"ZonedDateTime", Symbol("email")=>"String", Symbol("email_verified")=>"Bool", Symbol("first_name")=>"String", Symbol("full_name")=>"String", Symbol("id")=>"String", Symbol("last_name")=>"String", )
OpenAPI.property_type(::Type{ UserProfile }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserProfile[name]))}

function OpenAPI.check_required(o::UserProfile)
    o.created_at === nothing && (return false)
    o.email === nothing && (return false)
    o.email_verified === nothing && (return false)
    o.first_name === nothing && (return false)
    o.full_name === nothing && (return false)
    o.id === nothing && (return false)
    o.last_name === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::UserProfile)
    OpenAPI.validate_property(UserProfile, Symbol("created_at"), o.created_at)
    OpenAPI.validate_property(UserProfile, Symbol("email"), o.email)
    OpenAPI.validate_property(UserProfile, Symbol("email_verified"), o.email_verified)
    OpenAPI.validate_property(UserProfile, Symbol("first_name"), o.first_name)
    OpenAPI.validate_property(UserProfile, Symbol("full_name"), o.full_name)
    OpenAPI.validate_property(UserProfile, Symbol("id"), o.id)
    OpenAPI.validate_property(UserProfile, Symbol("last_name"), o.last_name)
end

function OpenAPI.validate_property(::Type{ UserProfile }, name::Symbol, val)

    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "UserProfile", :format, val, "date-time")
    end





    if name === Symbol("id")
        OpenAPI.validate_param(name, "UserProfile", :format, val, "uuid")
    end

end
