# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SuitabilityRequest

    SuitabilityRequest(;
        customer_annual_volume=nothing,
        items=nothing,
        recipient=nothing,
        sender=nothing,
    )

    - customer_annual_volume::Int64
    - items::Vector{CartItemInput}
    - recipient::Address
    - sender::Address
"""
Base.@kwdef mutable struct SuitabilityRequest <: OpenAPI.APIModel
    customer_annual_volume::Union{Nothing, Int64} = nothing
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{CartItemInput} }
    recipient = nothing # spec type: Union{ Nothing, Address }
    sender = nothing # spec type: Union{ Nothing, Address }

    function SuitabilityRequest(customer_annual_volume, items, recipient, sender, )
        o = new(customer_annual_volume, items, recipient, sender, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type SuitabilityRequest

const _property_types_SuitabilityRequest = Dict{Symbol,String}(Symbol("customer_annual_volume")=>"Int64", Symbol("items")=>"Vector{CartItemInput}", Symbol("recipient")=>"Address", Symbol("sender")=>"Address", )
OpenAPI.property_type(::Type{ SuitabilityRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SuitabilityRequest[name]))}

function OpenAPI.check_required(o::SuitabilityRequest)
    o.items === nothing && (return false)
    o.recipient === nothing && (return false)
    o.sender === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::SuitabilityRequest)
    OpenAPI.validate_property(SuitabilityRequest, Symbol("customer_annual_volume"), o.customer_annual_volume)
    OpenAPI.validate_property(SuitabilityRequest, Symbol("items"), o.items)
    OpenAPI.validate_property(SuitabilityRequest, Symbol("recipient"), o.recipient)
    OpenAPI.validate_property(SuitabilityRequest, Symbol("sender"), o.sender)
end

function OpenAPI.validate_property(::Type{ SuitabilityRequest }, name::Symbol, val)

    if name === Symbol("customer_annual_volume")
        OpenAPI.validate_param(name, "SuitabilityRequest", :format, val, "int32")
    end
    if name === Symbol("customer_annual_volume")
        OpenAPI.validate_param(name, "SuitabilityRequest", :minimum, val, 0, false)
    end



end
