# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CategoryTotal

    CategoryTotal(;
        category_id=nothing,
        share_pct=nothing,
        tco2e=nothing,
    )

    - category_id::String
    - share_pct::Float64
    - tco2e::String
"""
Base.@kwdef mutable struct CategoryTotal <: OpenAPI.APIModel
    category_id::Union{Nothing, String} = nothing
    share_pct::Union{Nothing, Float64} = nothing
    tco2e::Union{Nothing, String} = nothing

    function CategoryTotal(category_id, share_pct, tco2e, )
        o = new(category_id, share_pct, tco2e, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type CategoryTotal

const _property_types_CategoryTotal = Dict{Symbol,String}(Symbol("category_id")=>"String", Symbol("share_pct")=>"Float64", Symbol("tco2e")=>"String", )
OpenAPI.property_type(::Type{ CategoryTotal }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CategoryTotal[name]))}

function OpenAPI.check_required(o::CategoryTotal)
    o.category_id === nothing && (return false)
    o.share_pct === nothing && (return false)
    o.tco2e === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::CategoryTotal)
    OpenAPI.validate_property(CategoryTotal, Symbol("category_id"), o.category_id)
    OpenAPI.validate_property(CategoryTotal, Symbol("share_pct"), o.share_pct)
    OpenAPI.validate_property(CategoryTotal, Symbol("tco2e"), o.tco2e)
end

function OpenAPI.validate_property(::Type{ CategoryTotal }, name::Symbol, val)


    if name === Symbol("share_pct")
        OpenAPI.validate_param(name, "CategoryTotal", :format, val, "double")
    end

end
