# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProductAttributeUpdate

    ProductAttributeUpdate(;
        isFilterable=nothing,
        name=nothing,
        position=nothing,
        productId=nothing,
        unit=nothing,
        value=nothing,
    )

    - isFilterable::Bool : Whether this attribute participates in the shop&#39;s faceted filters.
    - name::String : Attribute name, e.g. &#x60;Material&#x60;, &#x60;Farbe&#x60;, &#x60;Gewicht&#x60;.
    - position::Int64 : Ordering position within the product&#39;s attribute list.
    - productId::String : The product this attribute belongs to. References the product entity.
    - unit::String : Optional unit of measure for numeric attributes, e.g. &#x60;g&#x60;, &#x60;cm&#x60;.
    - value::String : Attribute value, e.g. &#x60;Baumwolle&#x60;, &#x60;Rot&#x60;, &#x60;180g&#x60;.
"""
Base.@kwdef mutable struct ProductAttributeUpdate <: OpenAPI.APIModel
    isFilterable::Union{Nothing, Bool} = nothing
    name::Union{Nothing, String} = nothing
    position::Union{Nothing, Int64} = nothing
    productId::Union{Nothing, String} = nothing
    unit::Union{Nothing, String} = nothing
    value::Union{Nothing, String} = nothing

    function ProductAttributeUpdate(isFilterable, name, position, productId, unit, value, )
        o = new(isFilterable, name, position, productId, unit, value, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ProductAttributeUpdate

const _property_types_ProductAttributeUpdate = Dict{Symbol,String}(Symbol("isFilterable")=>"Bool", Symbol("name")=>"String", Symbol("position")=>"Int64", Symbol("productId")=>"String", Symbol("unit")=>"String", Symbol("value")=>"String", )
OpenAPI.property_type(::Type{ ProductAttributeUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductAttributeUpdate[name]))}

function OpenAPI.check_required(o::ProductAttributeUpdate)
    true
end

function OpenAPI.validate_properties(o::ProductAttributeUpdate)
    OpenAPI.validate_property(ProductAttributeUpdate, Symbol("isFilterable"), o.isFilterable)
    OpenAPI.validate_property(ProductAttributeUpdate, Symbol("name"), o.name)
    OpenAPI.validate_property(ProductAttributeUpdate, Symbol("position"), o.position)
    OpenAPI.validate_property(ProductAttributeUpdate, Symbol("productId"), o.productId)
    OpenAPI.validate_property(ProductAttributeUpdate, Symbol("unit"), o.unit)
    OpenAPI.validate_property(ProductAttributeUpdate, Symbol("value"), o.value)
end

function OpenAPI.validate_property(::Type{ ProductAttributeUpdate }, name::Symbol, val)


    if name === Symbol("name")
        OpenAPI.validate_param(name, "ProductAttributeUpdate", :minLength, val, 1)
    end

    if name === Symbol("position")
        OpenAPI.validate_param(name, "ProductAttributeUpdate", :format, val, "int32")
    end

    if name === Symbol("productId")
        OpenAPI.validate_param(name, "ProductAttributeUpdate", :format, val, "uuid")
    end


    if name === Symbol("value")
        OpenAPI.validate_param(name, "ProductAttributeUpdate", :minLength, val, 1)
    end
end
