# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TrainingContent

    TrainingContent(;
        code=nothing,
        contact=nothing,
        passScore=nothing,
        quiz=nothing,
        sections=nothing,
        title=nothing,
        titleEn=nothing,
    )

    - code::String
    - contact::ContactInfo
    - passScore::Int64
    - quiz::Vector{QuizQuestion}
    - sections::Vector{Section}
    - title::String
    - titleEn::String
"""
Base.@kwdef mutable struct TrainingContent <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    contact = nothing # spec type: Union{ Nothing, ContactInfo }
    passScore::Union{Nothing, Int64} = nothing
    quiz::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{QuizQuestion} }
    sections::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Section} }
    title::Union{Nothing, String} = nothing
    titleEn::Union{Nothing, String} = nothing

    function TrainingContent(code, contact, passScore, quiz, sections, title, titleEn, )
        o = new(code, contact, passScore, quiz, sections, title, titleEn, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TrainingContent

const _property_types_TrainingContent = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("contact")=>"ContactInfo", Symbol("passScore")=>"Int64", Symbol("quiz")=>"Vector{QuizQuestion}", Symbol("sections")=>"Vector{Section}", Symbol("title")=>"String", Symbol("titleEn")=>"String", )
OpenAPI.property_type(::Type{ TrainingContent }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TrainingContent[name]))}

function OpenAPI.check_required(o::TrainingContent)
    o.code === nothing && (return false)
    o.contact === nothing && (return false)
    o.passScore === nothing && (return false)
    o.quiz === nothing && (return false)
    o.sections === nothing && (return false)
    o.title === nothing && (return false)
    o.titleEn === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TrainingContent)
    OpenAPI.validate_property(TrainingContent, Symbol("code"), o.code)
    OpenAPI.validate_property(TrainingContent, Symbol("contact"), o.contact)
    OpenAPI.validate_property(TrainingContent, Symbol("passScore"), o.passScore)
    OpenAPI.validate_property(TrainingContent, Symbol("quiz"), o.quiz)
    OpenAPI.validate_property(TrainingContent, Symbol("sections"), o.sections)
    OpenAPI.validate_property(TrainingContent, Symbol("title"), o.title)
    OpenAPI.validate_property(TrainingContent, Symbol("titleEn"), o.titleEn)
end

function OpenAPI.validate_property(::Type{ TrainingContent }, name::Symbol, val)



    if name === Symbol("passScore")
        OpenAPI.validate_param(name, "TrainingContent", :format, val, "int32")
    end




end
