# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""InstituteProfileUpdate
Partial update of the institute profile.

    InstituteProfileUpdate(;
        instituteType=nothing,
        kapitalmarktorientiert=nothing,
    )

    - instituteType::String
    - kapitalmarktorientiert::Bool
"""
Base.@kwdef mutable struct InstituteProfileUpdate <: OpenAPI.APIModel
    instituteType::Union{Nothing, String} = nothing
    kapitalmarktorientiert::Union{Nothing, Bool} = nothing

    function InstituteProfileUpdate(instituteType, kapitalmarktorientiert, )
        o = new(instituteType, kapitalmarktorientiert, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type InstituteProfileUpdate

const _property_types_InstituteProfileUpdate = Dict{Symbol,String}(Symbol("instituteType")=>"String", Symbol("kapitalmarktorientiert")=>"Bool", )
OpenAPI.property_type(::Type{ InstituteProfileUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InstituteProfileUpdate[name]))}

function OpenAPI.check_required(o::InstituteProfileUpdate)
    true
end

function OpenAPI.validate_properties(o::InstituteProfileUpdate)
    OpenAPI.validate_property(InstituteProfileUpdate, Symbol("instituteType"), o.instituteType)
    OpenAPI.validate_property(InstituteProfileUpdate, Symbol("kapitalmarktorientiert"), o.kapitalmarktorientiert)
end

function OpenAPI.validate_property(::Type{ InstituteProfileUpdate }, name::Symbol, val)


end
