# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""DeliveryDateUpdate

    DeliveryDateUpdate(;
        customerId=nothing,
        fulfilledDate=nothing,
        note=nothing,
        orderNumber=nothing,
        originalDate=nothing,
        productId=nothing,
        promisedDate=nothing,
        status=nothing,
    )

    - customerId::String : References the customer entity.
    - fulfilledDate::Date : Date actually delivered (set on fulfillment).
    - note::String
    - orderNumber::String : Sales order number (&#x60;order.order_number&#x60;).
    - originalDate::Date : Original date promised before rescheduling.
    - productId::String : Product line item this date applies to, if per-item. References the product entity.
    - promisedDate::Date : Date promised to the customer.
    - status::DeliveryDateStatus : One of: promised | confirmed | rescheduled | fulfilled | late | cancelled
"""
Base.@kwdef mutable struct DeliveryDateUpdate <: OpenAPI.APIModel
    customerId::Union{Nothing, String} = nothing
    fulfilledDate::Union{Nothing, Date} = nothing
    note::Union{Nothing, String} = nothing
    orderNumber::Union{Nothing, String} = nothing
    originalDate::Union{Nothing, Date} = nothing
    productId::Union{Nothing, String} = nothing
    promisedDate::Union{Nothing, Date} = nothing
    status = nothing # spec type: Union{ Nothing, DeliveryDateStatus }

    function DeliveryDateUpdate(customerId, fulfilledDate, note, orderNumber, originalDate, productId, promisedDate, status, )
        o = new(customerId, fulfilledDate, note, orderNumber, originalDate, productId, promisedDate, status, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type DeliveryDateUpdate

const _property_types_DeliveryDateUpdate = Dict{Symbol,String}(Symbol("customerId")=>"String", Symbol("fulfilledDate")=>"Date", Symbol("note")=>"String", Symbol("orderNumber")=>"String", Symbol("originalDate")=>"Date", Symbol("productId")=>"String", Symbol("promisedDate")=>"Date", Symbol("status")=>"DeliveryDateStatus", )
OpenAPI.property_type(::Type{ DeliveryDateUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DeliveryDateUpdate[name]))}

function OpenAPI.check_required(o::DeliveryDateUpdate)
    true
end

function OpenAPI.validate_properties(o::DeliveryDateUpdate)
    OpenAPI.validate_property(DeliveryDateUpdate, Symbol("customerId"), o.customerId)
    OpenAPI.validate_property(DeliveryDateUpdate, Symbol("fulfilledDate"), o.fulfilledDate)
    OpenAPI.validate_property(DeliveryDateUpdate, Symbol("note"), o.note)
    OpenAPI.validate_property(DeliveryDateUpdate, Symbol("orderNumber"), o.orderNumber)
    OpenAPI.validate_property(DeliveryDateUpdate, Symbol("originalDate"), o.originalDate)
    OpenAPI.validate_property(DeliveryDateUpdate, Symbol("productId"), o.productId)
    OpenAPI.validate_property(DeliveryDateUpdate, Symbol("promisedDate"), o.promisedDate)
    OpenAPI.validate_property(DeliveryDateUpdate, Symbol("status"), o.status)
end

function OpenAPI.validate_property(::Type{ DeliveryDateUpdate }, name::Symbol, val)


    if name === Symbol("fulfilledDate")
        OpenAPI.validate_param(name, "DeliveryDateUpdate", :format, val, "date")
    end



    if name === Symbol("originalDate")
        OpenAPI.validate_param(name, "DeliveryDateUpdate", :format, val, "date")
    end


    if name === Symbol("promisedDate")
        OpenAPI.validate_param(name, "DeliveryDateUpdate", :format, val, "date")
    end

end
