# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PluginError_oneOf_1

    PluginErrorOneOf1(;
        NotFound=nothing,
    )

    - NotFound::Vector{Any}
"""
Base.@kwdef mutable struct PluginErrorOneOf1 <: OpenAPI.APIModel
    NotFound::Union{Nothing, Vector{Any}} = nothing

    function PluginErrorOneOf1(NotFound, )
        o = new(NotFound, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PluginErrorOneOf1

const _property_types_PluginErrorOneOf1 = Dict{Symbol,String}(Symbol("NotFound")=>"Vector{Any}", )
OpenAPI.property_type(::Type{ PluginErrorOneOf1 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PluginErrorOneOf1[name]))}

function OpenAPI.check_required(o::PluginErrorOneOf1)
    o.NotFound === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PluginErrorOneOf1)
    OpenAPI.validate_property(PluginErrorOneOf1, Symbol("NotFound"), o.NotFound)
end

function OpenAPI.validate_property(::Type{ PluginErrorOneOf1 }, name::Symbol, val)

    if name === Symbol("NotFound")
        OpenAPI.validate_param(name, "PluginErrorOneOf1", :maxItems, val, 2)
        OpenAPI.validate_param(name, "PluginErrorOneOf1", :minItems, val, 2)
    end
end
