# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""InviteRequest

    InviteRequest(;
        email=nothing,
    )

    - email::String
"""
Base.@kwdef mutable struct InviteRequest <: OpenAPI.APIModel
    email::Union{Nothing, String} = nothing

    function InviteRequest(email, )
        o = new(email, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type InviteRequest

const _property_types_InviteRequest = Dict{Symbol,String}(Symbol("email")=>"String", )
OpenAPI.property_type(::Type{ InviteRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InviteRequest[name]))}

function OpenAPI.check_required(o::InviteRequest)
    o.email === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::InviteRequest)
    OpenAPI.validate_property(InviteRequest, Symbol("email"), o.email)
end

function OpenAPI.validate_property(::Type{ InviteRequest }, name::Symbol, val)

end
