# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AcceptInviteRequest

    AcceptInviteRequest(;
        first_name=nothing,
        last_name=nothing,
        password=nothing,
        privacy_accepted=nothing,
        token=nothing,
    )

    - first_name::String
    - last_name::String
    - password::String
    - privacy_accepted::Bool : GDPR consent — rejected unless true.
    - token::String
"""
Base.@kwdef mutable struct AcceptInviteRequest <: OpenAPI.APIModel
    first_name::Union{Nothing, String} = nothing
    last_name::Union{Nothing, String} = nothing
    password::Union{Nothing, String} = nothing
    privacy_accepted::Union{Nothing, Bool} = nothing
    token::Union{Nothing, String} = nothing

    function AcceptInviteRequest(first_name, last_name, password, privacy_accepted, token, )
        o = new(first_name, last_name, password, privacy_accepted, token, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AcceptInviteRequest

const _property_types_AcceptInviteRequest = Dict{Symbol,String}(Symbol("first_name")=>"String", Symbol("last_name")=>"String", Symbol("password")=>"String", Symbol("privacy_accepted")=>"Bool", Symbol("token")=>"String", )
OpenAPI.property_type(::Type{ AcceptInviteRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AcceptInviteRequest[name]))}

function OpenAPI.check_required(o::AcceptInviteRequest)
    o.first_name === nothing && (return false)
    o.last_name === nothing && (return false)
    o.password === nothing && (return false)
    o.privacy_accepted === nothing && (return false)
    o.token === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::AcceptInviteRequest)
    OpenAPI.validate_property(AcceptInviteRequest, Symbol("first_name"), o.first_name)
    OpenAPI.validate_property(AcceptInviteRequest, Symbol("last_name"), o.last_name)
    OpenAPI.validate_property(AcceptInviteRequest, Symbol("password"), o.password)
    OpenAPI.validate_property(AcceptInviteRequest, Symbol("privacy_accepted"), o.privacy_accepted)
    OpenAPI.validate_property(AcceptInviteRequest, Symbol("token"), o.token)
end

function OpenAPI.validate_property(::Type{ AcceptInviteRequest }, name::Symbol, val)





end
