# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EuerErgebnis

    EuerErgebnis(;
        anlage_zugaenge=nothing,
        gewinn_verlust=nothing,
        jahr=nothing,
        summe_ausgaben=nothing,
        summe_einnahmen=nothing,
        zeilen=nothing,
    )

    - anlage_zugaenge::String
    - gewinn_verlust::String
    - jahr::Int64
    - summe_ausgaben::String
    - summe_einnahmen::String
    - zeilen::Vector{EuerZeile}
"""
Base.@kwdef mutable struct EuerErgebnis <: OpenAPI.APIModel
    anlage_zugaenge::Union{Nothing, String} = nothing
    gewinn_verlust::Union{Nothing, String} = nothing
    jahr::Union{Nothing, Int64} = nothing
    summe_ausgaben::Union{Nothing, String} = nothing
    summe_einnahmen::Union{Nothing, String} = nothing
    zeilen::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{EuerZeile} }

    function EuerErgebnis(anlage_zugaenge, gewinn_verlust, jahr, summe_ausgaben, summe_einnahmen, zeilen, )
        o = new(anlage_zugaenge, gewinn_verlust, jahr, summe_ausgaben, summe_einnahmen, zeilen, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type EuerErgebnis

const _property_types_EuerErgebnis = Dict{Symbol,String}(Symbol("anlage_zugaenge")=>"String", Symbol("gewinn_verlust")=>"String", Symbol("jahr")=>"Int64", Symbol("summe_ausgaben")=>"String", Symbol("summe_einnahmen")=>"String", Symbol("zeilen")=>"Vector{EuerZeile}", )
OpenAPI.property_type(::Type{ EuerErgebnis }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EuerErgebnis[name]))}

function OpenAPI.check_required(o::EuerErgebnis)
    o.anlage_zugaenge === nothing && (return false)
    o.gewinn_verlust === nothing && (return false)
    o.jahr === nothing && (return false)
    o.summe_ausgaben === nothing && (return false)
    o.summe_einnahmen === nothing && (return false)
    o.zeilen === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::EuerErgebnis)
    OpenAPI.validate_property(EuerErgebnis, Symbol("anlage_zugaenge"), o.anlage_zugaenge)
    OpenAPI.validate_property(EuerErgebnis, Symbol("gewinn_verlust"), o.gewinn_verlust)
    OpenAPI.validate_property(EuerErgebnis, Symbol("jahr"), o.jahr)
    OpenAPI.validate_property(EuerErgebnis, Symbol("summe_ausgaben"), o.summe_ausgaben)
    OpenAPI.validate_property(EuerErgebnis, Symbol("summe_einnahmen"), o.summe_einnahmen)
    OpenAPI.validate_property(EuerErgebnis, Symbol("zeilen"), o.zeilen)
end

function OpenAPI.validate_property(::Type{ EuerErgebnis }, name::Symbol, val)



    if name === Symbol("jahr")
        OpenAPI.validate_param(name, "EuerErgebnis", :format, val, "int32")
    end



end
