# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ApiResponse_Vec_UserTenantInfo

    ApiResponseVecUserTenantInfo(;
        data=nothing,
        error=nothing,
        message=nothing,
        success=nothing,
    )

    - data::Vector{ApiResponseVecUserTenantInfoDataInner}
    - error::String
    - message::String
    - success::Bool
"""
Base.@kwdef mutable struct ApiResponseVecUserTenantInfo <: OpenAPI.APIModel
    data::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ApiResponseVecUserTenantInfoDataInner} }
    error::Union{Nothing, String} = nothing
    message::Union{Nothing, String} = nothing
    success::Union{Nothing, Bool} = nothing

    function ApiResponseVecUserTenantInfo(data, error, message, success, )
        o = new(data, error, message, success, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ApiResponseVecUserTenantInfo

const _property_types_ApiResponseVecUserTenantInfo = Dict{Symbol,String}(Symbol("data")=>"Vector{ApiResponseVecUserTenantInfoDataInner}", Symbol("error")=>"String", Symbol("message")=>"String", Symbol("success")=>"Bool", )
OpenAPI.property_type(::Type{ ApiResponseVecUserTenantInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ApiResponseVecUserTenantInfo[name]))}

function OpenAPI.check_required(o::ApiResponseVecUserTenantInfo)
    o.success === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ApiResponseVecUserTenantInfo)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfo, Symbol("data"), o.data)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfo, Symbol("error"), o.error)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfo, Symbol("message"), o.message)
    OpenAPI.validate_property(ApiResponseVecUserTenantInfo, Symbol("success"), o.success)
end

function OpenAPI.validate_property(::Type{ ApiResponseVecUserTenantInfo }, name::Symbol, val)




end
