# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Verfahrensdokumentation

    Verfahrensdokumentation(;
        entries=nothing,
        generated_at=nothing,
        title=nothing,
        version=nothing,
    )

    - entries::Vector{ComplianceEntry}
    - generated_at::String
    - title::String
    - version::String
"""
Base.@kwdef mutable struct Verfahrensdokumentation <: OpenAPI.APIModel
    entries::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ComplianceEntry} }
    generated_at::Union{Nothing, String} = nothing
    title::Union{Nothing, String} = nothing
    version::Union{Nothing, String} = nothing

    function Verfahrensdokumentation(entries, generated_at, title, version, )
        o = new(entries, generated_at, title, version, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Verfahrensdokumentation

const _property_types_Verfahrensdokumentation = Dict{Symbol,String}(Symbol("entries")=>"Vector{ComplianceEntry}", Symbol("generated_at")=>"String", Symbol("title")=>"String", Symbol("version")=>"String", )
OpenAPI.property_type(::Type{ Verfahrensdokumentation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Verfahrensdokumentation[name]))}

function OpenAPI.check_required(o::Verfahrensdokumentation)
    o.entries === nothing && (return false)
    o.generated_at === nothing && (return false)
    o.title === nothing && (return false)
    o.version === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Verfahrensdokumentation)
    OpenAPI.validate_property(Verfahrensdokumentation, Symbol("entries"), o.entries)
    OpenAPI.validate_property(Verfahrensdokumentation, Symbol("generated_at"), o.generated_at)
    OpenAPI.validate_property(Verfahrensdokumentation, Symbol("title"), o.title)
    OpenAPI.validate_property(Verfahrensdokumentation, Symbol("version"), o.version)
end

function OpenAPI.validate_property(::Type{ Verfahrensdokumentation }, name::Symbol, val)




end
