# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Payment

    Payment(;
        amount=nothing,
        attachment=nothing,
        currency=nothing,
        customerId=nothing,
        description=nothing,
        metadata=nothing,
        method=nothing,
        paymentDate=nothing,
        reference=nothing,
    )

    - amount::String
    - attachment::Any
    - currency::String
    - customerId::String : References the customer entity.
    - description::String
    - metadata::Any
    - method::PaymentMethod
    - paymentDate::ZonedDateTime
    - reference::String
"""
Base.@kwdef mutable struct Payment <: OpenAPI.APIModel
    amount::Union{Nothing, String} = nothing
    attachment::Union{Nothing, Any} = nothing
    currency::Union{Nothing, String} = nothing
    customerId::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    metadata::Union{Nothing, Any} = nothing
    method = nothing # spec type: Union{ Nothing, PaymentMethod }
    paymentDate::Union{Nothing, ZonedDateTime} = nothing
    reference::Union{Nothing, String} = nothing

    function Payment(amount, attachment, currency, customerId, description, metadata, method, paymentDate, reference, )
        o = new(amount, attachment, currency, customerId, description, metadata, method, paymentDate, reference, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Payment

const _property_types_Payment = Dict{Symbol,String}(Symbol("amount")=>"String", Symbol("attachment")=>"Any", Symbol("currency")=>"String", Symbol("customerId")=>"String", Symbol("description")=>"String", Symbol("metadata")=>"Any", Symbol("method")=>"PaymentMethod", Symbol("paymentDate")=>"ZonedDateTime", Symbol("reference")=>"String", )
OpenAPI.property_type(::Type{ Payment }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Payment[name]))}

function OpenAPI.check_required(o::Payment)
    true
end

function OpenAPI.validate_properties(o::Payment)
    OpenAPI.validate_property(Payment, Symbol("amount"), o.amount)
    OpenAPI.validate_property(Payment, Symbol("attachment"), o.attachment)
    OpenAPI.validate_property(Payment, Symbol("currency"), o.currency)
    OpenAPI.validate_property(Payment, Symbol("customerId"), o.customerId)
    OpenAPI.validate_property(Payment, Symbol("description"), o.description)
    OpenAPI.validate_property(Payment, Symbol("metadata"), o.metadata)
    OpenAPI.validate_property(Payment, Symbol("method"), o.method)
    OpenAPI.validate_property(Payment, Symbol("paymentDate"), o.paymentDate)
    OpenAPI.validate_property(Payment, Symbol("reference"), o.reference)
end

function OpenAPI.validate_property(::Type{ Payment }, name::Symbol, val)








    if name === Symbol("paymentDate")
        OpenAPI.validate_param(name, "Payment", :format, val, "date-time")
    end

end
