# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RfqCreate

    RfqCreate(;
        currency=nothing,
        lineItems=nothing,
        notes=nothing,
        requestedDate=nothing,
        responseDate=nothing,
        rfqNumber=nothing,
        status=nothing,
        supplierContactId=nothing,
        supplierName=nothing,
    )

    - currency::String
    - lineItems::Any : JSON array of &#x60;{product_id, name, sku, quantity, requested_unit_price?, quoted_unit_price?}&#x60;.
    - notes::String
    - requestedDate::Date
    - responseDate::Date
    - rfqNumber::String
    - status::RfqStatus : One of: draft | sent | offer_received | rejected | converted
    - supplierContactId::String : References the supplier entity.
    - supplierName::String
"""
Base.@kwdef mutable struct RfqCreate <: OpenAPI.APIModel
    currency::Union{Nothing, String} = nothing
    lineItems::Union{Nothing, Any} = nothing
    notes::Union{Nothing, String} = nothing
    requestedDate::Union{Nothing, Date} = nothing
    responseDate::Union{Nothing, Date} = nothing
    rfqNumber::Union{Nothing, String} = nothing
    status = nothing # spec type: Union{ Nothing, RfqStatus }
    supplierContactId::Union{Nothing, String} = nothing
    supplierName::Union{Nothing, String} = nothing

    function RfqCreate(currency, lineItems, notes, requestedDate, responseDate, rfqNumber, status, supplierContactId, supplierName, )
        o = new(currency, lineItems, notes, requestedDate, responseDate, rfqNumber, status, supplierContactId, supplierName, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RfqCreate

const _property_types_RfqCreate = Dict{Symbol,String}(Symbol("currency")=>"String", Symbol("lineItems")=>"Any", Symbol("notes")=>"String", Symbol("requestedDate")=>"Date", Symbol("responseDate")=>"Date", Symbol("rfqNumber")=>"String", Symbol("status")=>"RfqStatus", Symbol("supplierContactId")=>"String", Symbol("supplierName")=>"String", )
OpenAPI.property_type(::Type{ RfqCreate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RfqCreate[name]))}

function OpenAPI.check_required(o::RfqCreate)
    o.lineItems === nothing && (return false)
    o.requestedDate === nothing && (return false)
    o.rfqNumber === nothing && (return false)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::RfqCreate)
    OpenAPI.validate_property(RfqCreate, Symbol("currency"), o.currency)
    OpenAPI.validate_property(RfqCreate, Symbol("lineItems"), o.lineItems)
    OpenAPI.validate_property(RfqCreate, Symbol("notes"), o.notes)
    OpenAPI.validate_property(RfqCreate, Symbol("requestedDate"), o.requestedDate)
    OpenAPI.validate_property(RfqCreate, Symbol("responseDate"), o.responseDate)
    OpenAPI.validate_property(RfqCreate, Symbol("rfqNumber"), o.rfqNumber)
    OpenAPI.validate_property(RfqCreate, Symbol("status"), o.status)
    OpenAPI.validate_property(RfqCreate, Symbol("supplierContactId"), o.supplierContactId)
    OpenAPI.validate_property(RfqCreate, Symbol("supplierName"), o.supplierName)
end

function OpenAPI.validate_property(::Type{ RfqCreate }, name::Symbol, val)




    if name === Symbol("requestedDate")
        OpenAPI.validate_param(name, "RfqCreate", :format, val, "date")
    end

    if name === Symbol("responseDate")
        OpenAPI.validate_param(name, "RfqCreate", :format, val, "date")
    end




end
