# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WebhookEvent

    WebhookEvent(;
        attempts=nothing,
        channel=nothing,
        direction=nothing,
        eventType=nothing,
        lastError=nothing,
        payload=nothing,
        status=nothing,
    )

    - attempts::Int64
    - channel::String : source for inbound, target URL for outbound.
    - direction::WebhookDirection : inbound | outbound
    - eventType::String
    - lastError::String
    - payload::Any
    - status::WebhookEventStatus : accepted | delivered | failed
"""
Base.@kwdef mutable struct WebhookEvent <: OpenAPI.APIModel
    attempts::Union{Nothing, Int64} = nothing
    channel::Union{Nothing, String} = nothing
    direction = nothing # spec type: Union{ Nothing, WebhookDirection }
    eventType::Union{Nothing, String} = nothing
    lastError::Union{Nothing, String} = nothing
    payload::Union{Nothing, Any} = nothing
    status = nothing # spec type: Union{ Nothing, WebhookEventStatus }

    function WebhookEvent(attempts, channel, direction, eventType, lastError, payload, status, )
        o = new(attempts, channel, direction, eventType, lastError, payload, status, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type WebhookEvent

const _property_types_WebhookEvent = Dict{Symbol,String}(Symbol("attempts")=>"Int64", Symbol("channel")=>"String", Symbol("direction")=>"WebhookDirection", Symbol("eventType")=>"String", Symbol("lastError")=>"String", Symbol("payload")=>"Any", Symbol("status")=>"WebhookEventStatus", )
OpenAPI.property_type(::Type{ WebhookEvent }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WebhookEvent[name]))}

function OpenAPI.check_required(o::WebhookEvent)
    o.direction === nothing && (return false)
    o.eventType === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::WebhookEvent)
    OpenAPI.validate_property(WebhookEvent, Symbol("attempts"), o.attempts)
    OpenAPI.validate_property(WebhookEvent, Symbol("channel"), o.channel)
    OpenAPI.validate_property(WebhookEvent, Symbol("direction"), o.direction)
    OpenAPI.validate_property(WebhookEvent, Symbol("eventType"), o.eventType)
    OpenAPI.validate_property(WebhookEvent, Symbol("lastError"), o.lastError)
    OpenAPI.validate_property(WebhookEvent, Symbol("payload"), o.payload)
    OpenAPI.validate_property(WebhookEvent, Symbol("status"), o.status)
end

function OpenAPI.validate_property(::Type{ WebhookEvent }, name::Symbol, val)

    if name === Symbol("attempts")
        OpenAPI.validate_param(name, "WebhookEvent", :format, val, "int32")
    end






end
