# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ReturnWarehouseSummary
Aggregation for a single warehouse.

    ReturnWarehouseSummary(;
        itemsRestocked=nothing,
        itemsScrapped=nothing,
        returns=nothing,
        warehouseId=nothing,
    )

    - itemsRestocked::Int64
    - itemsScrapped::Int64
    - returns::Int64
    - warehouseId::String
"""
Base.@kwdef mutable struct ReturnWarehouseSummary <: OpenAPI.APIModel
    itemsRestocked::Union{Nothing, Int64} = nothing
    itemsScrapped::Union{Nothing, Int64} = nothing
    returns::Union{Nothing, Int64} = nothing
    warehouseId::Union{Nothing, String} = nothing

    function ReturnWarehouseSummary(itemsRestocked, itemsScrapped, returns, warehouseId, )
        o = new(itemsRestocked, itemsScrapped, returns, warehouseId, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ReturnWarehouseSummary

const _property_types_ReturnWarehouseSummary = Dict{Symbol,String}(Symbol("itemsRestocked")=>"Int64", Symbol("itemsScrapped")=>"Int64", Symbol("returns")=>"Int64", Symbol("warehouseId")=>"String", )
OpenAPI.property_type(::Type{ ReturnWarehouseSummary }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ReturnWarehouseSummary[name]))}

function OpenAPI.check_required(o::ReturnWarehouseSummary)
    o.itemsRestocked === nothing && (return false)
    o.itemsScrapped === nothing && (return false)
    o.returns === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ReturnWarehouseSummary)
    OpenAPI.validate_property(ReturnWarehouseSummary, Symbol("itemsRestocked"), o.itemsRestocked)
    OpenAPI.validate_property(ReturnWarehouseSummary, Symbol("itemsScrapped"), o.itemsScrapped)
    OpenAPI.validate_property(ReturnWarehouseSummary, Symbol("returns"), o.returns)
    OpenAPI.validate_property(ReturnWarehouseSummary, Symbol("warehouseId"), o.warehouseId)
end

function OpenAPI.validate_property(::Type{ ReturnWarehouseSummary }, name::Symbol, val)

    if name === Symbol("itemsRestocked")
        OpenAPI.validate_param(name, "ReturnWarehouseSummary", :format, val, "int64")
    end

    if name === Symbol("itemsScrapped")
        OpenAPI.validate_param(name, "ReturnWarehouseSummary", :format, val, "int64")
    end

    if name === Symbol("returns")
        OpenAPI.validate_param(name, "ReturnWarehouseSummary", :format, val, "int64")
    end
    if name === Symbol("returns")
        OpenAPI.validate_param(name, "ReturnWarehouseSummary", :minimum, val, 0, false)
    end

end
