# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Automation

    Automation(;
        automationKey=nothing,
        config=nothing,
        createdAt=nothing,
        enabled=nothing,
        lastRunAt=nothing,
        nextRunAt=nothing,
        tenantId=nothing,
        updatedAt=nothing,
    )

    - automationKey::String
    - config::Any
    - createdAt::ZonedDateTime
    - enabled::Bool
    - lastRunAt::ZonedDateTime
    - nextRunAt::ZonedDateTime
    - tenantId::String
    - updatedAt::ZonedDateTime
"""
Base.@kwdef mutable struct Automation <: OpenAPI.APIModel
    automationKey::Union{Nothing, String} = nothing
    config::Union{Nothing, Any} = nothing
    createdAt::Union{Nothing, ZonedDateTime} = nothing
    enabled::Union{Nothing, Bool} = nothing
    lastRunAt::Union{Nothing, ZonedDateTime} = nothing
    nextRunAt::Union{Nothing, ZonedDateTime} = nothing
    tenantId::Union{Nothing, String} = nothing
    updatedAt::Union{Nothing, ZonedDateTime} = nothing

    function Automation(automationKey, config, createdAt, enabled, lastRunAt, nextRunAt, tenantId, updatedAt, )
        o = new(automationKey, config, createdAt, enabled, lastRunAt, nextRunAt, tenantId, updatedAt, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Automation

const _property_types_Automation = Dict{Symbol,String}(Symbol("automationKey")=>"String", Symbol("config")=>"Any", Symbol("createdAt")=>"ZonedDateTime", Symbol("enabled")=>"Bool", Symbol("lastRunAt")=>"ZonedDateTime", Symbol("nextRunAt")=>"ZonedDateTime", Symbol("tenantId")=>"String", Symbol("updatedAt")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ Automation }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Automation[name]))}

function OpenAPI.check_required(o::Automation)
    o.automationKey === nothing && (return false)
    o.config === nothing && (return false)
    o.createdAt === nothing && (return false)
    o.enabled === nothing && (return false)
    o.tenantId === nothing && (return false)
    o.updatedAt === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Automation)
    OpenAPI.validate_property(Automation, Symbol("automationKey"), o.automationKey)
    OpenAPI.validate_property(Automation, Symbol("config"), o.config)
    OpenAPI.validate_property(Automation, Symbol("createdAt"), o.createdAt)
    OpenAPI.validate_property(Automation, Symbol("enabled"), o.enabled)
    OpenAPI.validate_property(Automation, Symbol("lastRunAt"), o.lastRunAt)
    OpenAPI.validate_property(Automation, Symbol("nextRunAt"), o.nextRunAt)
    OpenAPI.validate_property(Automation, Symbol("tenantId"), o.tenantId)
    OpenAPI.validate_property(Automation, Symbol("updatedAt"), o.updatedAt)
end

function OpenAPI.validate_property(::Type{ Automation }, name::Symbol, val)



    if name === Symbol("createdAt")
        OpenAPI.validate_param(name, "Automation", :format, val, "date-time")
    end


    if name === Symbol("lastRunAt")
        OpenAPI.validate_param(name, "Automation", :format, val, "date-time")
    end

    if name === Symbol("nextRunAt")
        OpenAPI.validate_param(name, "Automation", :format, val, "date-time")
    end

    if name === Symbol("tenantId")
        OpenAPI.validate_param(name, "Automation", :format, val, "uuid")
    end

    if name === Symbol("updatedAt")
        OpenAPI.validate_param(name, "Automation", :format, val, "date-time")
    end
end
