# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TotpEnableRequest

    TotpEnableRequest(;
        code=nothing,
    )

    - code::String
"""
Base.@kwdef mutable struct TotpEnableRequest <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing

    function TotpEnableRequest(code, )
        o = new(code, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TotpEnableRequest

const _property_types_TotpEnableRequest = Dict{Symbol,String}(Symbol("code")=>"String", )
OpenAPI.property_type(::Type{ TotpEnableRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TotpEnableRequest[name]))}

function OpenAPI.check_required(o::TotpEnableRequest)
    o.code === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TotpEnableRequest)
    OpenAPI.validate_property(TotpEnableRequest, Symbol("code"), o.code)
end

function OpenAPI.validate_property(::Type{ TotpEnableRequest }, name::Symbol, val)

end
