# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BalanceSheet

    BalanceSheet(;
        assets=nothing,
        balanced=nothing,
        equity_liabilities=nothing,
        total_assets=nothing,
        total_equity_liabilities=nothing,
    )

    - assets::Vector{BalanceItem}
    - balanced::Bool
    - equity_liabilities::Vector{BalanceItem}
    - total_assets::String
    - total_equity_liabilities::String
"""
Base.@kwdef mutable struct BalanceSheet <: OpenAPI.APIModel
    assets::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{BalanceItem} }
    balanced::Union{Nothing, Bool} = nothing
    equity_liabilities::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{BalanceItem} }
    total_assets::Union{Nothing, String} = nothing
    total_equity_liabilities::Union{Nothing, String} = nothing

    function BalanceSheet(assets, balanced, equity_liabilities, total_assets, total_equity_liabilities, )
        o = new(assets, balanced, equity_liabilities, total_assets, total_equity_liabilities, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BalanceSheet

const _property_types_BalanceSheet = Dict{Symbol,String}(Symbol("assets")=>"Vector{BalanceItem}", Symbol("balanced")=>"Bool", Symbol("equity_liabilities")=>"Vector{BalanceItem}", Symbol("total_assets")=>"String", Symbol("total_equity_liabilities")=>"String", )
OpenAPI.property_type(::Type{ BalanceSheet }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BalanceSheet[name]))}

function OpenAPI.check_required(o::BalanceSheet)
    o.assets === nothing && (return false)
    o.balanced === nothing && (return false)
    o.equity_liabilities === nothing && (return false)
    o.total_assets === nothing && (return false)
    o.total_equity_liabilities === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::BalanceSheet)
    OpenAPI.validate_property(BalanceSheet, Symbol("assets"), o.assets)
    OpenAPI.validate_property(BalanceSheet, Symbol("balanced"), o.balanced)
    OpenAPI.validate_property(BalanceSheet, Symbol("equity_liabilities"), o.equity_liabilities)
    OpenAPI.validate_property(BalanceSheet, Symbol("total_assets"), o.total_assets)
    OpenAPI.validate_property(BalanceSheet, Symbol("total_equity_liabilities"), o.total_equity_liabilities)
end

function OpenAPI.validate_property(::Type{ BalanceSheet }, name::Symbol, val)





end
