# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TrackingInfo

    TrackingInfo(;
        carrier=nothing,
        estimated_delivery=nothing,
        events=nothing,
        raw_response=nothing,
        status=nothing,
        tracking_number=nothing,
    )

    - carrier::String
    - estimated_delivery::String
    - events::Vector{TrackingEvent}
    - raw_response::Any
    - status::String
    - tracking_number::String
"""
Base.@kwdef mutable struct TrackingInfo <: OpenAPI.APIModel
    carrier::Union{Nothing, String} = nothing
    estimated_delivery::Union{Nothing, String} = nothing
    events::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{TrackingEvent} }
    raw_response::Union{Nothing, Any} = nothing
    status::Union{Nothing, String} = nothing
    tracking_number::Union{Nothing, String} = nothing

    function TrackingInfo(carrier, estimated_delivery, events, raw_response, status, tracking_number, )
        o = new(carrier, estimated_delivery, events, raw_response, status, tracking_number, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TrackingInfo

const _property_types_TrackingInfo = Dict{Symbol,String}(Symbol("carrier")=>"String", Symbol("estimated_delivery")=>"String", Symbol("events")=>"Vector{TrackingEvent}", Symbol("raw_response")=>"Any", Symbol("status")=>"String", Symbol("tracking_number")=>"String", )
OpenAPI.property_type(::Type{ TrackingInfo }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TrackingInfo[name]))}

function OpenAPI.check_required(o::TrackingInfo)
    o.carrier === nothing && (return false)
    o.events === nothing && (return false)
    o.status === nothing && (return false)
    o.tracking_number === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TrackingInfo)
    OpenAPI.validate_property(TrackingInfo, Symbol("carrier"), o.carrier)
    OpenAPI.validate_property(TrackingInfo, Symbol("estimated_delivery"), o.estimated_delivery)
    OpenAPI.validate_property(TrackingInfo, Symbol("events"), o.events)
    OpenAPI.validate_property(TrackingInfo, Symbol("raw_response"), o.raw_response)
    OpenAPI.validate_property(TrackingInfo, Symbol("status"), o.status)
    OpenAPI.validate_property(TrackingInfo, Symbol("tracking_number"), o.tracking_number)
end

function OpenAPI.validate_property(::Type{ TrackingInfo }, name::Symbol, val)






end
