# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RateResponse

    RateResponse(;
        rates=nothing,
    )

    - rates::Vector{ShippingRate}
"""
Base.@kwdef mutable struct RateResponse <: OpenAPI.APIModel
    rates::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ShippingRate} }

    function RateResponse(rates, )
        o = new(rates, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type RateResponse

const _property_types_RateResponse = Dict{Symbol,String}(Symbol("rates")=>"Vector{ShippingRate}", )
OpenAPI.property_type(::Type{ RateResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RateResponse[name]))}

function OpenAPI.check_required(o::RateResponse)
    o.rates === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::RateResponse)
    OpenAPI.validate_property(RateResponse, Symbol("rates"), o.rates)
end

function OpenAPI.validate_property(::Type{ RateResponse }, name::Symbol, val)

end
