# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PayGapReport

    PayGapReport(;
        by_job_title=nothing,
        diverse_count=nothing,
        employee_count=nothing,
        female_count=nothing,
        male_count=nothing,
        mean_gap_pct=nothing,
        median_gap_pct=nothing,
        quartiles=nothing,
    )

    - by_job_title::Vector{JobTitleGap}
    - diverse_count::Int64
    - employee_count::Int64
    - female_count::Int64
    - male_count::Int64
    - mean_gap_pct::Float64
    - median_gap_pct::Float64
    - quartiles::Vector{QuartileBand}
"""
Base.@kwdef mutable struct PayGapReport <: OpenAPI.APIModel
    by_job_title::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{JobTitleGap} }
    diverse_count::Union{Nothing, Int64} = nothing
    employee_count::Union{Nothing, Int64} = nothing
    female_count::Union{Nothing, Int64} = nothing
    male_count::Union{Nothing, Int64} = nothing
    mean_gap_pct::Union{Nothing, Float64} = nothing
    median_gap_pct::Union{Nothing, Float64} = nothing
    quartiles::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{QuartileBand} }

    function PayGapReport(by_job_title, diverse_count, employee_count, female_count, male_count, mean_gap_pct, median_gap_pct, quartiles, )
        o = new(by_job_title, diverse_count, employee_count, female_count, male_count, mean_gap_pct, median_gap_pct, quartiles, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PayGapReport

const _property_types_PayGapReport = Dict{Symbol,String}(Symbol("by_job_title")=>"Vector{JobTitleGap}", Symbol("diverse_count")=>"Int64", Symbol("employee_count")=>"Int64", Symbol("female_count")=>"Int64", Symbol("male_count")=>"Int64", Symbol("mean_gap_pct")=>"Float64", Symbol("median_gap_pct")=>"Float64", Symbol("quartiles")=>"Vector{QuartileBand}", )
OpenAPI.property_type(::Type{ PayGapReport }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PayGapReport[name]))}

function OpenAPI.check_required(o::PayGapReport)
    o.by_job_title === nothing && (return false)
    o.diverse_count === nothing && (return false)
    o.employee_count === nothing && (return false)
    o.female_count === nothing && (return false)
    o.male_count === nothing && (return false)
    o.mean_gap_pct === nothing && (return false)
    o.median_gap_pct === nothing && (return false)
    o.quartiles === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PayGapReport)
    OpenAPI.validate_property(PayGapReport, Symbol("by_job_title"), o.by_job_title)
    OpenAPI.validate_property(PayGapReport, Symbol("diverse_count"), o.diverse_count)
    OpenAPI.validate_property(PayGapReport, Symbol("employee_count"), o.employee_count)
    OpenAPI.validate_property(PayGapReport, Symbol("female_count"), o.female_count)
    OpenAPI.validate_property(PayGapReport, Symbol("male_count"), o.male_count)
    OpenAPI.validate_property(PayGapReport, Symbol("mean_gap_pct"), o.mean_gap_pct)
    OpenAPI.validate_property(PayGapReport, Symbol("median_gap_pct"), o.median_gap_pct)
    OpenAPI.validate_property(PayGapReport, Symbol("quartiles"), o.quartiles)
end

function OpenAPI.validate_property(::Type{ PayGapReport }, name::Symbol, val)


    if name === Symbol("diverse_count")
        OpenAPI.validate_param(name, "PayGapReport", :minimum, val, 0, false)
    end

    if name === Symbol("employee_count")
        OpenAPI.validate_param(name, "PayGapReport", :minimum, val, 0, false)
    end

    if name === Symbol("female_count")
        OpenAPI.validate_param(name, "PayGapReport", :minimum, val, 0, false)
    end

    if name === Symbol("male_count")
        OpenAPI.validate_param(name, "PayGapReport", :minimum, val, 0, false)
    end

    if name === Symbol("mean_gap_pct")
        OpenAPI.validate_param(name, "PayGapReport", :format, val, "double")
    end

    if name === Symbol("median_gap_pct")
        OpenAPI.validate_param(name, "PayGapReport", :format, val, "double")
    end

end
