# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ProductionOrderStatusUpdate
Status update request.

    ProductionOrderStatusUpdate(;
        status=nothing,
    )

    - status::String
"""
Base.@kwdef mutable struct ProductionOrderStatusUpdate <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing

    function ProductionOrderStatusUpdate(status, )
        o = new(status, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ProductionOrderStatusUpdate

const _property_types_ProductionOrderStatusUpdate = Dict{Symbol,String}(Symbol("status")=>"String", )
OpenAPI.property_type(::Type{ ProductionOrderStatusUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ProductionOrderStatusUpdate[name]))}

function OpenAPI.check_required(o::ProductionOrderStatusUpdate)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ProductionOrderStatusUpdate)
    OpenAPI.validate_property(ProductionOrderStatusUpdate, Symbol("status"), o.status)
end

function OpenAPI.validate_property(::Type{ ProductionOrderStatusUpdate }, name::Symbol, val)

end
