# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PluginError_oneOf_5

    PluginErrorOneOf5(;
        ValidationError=nothing,
    )

    - ValidationError::Vector{Any}
"""
Base.@kwdef mutable struct PluginErrorOneOf5 <: OpenAPI.APIModel
    ValidationError::Union{Nothing, Vector{Any}} = nothing

    function PluginErrorOneOf5(ValidationError, )
        o = new(ValidationError, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PluginErrorOneOf5

const _property_types_PluginErrorOneOf5 = Dict{Symbol,String}(Symbol("ValidationError")=>"Vector{Any}", )
OpenAPI.property_type(::Type{ PluginErrorOneOf5 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PluginErrorOneOf5[name]))}

function OpenAPI.check_required(o::PluginErrorOneOf5)
    o.ValidationError === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PluginErrorOneOf5)
    OpenAPI.validate_property(PluginErrorOneOf5, Symbol("ValidationError"), o.ValidationError)
end

function OpenAPI.validate_property(::Type{ PluginErrorOneOf5 }, name::Symbol, val)

    if name === Symbol("ValidationError")
        OpenAPI.validate_param(name, "PluginErrorOneOf5", :maxItems, val, 2)
        OpenAPI.validate_param(name, "PluginErrorOneOf5", :minItems, val, 2)
    end
end
