# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""LaborCostRow

    LaborCostRow(;
        cost=nothing,
        employeeId=nothing,
        groupKey=nothing,
        hours=nothing,
        name=nothing,
    )

    - cost::String
    - employeeId::String
    - groupKey::String
    - hours::String
    - name::String
"""
Base.@kwdef mutable struct LaborCostRow <: OpenAPI.APIModel
    cost::Union{Nothing, String} = nothing
    employeeId::Union{Nothing, String} = nothing
    groupKey::Union{Nothing, String} = nothing
    hours::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing

    function LaborCostRow(cost, employeeId, groupKey, hours, name, )
        o = new(cost, employeeId, groupKey, hours, name, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type LaborCostRow

const _property_types_LaborCostRow = Dict{Symbol,String}(Symbol("cost")=>"String", Symbol("employeeId")=>"String", Symbol("groupKey")=>"String", Symbol("hours")=>"String", Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ LaborCostRow }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_LaborCostRow[name]))}

function OpenAPI.check_required(o::LaborCostRow)
    o.cost === nothing && (return false)
    o.groupKey === nothing && (return false)
    o.hours === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::LaborCostRow)
    OpenAPI.validate_property(LaborCostRow, Symbol("cost"), o.cost)
    OpenAPI.validate_property(LaborCostRow, Symbol("employeeId"), o.employeeId)
    OpenAPI.validate_property(LaborCostRow, Symbol("groupKey"), o.groupKey)
    OpenAPI.validate_property(LaborCostRow, Symbol("hours"), o.hours)
    OpenAPI.validate_property(LaborCostRow, Symbol("name"), o.name)
end

function OpenAPI.validate_property(::Type{ LaborCostRow }, name::Symbol, val)


    if name === Symbol("employeeId")
        OpenAPI.validate_param(name, "LaborCostRow", :format, val, "uuid")
    end



end
