# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TrainingAssignmentCreate

    TrainingAssignmentCreate(;
        assignedBy=nothing,
        dueDate=nothing,
        employeeId=nothing,
        notes=nothing,
        status=nothing,
        trainingId=nothing,
    )

    - assignedBy::String
    - dueDate::Date
    - employeeId::String
    - notes::String
    - status::AssignmentStatus
    - trainingId::String
"""
Base.@kwdef mutable struct TrainingAssignmentCreate <: OpenAPI.APIModel
    assignedBy::Union{Nothing, String} = nothing
    dueDate::Union{Nothing, Date} = nothing
    employeeId::Union{Nothing, String} = nothing
    notes::Union{Nothing, String} = nothing
    status = nothing # spec type: Union{ Nothing, AssignmentStatus }
    trainingId::Union{Nothing, String} = nothing

    function TrainingAssignmentCreate(assignedBy, dueDate, employeeId, notes, status, trainingId, )
        o = new(assignedBy, dueDate, employeeId, notes, status, trainingId, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TrainingAssignmentCreate

const _property_types_TrainingAssignmentCreate = Dict{Symbol,String}(Symbol("assignedBy")=>"String", Symbol("dueDate")=>"Date", Symbol("employeeId")=>"String", Symbol("notes")=>"String", Symbol("status")=>"AssignmentStatus", Symbol("trainingId")=>"String", )
OpenAPI.property_type(::Type{ TrainingAssignmentCreate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TrainingAssignmentCreate[name]))}

function OpenAPI.check_required(o::TrainingAssignmentCreate)
    true
end

function OpenAPI.validate_properties(o::TrainingAssignmentCreate)
    OpenAPI.validate_property(TrainingAssignmentCreate, Symbol("assignedBy"), o.assignedBy)
    OpenAPI.validate_property(TrainingAssignmentCreate, Symbol("dueDate"), o.dueDate)
    OpenAPI.validate_property(TrainingAssignmentCreate, Symbol("employeeId"), o.employeeId)
    OpenAPI.validate_property(TrainingAssignmentCreate, Symbol("notes"), o.notes)
    OpenAPI.validate_property(TrainingAssignmentCreate, Symbol("status"), o.status)
    OpenAPI.validate_property(TrainingAssignmentCreate, Symbol("trainingId"), o.trainingId)
end

function OpenAPI.validate_property(::Type{ TrainingAssignmentCreate }, name::Symbol, val)

    if name === Symbol("assignedBy")
        OpenAPI.validate_param(name, "TrainingAssignmentCreate", :format, val, "uuid")
    end

    if name === Symbol("dueDate")
        OpenAPI.validate_param(name, "TrainingAssignmentCreate", :format, val, "date")
    end

    if name === Symbol("employeeId")
        OpenAPI.validate_param(name, "TrainingAssignmentCreate", :format, val, "uuid")
    end

    if name === Symbol("notes")
        OpenAPI.validate_param(name, "TrainingAssignmentCreate", :maxLength, val, 1000)
    end


    if name === Symbol("trainingId")
        OpenAPI.validate_param(name, "TrainingAssignmentCreate", :format, val, "uuid")
    end
end
