# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdatePermissionsPayload

    UpdatePermissionsPayload(;
        permissions=nothing,
    )

    - permissions::Vector{String}
"""
Base.@kwdef mutable struct UpdatePermissionsPayload <: OpenAPI.APIModel
    permissions::Union{Nothing, Vector{String}} = nothing

    function UpdatePermissionsPayload(permissions, )
        o = new(permissions, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type UpdatePermissionsPayload

const _property_types_UpdatePermissionsPayload = Dict{Symbol,String}(Symbol("permissions")=>"Vector{String}", )
OpenAPI.property_type(::Type{ UpdatePermissionsPayload }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdatePermissionsPayload[name]))}

function OpenAPI.check_required(o::UpdatePermissionsPayload)
    o.permissions === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::UpdatePermissionsPayload)
    OpenAPI.validate_property(UpdatePermissionsPayload, Symbol("permissions"), o.permissions)
end

function OpenAPI.validate_property(::Type{ UpdatePermissionsPayload }, name::Symbol, val)

end
