# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Employee

    Employee(;
        address=nothing,
        backupEmployeeId=nothing,
        bic=nothing,
        city=nothing,
        country=nothing,
        createdAt=nothing,
        dateOfBirth=nothing,
        deletedAt=nothing,
        departmentId=nothing,
        email=nothing,
        firstName=nothing,
        gender=nothing,
        hireDate=nothing,
        hourlyCost=nothing,
        iban=nothing,
        id=nothing,
        jobTitle=nothing,
        lastLogin=nothing,
        lastName=nothing,
        lastUpdated=nothing,
        monthlySalary=nothing,
        phone=nothing,
        state=nothing,
        status=nothing,
        tenantId=nothing,
        updatedAt=nothing,
        userId=nothing,
        weeklyHours=nothing,
        zip=nothing,
    )

    - address::String
    - backupEmployeeId::String : References another employee who covers when this employee is absent.
    - bic::String
    - city::String
    - country::CountryCode
    - createdAt::ZonedDateTime
    - dateOfBirth::Date
    - deletedAt::ZonedDateTime
    - departmentId::String : References the department entity.
    - email::String
    - firstName::String
    - gender::Gender : Gender for pay-transparency reporting: \&quot;male\&quot;, \&quot;female\&quot; or \&quot;diverse\&quot;.
    - hireDate::Date
    - hourlyCost::String : Hourly cost rate in EUR for labor-cost reporting; when unset the rate is derived from &#x60;monthly_salary / (weekly_hours * 4.33)&#x60;.
    - iban::String
    - id::String
    - jobTitle::String
    - lastLogin::ZonedDateTime
    - lastName::String
    - lastUpdated::ZonedDateTime
    - monthlySalary::String : Gross monthly salary in EUR for pay-transparency reporting.
    - phone::String
    - state::String
    - status::EmployeeStatus
    - tenantId::String
    - updatedAt::ZonedDateTime
    - userId::String : References the user entity.
    - weeklyHours::String : Contractual weekly working hours for pay-transparency normalization.
    - zip::String
"""
Base.@kwdef mutable struct Employee <: OpenAPI.APIModel
    address::Union{Nothing, String} = nothing
    backupEmployeeId::Union{Nothing, String} = nothing
    bic::Union{Nothing, String} = nothing
    city::Union{Nothing, String} = nothing
    country = nothing # spec type: Union{ Nothing, CountryCode }
    createdAt::Union{Nothing, ZonedDateTime} = nothing
    dateOfBirth::Union{Nothing, Date} = nothing
    deletedAt::Union{Nothing, ZonedDateTime} = nothing
    departmentId::Union{Nothing, String} = nothing
    email::Union{Nothing, String} = nothing
    firstName::Union{Nothing, String} = nothing
    gender = nothing # spec type: Union{ Nothing, Gender }
    hireDate::Union{Nothing, Date} = nothing
    hourlyCost::Union{Nothing, String} = nothing
    iban::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing
    jobTitle::Union{Nothing, String} = nothing
    lastLogin::Union{Nothing, ZonedDateTime} = nothing
    lastName::Union{Nothing, String} = nothing
    lastUpdated::Union{Nothing, ZonedDateTime} = nothing
    monthlySalary::Union{Nothing, String} = nothing
    phone::Union{Nothing, String} = nothing
    state::Union{Nothing, String} = nothing
    status = nothing # spec type: Union{ Nothing, EmployeeStatus }
    tenantId::Union{Nothing, String} = nothing
    updatedAt::Union{Nothing, ZonedDateTime} = nothing
    userId::Union{Nothing, String} = nothing
    weeklyHours::Union{Nothing, String} = nothing
    zip::Union{Nothing, String} = nothing

    function Employee(address, backupEmployeeId, bic, city, country, createdAt, dateOfBirth, deletedAt, departmentId, email, firstName, gender, hireDate, hourlyCost, iban, id, jobTitle, lastLogin, lastName, lastUpdated, monthlySalary, phone, state, status, tenantId, updatedAt, userId, weeklyHours, zip, )
        o = new(address, backupEmployeeId, bic, city, country, createdAt, dateOfBirth, deletedAt, departmentId, email, firstName, gender, hireDate, hourlyCost, iban, id, jobTitle, lastLogin, lastName, lastUpdated, monthlySalary, phone, state, status, tenantId, updatedAt, userId, weeklyHours, zip, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Employee

const _property_types_Employee = Dict{Symbol,String}(Symbol("address")=>"String", Symbol("backupEmployeeId")=>"String", Symbol("bic")=>"String", Symbol("city")=>"String", Symbol("country")=>"CountryCode", Symbol("createdAt")=>"ZonedDateTime", Symbol("dateOfBirth")=>"Date", Symbol("deletedAt")=>"ZonedDateTime", Symbol("departmentId")=>"String", Symbol("email")=>"String", Symbol("firstName")=>"String", Symbol("gender")=>"Gender", Symbol("hireDate")=>"Date", Symbol("hourlyCost")=>"String", Symbol("iban")=>"String", Symbol("id")=>"String", Symbol("jobTitle")=>"String", Symbol("lastLogin")=>"ZonedDateTime", Symbol("lastName")=>"String", Symbol("lastUpdated")=>"ZonedDateTime", Symbol("monthlySalary")=>"String", Symbol("phone")=>"String", Symbol("state")=>"String", Symbol("status")=>"EmployeeStatus", Symbol("tenantId")=>"String", Symbol("updatedAt")=>"ZonedDateTime", Symbol("userId")=>"String", Symbol("weeklyHours")=>"String", Symbol("zip")=>"String", )
OpenAPI.property_type(::Type{ Employee }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Employee[name]))}

function OpenAPI.check_required(o::Employee)
    true
end

function OpenAPI.validate_properties(o::Employee)
    OpenAPI.validate_property(Employee, Symbol("address"), o.address)
    OpenAPI.validate_property(Employee, Symbol("backupEmployeeId"), o.backupEmployeeId)
    OpenAPI.validate_property(Employee, Symbol("bic"), o.bic)
    OpenAPI.validate_property(Employee, Symbol("city"), o.city)
    OpenAPI.validate_property(Employee, Symbol("country"), o.country)
    OpenAPI.validate_property(Employee, Symbol("createdAt"), o.createdAt)
    OpenAPI.validate_property(Employee, Symbol("dateOfBirth"), o.dateOfBirth)
    OpenAPI.validate_property(Employee, Symbol("deletedAt"), o.deletedAt)
    OpenAPI.validate_property(Employee, Symbol("departmentId"), o.departmentId)
    OpenAPI.validate_property(Employee, Symbol("email"), o.email)
    OpenAPI.validate_property(Employee, Symbol("firstName"), o.firstName)
    OpenAPI.validate_property(Employee, Symbol("gender"), o.gender)
    OpenAPI.validate_property(Employee, Symbol("hireDate"), o.hireDate)
    OpenAPI.validate_property(Employee, Symbol("hourlyCost"), o.hourlyCost)
    OpenAPI.validate_property(Employee, Symbol("iban"), o.iban)
    OpenAPI.validate_property(Employee, Symbol("id"), o.id)
    OpenAPI.validate_property(Employee, Symbol("jobTitle"), o.jobTitle)
    OpenAPI.validate_property(Employee, Symbol("lastLogin"), o.lastLogin)
    OpenAPI.validate_property(Employee, Symbol("lastName"), o.lastName)
    OpenAPI.validate_property(Employee, Symbol("lastUpdated"), o.lastUpdated)
    OpenAPI.validate_property(Employee, Symbol("monthlySalary"), o.monthlySalary)
    OpenAPI.validate_property(Employee, Symbol("phone"), o.phone)
    OpenAPI.validate_property(Employee, Symbol("state"), o.state)
    OpenAPI.validate_property(Employee, Symbol("status"), o.status)
    OpenAPI.validate_property(Employee, Symbol("tenantId"), o.tenantId)
    OpenAPI.validate_property(Employee, Symbol("updatedAt"), o.updatedAt)
    OpenAPI.validate_property(Employee, Symbol("userId"), o.userId)
    OpenAPI.validate_property(Employee, Symbol("weeklyHours"), o.weeklyHours)
    OpenAPI.validate_property(Employee, Symbol("zip"), o.zip)
end

function OpenAPI.validate_property(::Type{ Employee }, name::Symbol, val)

    if name === Symbol("address")
        OpenAPI.validate_param(name, "Employee", :maxLength, val, 255)
    end

    if name === Symbol("backupEmployeeId")
        OpenAPI.validate_param(name, "Employee", :format, val, "uuid")
    end


    if name === Symbol("city")
        OpenAPI.validate_param(name, "Employee", :maxLength, val, 100)
    end


    if name === Symbol("createdAt")
        OpenAPI.validate_param(name, "Employee", :format, val, "date-time")
    end

    if name === Symbol("dateOfBirth")
        OpenAPI.validate_param(name, "Employee", :format, val, "date")
    end

    if name === Symbol("deletedAt")
        OpenAPI.validate_param(name, "Employee", :format, val, "date-time")
    end

    if name === Symbol("departmentId")
        OpenAPI.validate_param(name, "Employee", :format, val, "uuid")
    end

    if name === Symbol("email")
        OpenAPI.validate_param(name, "Employee", :format, val, "email")
    end

    if name === Symbol("firstName")
        OpenAPI.validate_param(name, "Employee", :maxLength, val, 100)
        OpenAPI.validate_param(name, "Employee", :minLength, val, 1)
    end


    if name === Symbol("hireDate")
        OpenAPI.validate_param(name, "Employee", :format, val, "date")
    end



    if name === Symbol("id")
        OpenAPI.validate_param(name, "Employee", :format, val, "uuid")
    end

    if name === Symbol("jobTitle")
        OpenAPI.validate_param(name, "Employee", :maxLength, val, 100)
    end

    if name === Symbol("lastLogin")
        OpenAPI.validate_param(name, "Employee", :format, val, "date-time")
    end

    if name === Symbol("lastName")
        OpenAPI.validate_param(name, "Employee", :maxLength, val, 100)
        OpenAPI.validate_param(name, "Employee", :minLength, val, 1)
    end

    if name === Symbol("lastUpdated")
        OpenAPI.validate_param(name, "Employee", :format, val, "date-time")
    end


    if name === Symbol("phone")
        OpenAPI.validate_param(name, "Employee", :pattern, val, r"^\+?[0-9\s\-\(\)]{7,20}$")
    end

    if name === Symbol("state")
        OpenAPI.validate_param(name, "Employee", :maxLength, val, 100)
    end


    if name === Symbol("tenantId")
        OpenAPI.validate_param(name, "Employee", :format, val, "uuid")
    end

    if name === Symbol("updatedAt")
        OpenAPI.validate_param(name, "Employee", :format, val, "date-time")
    end

    if name === Symbol("userId")
        OpenAPI.validate_param(name, "Employee", :format, val, "uuid")
    end


    if name === Symbol("zip")
        OpenAPI.validate_param(name, "Employee", :maxLength, val, 20)
    end
end
