# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AnlageSErgebnis

    AnlageSErgebnis(;
        gewinn_verlust=nothing,
        jahr=nothing,
        kfz_hinweise=nothing,
    )

    - gewinn_verlust::String
    - jahr::Int64
    - kfz_hinweise::Vector{AnlageSKfzHinweis}
"""
Base.@kwdef mutable struct AnlageSErgebnis <: OpenAPI.APIModel
    gewinn_verlust::Union{Nothing, String} = nothing
    jahr::Union{Nothing, Int64} = nothing
    kfz_hinweise::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{AnlageSKfzHinweis} }

    function AnlageSErgebnis(gewinn_verlust, jahr, kfz_hinweise, )
        o = new(gewinn_verlust, jahr, kfz_hinweise, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AnlageSErgebnis

const _property_types_AnlageSErgebnis = Dict{Symbol,String}(Symbol("gewinn_verlust")=>"String", Symbol("jahr")=>"Int64", Symbol("kfz_hinweise")=>"Vector{AnlageSKfzHinweis}", )
OpenAPI.property_type(::Type{ AnlageSErgebnis }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AnlageSErgebnis[name]))}

function OpenAPI.check_required(o::AnlageSErgebnis)
    o.gewinn_verlust === nothing && (return false)
    o.jahr === nothing && (return false)
    o.kfz_hinweise === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::AnlageSErgebnis)
    OpenAPI.validate_property(AnlageSErgebnis, Symbol("gewinn_verlust"), o.gewinn_verlust)
    OpenAPI.validate_property(AnlageSErgebnis, Symbol("jahr"), o.jahr)
    OpenAPI.validate_property(AnlageSErgebnis, Symbol("kfz_hinweise"), o.kfz_hinweise)
end

function OpenAPI.validate_property(::Type{ AnlageSErgebnis }, name::Symbol, val)


    if name === Symbol("jahr")
        OpenAPI.validate_param(name, "AnlageSErgebnis", :format, val, "int32")
    end

end
