# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""InvoiceLineItem

    InvoiceLineItem(;
        article_number=nothing,
        description=nothing,
        discount_amount=nothing,
        discount_percentage=nothing,
        input_vat_deductible=nothing,
        input_vat_rate=nothing,
        is_intra_community_acquisition=nothing,
        is_margin_25a=nothing,
        ledger_account=nothing,
        line_total=nothing,
        line_total_gross=nothing,
        margin_25a_purchase_price=nothing,
        meter_point_id=nothing,
        position=nothing,
        price_components=nothing,
        product_id=nothing,
        product_sku=nothing,
        quantity=nothing,
        supplier_article_number=nothing,
        tax_rate=nothing,
        unit=nothing,
        unit_price=nothing,
        usage_data_id=nothing,
        vat_rate_nominal=nothing,
        vat_special_case=nothing,
    )

    - article_number::String
    - description::String
    - discount_amount::String
    - discount_percentage::String
    - input_vat_deductible::Bool
    - input_vat_rate::String
    - is_intra_community_acquisition::Bool
    - is_margin_25a::Bool
    - ledger_account::String
    - line_total::String
    - line_total_gross::String
    - margin_25a_purchase_price::String
    - meter_point_id::String
    - position::Int64
    - price_components::Any
    - product_id::String
    - product_sku::String
    - quantity::String
    - supplier_article_number::String
    - tax_rate::String
    - unit::Any
    - unit_price::String
    - usage_data_id::String
    - vat_rate_nominal::String
    - vat_special_case::String
"""
Base.@kwdef mutable struct InvoiceLineItem <: OpenAPI.APIModel
    article_number::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    discount_amount::Union{Nothing, String} = nothing
    discount_percentage::Union{Nothing, String} = nothing
    input_vat_deductible::Union{Nothing, Bool} = nothing
    input_vat_rate::Union{Nothing, String} = nothing
    is_intra_community_acquisition::Union{Nothing, Bool} = nothing
    is_margin_25a::Union{Nothing, Bool} = nothing
    ledger_account::Union{Nothing, String} = nothing
    line_total::Union{Nothing, String} = nothing
    line_total_gross::Union{Nothing, String} = nothing
    margin_25a_purchase_price::Union{Nothing, String} = nothing
    meter_point_id::Union{Nothing, String} = nothing
    position::Union{Nothing, Int64} = nothing
    price_components::Union{Nothing, Any} = nothing
    product_id::Union{Nothing, String} = nothing
    product_sku::Union{Nothing, String} = nothing
    quantity::Union{Nothing, String} = nothing
    supplier_article_number::Union{Nothing, String} = nothing
    tax_rate::Union{Nothing, String} = nothing
    unit::Union{Nothing, Any} = nothing
    unit_price::Union{Nothing, String} = nothing
    usage_data_id::Union{Nothing, String} = nothing
    vat_rate_nominal::Union{Nothing, String} = nothing
    vat_special_case::Union{Nothing, String} = nothing

    function InvoiceLineItem(article_number, description, discount_amount, discount_percentage, input_vat_deductible, input_vat_rate, is_intra_community_acquisition, is_margin_25a, ledger_account, line_total, line_total_gross, margin_25a_purchase_price, meter_point_id, position, price_components, product_id, product_sku, quantity, supplier_article_number, tax_rate, unit, unit_price, usage_data_id, vat_rate_nominal, vat_special_case, )
        o = new(article_number, description, discount_amount, discount_percentage, input_vat_deductible, input_vat_rate, is_intra_community_acquisition, is_margin_25a, ledger_account, line_total, line_total_gross, margin_25a_purchase_price, meter_point_id, position, price_components, product_id, product_sku, quantity, supplier_article_number, tax_rate, unit, unit_price, usage_data_id, vat_rate_nominal, vat_special_case, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type InvoiceLineItem

const _property_types_InvoiceLineItem = Dict{Symbol,String}(Symbol("article_number")=>"String", Symbol("description")=>"String", Symbol("discount_amount")=>"String", Symbol("discount_percentage")=>"String", Symbol("input_vat_deductible")=>"Bool", Symbol("input_vat_rate")=>"String", Symbol("is_intra_community_acquisition")=>"Bool", Symbol("is_margin_25a")=>"Bool", Symbol("ledger_account")=>"String", Symbol("line_total")=>"String", Symbol("line_total_gross")=>"String", Symbol("margin_25a_purchase_price")=>"String", Symbol("meter_point_id")=>"String", Symbol("position")=>"Int64", Symbol("price_components")=>"Any", Symbol("product_id")=>"String", Symbol("product_sku")=>"String", Symbol("quantity")=>"String", Symbol("supplier_article_number")=>"String", Symbol("tax_rate")=>"String", Symbol("unit")=>"Any", Symbol("unit_price")=>"String", Symbol("usage_data_id")=>"String", Symbol("vat_rate_nominal")=>"String", Symbol("vat_special_case")=>"String", )
OpenAPI.property_type(::Type{ InvoiceLineItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_InvoiceLineItem[name]))}

function OpenAPI.check_required(o::InvoiceLineItem)
    o.description === nothing && (return false)
    o.line_total === nothing && (return false)
    o.position === nothing && (return false)
    o.quantity === nothing && (return false)
    o.unit === nothing && (return false)
    o.unit_price === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::InvoiceLineItem)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("article_number"), o.article_number)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("description"), o.description)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("discount_amount"), o.discount_amount)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("discount_percentage"), o.discount_percentage)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("input_vat_deductible"), o.input_vat_deductible)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("input_vat_rate"), o.input_vat_rate)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("is_intra_community_acquisition"), o.is_intra_community_acquisition)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("is_margin_25a"), o.is_margin_25a)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("ledger_account"), o.ledger_account)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("line_total"), o.line_total)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("line_total_gross"), o.line_total_gross)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("margin_25a_purchase_price"), o.margin_25a_purchase_price)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("meter_point_id"), o.meter_point_id)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("position"), o.position)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("price_components"), o.price_components)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("product_id"), o.product_id)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("product_sku"), o.product_sku)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("quantity"), o.quantity)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("supplier_article_number"), o.supplier_article_number)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("tax_rate"), o.tax_rate)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("unit"), o.unit)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("unit_price"), o.unit_price)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("usage_data_id"), o.usage_data_id)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("vat_rate_nominal"), o.vat_rate_nominal)
    OpenAPI.validate_property(InvoiceLineItem, Symbol("vat_special_case"), o.vat_special_case)
end

function OpenAPI.validate_property(::Type{ InvoiceLineItem }, name::Symbol, val)













    if name === Symbol("meter_point_id")
        OpenAPI.validate_param(name, "InvoiceLineItem", :format, val, "uuid")
    end

    if name === Symbol("position")
        OpenAPI.validate_param(name, "InvoiceLineItem", :format, val, "int64")
    end
    if name === Symbol("position")
        OpenAPI.validate_param(name, "InvoiceLineItem", :minimum, val, 0, false)
    end


    if name === Symbol("product_id")
        OpenAPI.validate_param(name, "InvoiceLineItem", :format, val, "uuid")
    end







    if name === Symbol("usage_data_id")
        OpenAPI.validate_param(name, "InvoiceLineItem", :format, val, "uuid")
    end


end
