# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""JobApplication

    JobApplication(;
        cvFile=nothing,
        cvText=nothing,
        email=nothing,
        matchReason=nothing,
        matchScore=nothing,
        name=nothing,
        phone=nothing,
        postingId=nothing,
        source=nothing,
        status=nothing,
    )

    - cvFile::String : Relative path of the stored CV file under the upload dir.
    - cvText::String : Extracted CV text, used for match-scoring.
    - email::String
    - matchReason::String
    - matchScore::Int64 : 0-100 LLM match score against the posting&#39;s required profile.
    - name::String
    - phone::String
    - postingId::String : References the job_posting entity.
    - source::String : website | email | board
    - status::ApplicationStatus : new | reviewing | interview | hired | rejected
"""
Base.@kwdef mutable struct JobApplication <: OpenAPI.APIModel
    cvFile::Union{Nothing, String} = nothing
    cvText::Union{Nothing, String} = nothing
    email::Union{Nothing, String} = nothing
    matchReason::Union{Nothing, String} = nothing
    matchScore::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    phone::Union{Nothing, String} = nothing
    postingId::Union{Nothing, String} = nothing
    source::Union{Nothing, String} = nothing
    status = nothing # spec type: Union{ Nothing, ApplicationStatus }

    function JobApplication(cvFile, cvText, email, matchReason, matchScore, name, phone, postingId, source, status, )
        o = new(cvFile, cvText, email, matchReason, matchScore, name, phone, postingId, source, status, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type JobApplication

const _property_types_JobApplication = Dict{Symbol,String}(Symbol("cvFile")=>"String", Symbol("cvText")=>"String", Symbol("email")=>"String", Symbol("matchReason")=>"String", Symbol("matchScore")=>"Int64", Symbol("name")=>"String", Symbol("phone")=>"String", Symbol("postingId")=>"String", Symbol("source")=>"String", Symbol("status")=>"ApplicationStatus", )
OpenAPI.property_type(::Type{ JobApplication }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_JobApplication[name]))}

function OpenAPI.check_required(o::JobApplication)
    o.source === nothing && (return false)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::JobApplication)
    OpenAPI.validate_property(JobApplication, Symbol("cvFile"), o.cvFile)
    OpenAPI.validate_property(JobApplication, Symbol("cvText"), o.cvText)
    OpenAPI.validate_property(JobApplication, Symbol("email"), o.email)
    OpenAPI.validate_property(JobApplication, Symbol("matchReason"), o.matchReason)
    OpenAPI.validate_property(JobApplication, Symbol("matchScore"), o.matchScore)
    OpenAPI.validate_property(JobApplication, Symbol("name"), o.name)
    OpenAPI.validate_property(JobApplication, Symbol("phone"), o.phone)
    OpenAPI.validate_property(JobApplication, Symbol("postingId"), o.postingId)
    OpenAPI.validate_property(JobApplication, Symbol("source"), o.source)
    OpenAPI.validate_property(JobApplication, Symbol("status"), o.status)
end

function OpenAPI.validate_property(::Type{ JobApplication }, name::Symbol, val)





    if name === Symbol("matchScore")
        OpenAPI.validate_param(name, "JobApplication", :format, val, "int32")
    end



    if name === Symbol("postingId")
        OpenAPI.validate_param(name, "JobApplication", :format, val, "uuid")
    end


end
