# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ReturnOrderStatusUpdate

    ReturnOrderStatusUpdate(;
        status=nothing,
    )

    - status::String
"""
Base.@kwdef mutable struct ReturnOrderStatusUpdate <: OpenAPI.APIModel
    status::Union{Nothing, String} = nothing

    function ReturnOrderStatusUpdate(status, )
        o = new(status, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type ReturnOrderStatusUpdate

const _property_types_ReturnOrderStatusUpdate = Dict{Symbol,String}(Symbol("status")=>"String", )
OpenAPI.property_type(::Type{ ReturnOrderStatusUpdate }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ReturnOrderStatusUpdate[name]))}

function OpenAPI.check_required(o::ReturnOrderStatusUpdate)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::ReturnOrderStatusUpdate)
    OpenAPI.validate_property(ReturnOrderStatusUpdate, Symbol("status"), o.status)
end

function OpenAPI.validate_property(::Type{ ReturnOrderStatusUpdate }, name::Symbol, val)

end
