# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :AbsenceStatus)
    const AbsenceStatus = String
else
    @warn("Skipping redefinition of AbsenceStatus to String")
end
