# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BWAExpenses

    BWAExpenses(;
        expense_breakdown=nothing,
        total_expenses=nothing,
    )

    - expense_breakdown::Vector{ExpenseItem}
    - total_expenses::String
"""
Base.@kwdef mutable struct BWAExpenses <: OpenAPI.APIModel
    expense_breakdown::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{ExpenseItem} }
    total_expenses::Union{Nothing, String} = nothing

    function BWAExpenses(expense_breakdown, total_expenses, )
        o = new(expense_breakdown, total_expenses, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BWAExpenses

const _property_types_BWAExpenses = Dict{Symbol,String}(Symbol("expense_breakdown")=>"Vector{ExpenseItem}", Symbol("total_expenses")=>"String", )
OpenAPI.property_type(::Type{ BWAExpenses }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BWAExpenses[name]))}

function OpenAPI.check_required(o::BWAExpenses)
    o.expense_breakdown === nothing && (return false)
    o.total_expenses === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::BWAExpenses)
    OpenAPI.validate_property(BWAExpenses, Symbol("expense_breakdown"), o.expense_breakdown)
    OpenAPI.validate_property(BWAExpenses, Symbol("total_expenses"), o.total_expenses)
end

function OpenAPI.validate_property(::Type{ BWAExpenses }, name::Symbol, val)


end
