# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AiWorkerConfig

    AiWorkerConfig(;
        auto_reply=nothing,
        created_at=nothing,
        id=nothing,
        is_active=nothing,
        max_tool_calls=nothing,
        model=nothing,
        name=nothing,
        provider=nothing,
        system_prompt=nothing,
        tenant_id=nothing,
        trigger_on=nothing,
        updated_at=nothing,
    )

    - auto_reply::Bool
    - created_at::ZonedDateTime
    - id::String
    - is_active::Bool
    - max_tool_calls::Int64
    - model::String
    - name::String
    - provider::String
    - system_prompt::String
    - tenant_id::String
    - trigger_on::Vector{String}
    - updated_at::ZonedDateTime
"""
Base.@kwdef mutable struct AiWorkerConfig <: OpenAPI.APIModel
    auto_reply::Union{Nothing, Bool} = nothing
    created_at::Union{Nothing, ZonedDateTime} = nothing
    id::Union{Nothing, String} = nothing
    is_active::Union{Nothing, Bool} = nothing
    max_tool_calls::Union{Nothing, Int64} = nothing
    model::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    provider::Union{Nothing, String} = nothing
    system_prompt::Union{Nothing, String} = nothing
    tenant_id::Union{Nothing, String} = nothing
    trigger_on::Union{Nothing, Vector{String}} = nothing
    updated_at::Union{Nothing, ZonedDateTime} = nothing

    function AiWorkerConfig(auto_reply, created_at, id, is_active, max_tool_calls, model, name, provider, system_prompt, tenant_id, trigger_on, updated_at, )
        o = new(auto_reply, created_at, id, is_active, max_tool_calls, model, name, provider, system_prompt, tenant_id, trigger_on, updated_at, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type AiWorkerConfig

const _property_types_AiWorkerConfig = Dict{Symbol,String}(Symbol("auto_reply")=>"Bool", Symbol("created_at")=>"ZonedDateTime", Symbol("id")=>"String", Symbol("is_active")=>"Bool", Symbol("max_tool_calls")=>"Int64", Symbol("model")=>"String", Symbol("name")=>"String", Symbol("provider")=>"String", Symbol("system_prompt")=>"String", Symbol("tenant_id")=>"String", Symbol("trigger_on")=>"Vector{String}", Symbol("updated_at")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ AiWorkerConfig }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AiWorkerConfig[name]))}

function OpenAPI.check_required(o::AiWorkerConfig)
    o.auto_reply === nothing && (return false)
    o.created_at === nothing && (return false)
    o.id === nothing && (return false)
    o.is_active === nothing && (return false)
    o.max_tool_calls === nothing && (return false)
    o.model === nothing && (return false)
    o.name === nothing && (return false)
    o.provider === nothing && (return false)
    o.system_prompt === nothing && (return false)
    o.tenant_id === nothing && (return false)
    o.trigger_on === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::AiWorkerConfig)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("auto_reply"), o.auto_reply)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("created_at"), o.created_at)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("id"), o.id)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("is_active"), o.is_active)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("max_tool_calls"), o.max_tool_calls)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("model"), o.model)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("name"), o.name)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("provider"), o.provider)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("system_prompt"), o.system_prompt)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("tenant_id"), o.tenant_id)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("trigger_on"), o.trigger_on)
    OpenAPI.validate_property(AiWorkerConfig, Symbol("updated_at"), o.updated_at)
end

function OpenAPI.validate_property(::Type{ AiWorkerConfig }, name::Symbol, val)


    if name === Symbol("created_at")
        OpenAPI.validate_param(name, "AiWorkerConfig", :format, val, "date-time")
    end

    if name === Symbol("id")
        OpenAPI.validate_param(name, "AiWorkerConfig", :format, val, "uuid")
    end


    if name === Symbol("max_tool_calls")
        OpenAPI.validate_param(name, "AiWorkerConfig", :format, val, "int32")
    end





    if name === Symbol("tenant_id")
        OpenAPI.validate_param(name, "AiWorkerConfig", :format, val, "uuid")
    end


    if name === Symbol("updated_at")
        OpenAPI.validate_param(name, "AiWorkerConfig", :format, val, "date-time")
    end
end
