# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PublicPosting
Minimal shape for the public careers page (no tenant internals).

    PublicPosting(;
        currency=nothing,
        description=nothing,
        employmentType=nothing,
        id=nothing,
        location=nothing,
        remote=nothing,
        requiredSkills=nothing,
        requirements=nothing,
        salaryMax=nothing,
        salaryMin=nothing,
        title=nothing,
    )

    - currency::String
    - description::String
    - employmentType::String
    - id::String
    - location::String
    - remote::Bool
    - requiredSkills::Vector{String}
    - requirements::String
    - salaryMax::Int64
    - salaryMin::Int64
    - title::String
"""
Base.@kwdef mutable struct PublicPosting <: OpenAPI.APIModel
    currency::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    employmentType::Union{Nothing, String} = nothing
    id::Union{Nothing, String} = nothing
    location::Union{Nothing, String} = nothing
    remote::Union{Nothing, Bool} = nothing
    requiredSkills::Union{Nothing, Vector{String}} = nothing
    requirements::Union{Nothing, String} = nothing
    salaryMax::Union{Nothing, Int64} = nothing
    salaryMin::Union{Nothing, Int64} = nothing
    title::Union{Nothing, String} = nothing

    function PublicPosting(currency, description, employmentType, id, location, remote, requiredSkills, requirements, salaryMax, salaryMin, title, )
        o = new(currency, description, employmentType, id, location, remote, requiredSkills, requirements, salaryMax, salaryMin, title, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PublicPosting

const _property_types_PublicPosting = Dict{Symbol,String}(Symbol("currency")=>"String", Symbol("description")=>"String", Symbol("employmentType")=>"String", Symbol("id")=>"String", Symbol("location")=>"String", Symbol("remote")=>"Bool", Symbol("requiredSkills")=>"Vector{String}", Symbol("requirements")=>"String", Symbol("salaryMax")=>"Int64", Symbol("salaryMin")=>"Int64", Symbol("title")=>"String", )
OpenAPI.property_type(::Type{ PublicPosting }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PublicPosting[name]))}

function OpenAPI.check_required(o::PublicPosting)
    o.description === nothing && (return false)
    o.id === nothing && (return false)
    o.remote === nothing && (return false)
    o.requiredSkills === nothing && (return false)
    o.title === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PublicPosting)
    OpenAPI.validate_property(PublicPosting, Symbol("currency"), o.currency)
    OpenAPI.validate_property(PublicPosting, Symbol("description"), o.description)
    OpenAPI.validate_property(PublicPosting, Symbol("employmentType"), o.employmentType)
    OpenAPI.validate_property(PublicPosting, Symbol("id"), o.id)
    OpenAPI.validate_property(PublicPosting, Symbol("location"), o.location)
    OpenAPI.validate_property(PublicPosting, Symbol("remote"), o.remote)
    OpenAPI.validate_property(PublicPosting, Symbol("requiredSkills"), o.requiredSkills)
    OpenAPI.validate_property(PublicPosting, Symbol("requirements"), o.requirements)
    OpenAPI.validate_property(PublicPosting, Symbol("salaryMax"), o.salaryMax)
    OpenAPI.validate_property(PublicPosting, Symbol("salaryMin"), o.salaryMin)
    OpenAPI.validate_property(PublicPosting, Symbol("title"), o.title)
end

function OpenAPI.validate_property(::Type{ PublicPosting }, name::Symbol, val)




    if name === Symbol("id")
        OpenAPI.validate_param(name, "PublicPosting", :format, val, "uuid")
    end





    if name === Symbol("salaryMax")
        OpenAPI.validate_param(name, "PublicPosting", :format, val, "int32")
    end

    if name === Symbol("salaryMin")
        OpenAPI.validate_param(name, "PublicPosting", :format, val, "int32")
    end

end
