# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderTagsRequest

    OrderTagsRequest(;
        tags=nothing,
    )

    - tags::Vector{String}
"""
Base.@kwdef mutable struct OrderTagsRequest <: OpenAPI.APIModel
    tags::Union{Nothing, Vector{String}} = nothing

    function OrderTagsRequest(tags, )
        o = new(tags, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type OrderTagsRequest

const _property_types_OrderTagsRequest = Dict{Symbol,String}(Symbol("tags")=>"Vector{String}", )
OpenAPI.property_type(::Type{ OrderTagsRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderTagsRequest[name]))}

function OpenAPI.check_required(o::OrderTagsRequest)
    o.tags === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::OrderTagsRequest)
    OpenAPI.validate_property(OrderTagsRequest, Symbol("tags"), o.tags)
end

function OpenAPI.validate_property(::Type{ OrderTagsRequest }, name::Symbol, val)

end
