# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Coupon

    Coupon(;
        code=nothing,
        description=nothing,
        discountType=nothing,
        discountValue=nothing,
        expiresAt=nothing,
        isActive=nothing,
        isCombineable=nothing,
        maxDiscountAmount=nothing,
        maxUses=nothing,
        maxUsesPerCustomer=nothing,
        minOrderAmount=nothing,
        productIds=nothing,
        startsAt=nothing,
    )

    - code::String
    - description::String
    - discountType::DiscountType
    - discountValue::String
    - expiresAt::ZonedDateTime
    - isActive::Bool
    - isCombineable::Bool
    - maxDiscountAmount::String
    - maxUses::Int64
    - maxUsesPerCustomer::Int64
    - minOrderAmount::String
    - productIds::Any
    - startsAt::ZonedDateTime
"""
Base.@kwdef mutable struct Coupon <: OpenAPI.APIModel
    code::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    discountType = nothing # spec type: Union{ Nothing, DiscountType }
    discountValue::Union{Nothing, String} = nothing
    expiresAt::Union{Nothing, ZonedDateTime} = nothing
    isActive::Union{Nothing, Bool} = nothing
    isCombineable::Union{Nothing, Bool} = nothing
    maxDiscountAmount::Union{Nothing, String} = nothing
    maxUses::Union{Nothing, Int64} = nothing
    maxUsesPerCustomer::Union{Nothing, Int64} = nothing
    minOrderAmount::Union{Nothing, String} = nothing
    productIds::Union{Nothing, Any} = nothing
    startsAt::Union{Nothing, ZonedDateTime} = nothing

    function Coupon(code, description, discountType, discountValue, expiresAt, isActive, isCombineable, maxDiscountAmount, maxUses, maxUsesPerCustomer, minOrderAmount, productIds, startsAt, )
        o = new(code, description, discountType, discountValue, expiresAt, isActive, isCombineable, maxDiscountAmount, maxUses, maxUsesPerCustomer, minOrderAmount, productIds, startsAt, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type Coupon

const _property_types_Coupon = Dict{Symbol,String}(Symbol("code")=>"String", Symbol("description")=>"String", Symbol("discountType")=>"DiscountType", Symbol("discountValue")=>"String", Symbol("expiresAt")=>"ZonedDateTime", Symbol("isActive")=>"Bool", Symbol("isCombineable")=>"Bool", Symbol("maxDiscountAmount")=>"String", Symbol("maxUses")=>"Int64", Symbol("maxUsesPerCustomer")=>"Int64", Symbol("minOrderAmount")=>"String", Symbol("productIds")=>"Any", Symbol("startsAt")=>"ZonedDateTime", )
OpenAPI.property_type(::Type{ Coupon }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Coupon[name]))}

function OpenAPI.check_required(o::Coupon)
    o.code === nothing && (return false)
    o.discountType === nothing && (return false)
    o.discountValue === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::Coupon)
    OpenAPI.validate_property(Coupon, Symbol("code"), o.code)
    OpenAPI.validate_property(Coupon, Symbol("description"), o.description)
    OpenAPI.validate_property(Coupon, Symbol("discountType"), o.discountType)
    OpenAPI.validate_property(Coupon, Symbol("discountValue"), o.discountValue)
    OpenAPI.validate_property(Coupon, Symbol("expiresAt"), o.expiresAt)
    OpenAPI.validate_property(Coupon, Symbol("isActive"), o.isActive)
    OpenAPI.validate_property(Coupon, Symbol("isCombineable"), o.isCombineable)
    OpenAPI.validate_property(Coupon, Symbol("maxDiscountAmount"), o.maxDiscountAmount)
    OpenAPI.validate_property(Coupon, Symbol("maxUses"), o.maxUses)
    OpenAPI.validate_property(Coupon, Symbol("maxUsesPerCustomer"), o.maxUsesPerCustomer)
    OpenAPI.validate_property(Coupon, Symbol("minOrderAmount"), o.minOrderAmount)
    OpenAPI.validate_property(Coupon, Symbol("productIds"), o.productIds)
    OpenAPI.validate_property(Coupon, Symbol("startsAt"), o.startsAt)
end

function OpenAPI.validate_property(::Type{ Coupon }, name::Symbol, val)

    if name === Symbol("code")
        OpenAPI.validate_param(name, "Coupon", :maxLength, val, 50)
        OpenAPI.validate_param(name, "Coupon", :minLength, val, 1)
    end

    if name === Symbol("description")
        OpenAPI.validate_param(name, "Coupon", :maxLength, val, 500)
    end



    if name === Symbol("expiresAt")
        OpenAPI.validate_param(name, "Coupon", :format, val, "date-time")
    end




    if name === Symbol("maxUses")
        OpenAPI.validate_param(name, "Coupon", :format, val, "int32")
    end

    if name === Symbol("maxUsesPerCustomer")
        OpenAPI.validate_param(name, "Coupon", :format, val, "int32")
    end



    if name === Symbol("startsAt")
        OpenAPI.validate_param(name, "Coupon", :format, val, "date-time")
    end
end
