# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TenantUser

    TenantUser(;
        email=nothing,
        email_verified=nothing,
        is_active=nothing,
        joined_at=nothing,
        last_login=nothing,
        name=nothing,
        permissions=nothing,
        role=nothing,
        user_id=nothing,
    )

    - email::String
    - email_verified::Bool
    - is_active::Bool
    - joined_at::ZonedDateTime
    - last_login::ZonedDateTime
    - name::String
    - permissions::Vector{String}
    - role::String
    - user_id::String
"""
Base.@kwdef mutable struct TenantUser <: OpenAPI.APIModel
    email::Union{Nothing, String} = nothing
    email_verified::Union{Nothing, Bool} = nothing
    is_active::Union{Nothing, Bool} = nothing
    joined_at::Union{Nothing, ZonedDateTime} = nothing
    last_login::Union{Nothing, ZonedDateTime} = nothing
    name::Union{Nothing, String} = nothing
    permissions::Union{Nothing, Vector{String}} = nothing
    role::Union{Nothing, String} = nothing
    user_id::Union{Nothing, String} = nothing

    function TenantUser(email, email_verified, is_active, joined_at, last_login, name, permissions, role, user_id, )
        o = new(email, email_verified, is_active, joined_at, last_login, name, permissions, role, user_id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TenantUser

const _property_types_TenantUser = Dict{Symbol,String}(Symbol("email")=>"String", Symbol("email_verified")=>"Bool", Symbol("is_active")=>"Bool", Symbol("joined_at")=>"ZonedDateTime", Symbol("last_login")=>"ZonedDateTime", Symbol("name")=>"String", Symbol("permissions")=>"Vector{String}", Symbol("role")=>"String", Symbol("user_id")=>"String", )
OpenAPI.property_type(::Type{ TenantUser }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TenantUser[name]))}

function OpenAPI.check_required(o::TenantUser)
    o.email === nothing && (return false)
    o.email_verified === nothing && (return false)
    o.is_active === nothing && (return false)
    o.joined_at === nothing && (return false)
    o.name === nothing && (return false)
    o.permissions === nothing && (return false)
    o.role === nothing && (return false)
    o.user_id === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TenantUser)
    OpenAPI.validate_property(TenantUser, Symbol("email"), o.email)
    OpenAPI.validate_property(TenantUser, Symbol("email_verified"), o.email_verified)
    OpenAPI.validate_property(TenantUser, Symbol("is_active"), o.is_active)
    OpenAPI.validate_property(TenantUser, Symbol("joined_at"), o.joined_at)
    OpenAPI.validate_property(TenantUser, Symbol("last_login"), o.last_login)
    OpenAPI.validate_property(TenantUser, Symbol("name"), o.name)
    OpenAPI.validate_property(TenantUser, Symbol("permissions"), o.permissions)
    OpenAPI.validate_property(TenantUser, Symbol("role"), o.role)
    OpenAPI.validate_property(TenantUser, Symbol("user_id"), o.user_id)
end

function OpenAPI.validate_property(::Type{ TenantUser }, name::Symbol, val)




    if name === Symbol("joined_at")
        OpenAPI.validate_param(name, "TenantUser", :format, val, "date-time")
    end

    if name === Symbol("last_login")
        OpenAPI.validate_param(name, "TenantUser", :format, val, "date-time")
    end




    if name === Symbol("user_id")
        OpenAPI.validate_param(name, "TenantUser", :format, val, "uuid")
    end
end
