# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PayrollSummaryItem

    PayrollSummaryItem(;
        employee_count=nothing,
        month=nothing,
        status=nothing,
        total_employer_cost=nothing,
        total_gross=nothing,
        total_net=nothing,
        year=nothing,
    )

    - employee_count::Int64
    - month::String
    - status::PayrollRunStatus
    - total_employer_cost::String
    - total_gross::String
    - total_net::String
    - year::Int64
"""
Base.@kwdef mutable struct PayrollSummaryItem <: OpenAPI.APIModel
    employee_count::Union{Nothing, Int64} = nothing
    month::Union{Nothing, String} = nothing
    status = nothing # spec type: Union{ Nothing, PayrollRunStatus }
    total_employer_cost::Union{Nothing, String} = nothing
    total_gross::Union{Nothing, String} = nothing
    total_net::Union{Nothing, String} = nothing
    year::Union{Nothing, Int64} = nothing

    function PayrollSummaryItem(employee_count, month, status, total_employer_cost, total_gross, total_net, year, )
        o = new(employee_count, month, status, total_employer_cost, total_gross, total_net, year, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type PayrollSummaryItem

const _property_types_PayrollSummaryItem = Dict{Symbol,String}(Symbol("employee_count")=>"Int64", Symbol("month")=>"String", Symbol("status")=>"PayrollRunStatus", Symbol("total_employer_cost")=>"String", Symbol("total_gross")=>"String", Symbol("total_net")=>"String", Symbol("year")=>"Int64", )
OpenAPI.property_type(::Type{ PayrollSummaryItem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PayrollSummaryItem[name]))}

function OpenAPI.check_required(o::PayrollSummaryItem)
    o.employee_count === nothing && (return false)
    o.month === nothing && (return false)
    o.status === nothing && (return false)
    o.total_employer_cost === nothing && (return false)
    o.total_gross === nothing && (return false)
    o.total_net === nothing && (return false)
    o.year === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::PayrollSummaryItem)
    OpenAPI.validate_property(PayrollSummaryItem, Symbol("employee_count"), o.employee_count)
    OpenAPI.validate_property(PayrollSummaryItem, Symbol("month"), o.month)
    OpenAPI.validate_property(PayrollSummaryItem, Symbol("status"), o.status)
    OpenAPI.validate_property(PayrollSummaryItem, Symbol("total_employer_cost"), o.total_employer_cost)
    OpenAPI.validate_property(PayrollSummaryItem, Symbol("total_gross"), o.total_gross)
    OpenAPI.validate_property(PayrollSummaryItem, Symbol("total_net"), o.total_net)
    OpenAPI.validate_property(PayrollSummaryItem, Symbol("year"), o.year)
end

function OpenAPI.validate_property(::Type{ PayrollSummaryItem }, name::Symbol, val)

    if name === Symbol("employee_count")
        OpenAPI.validate_param(name, "PayrollSummaryItem", :format, val, "int32")
    end






    if name === Symbol("year")
        OpenAPI.validate_param(name, "PayrollSummaryItem", :format, val, "int32")
    end
end
